LightShow_Boilerplate: RenderTextureBase Class Reference
RenderTextureBase Class Reference
The RenderTextureBase class is used to create a texture that you can render to. This is not a component.
#include <RenderTexture.h>
Public Member Functions
GLint getTextureID () const
GLuint getFBO () const
unsigned int getWidth () const
unsigned int getHeight () const
virtual void initialize (unsigned int w, unsigned int h)
Initializes the texture.
virtual void resize (unsigned int w, unsigned int h)
Resizes the texture.
virtual ~RenderTextureBase ()
Protected Member Functions
void freeGLIds ()
Frees openGL id's.
Protected Attributes
unsigned int width = 0
unsigned int height = 0
GLuint textureFBO = 0
GLuint textureID = 0
GLuint textureRBO = 0
GLenum status
bool initialized = false
Detailed Description
The RenderTextureBase class is used to create a texture that you can render to. This is not a component.
Definition at line 12 of file RenderTexture.h.
Constructor & Destructor Documentation
~RenderTextureBase()
RenderTextureBase::~RenderTextureBase () virtual
Definition at line 40 of file RenderTexture.cpp.
References DBG_LOG, and freeGLIds().
Member Function Documentation
freeGLIds()
void RenderTextureBase::freeGLIds () protected
Frees openGL id's.
Definition at line 45 of file RenderTexture.cpp.
References initialized, textureFBO, textureID, and textureRBO.
Referenced by RenderTextureMS::getMaxMultisample(), resize(), RenderTextureMS::resize(), and ~RenderTextureBase().
getFBO()
GLuint RenderTextureBase::getFBO () const inline
Definition at line 16 of file RenderTexture.h.
References textureFBO.
Referenced by RenderingSystem::render().
getHeight()
unsigned int RenderTextureBase::getHeight () const inline
Definition at line 19 of file RenderTexture.h.
References height.
Referenced by RenderingSystem::render().
getTextureID()
GLint RenderTextureBase::getTextureID () const inline
Definition at line 15 of file RenderTexture.h.
References textureID.
Referenced by RenderingSystem::render().
getWidth()
unsigned int RenderTextureBase::getWidth () const inline
Definition at line 18 of file RenderTexture.h.
References width.
Referenced by RenderingSystem::render().
initialize()
void RenderTextureBase::initialize (unsigned int w, unsigned int h) virtual
Initializes the texture.
Reimplemented in RenderTextureMS.
Definition at line 2 of file RenderTexture.cpp.
References DBG_LOG, height, initialized, status, textureFBO, textureID, textureRBO, and width.
Referenced by resize().
resize()
void RenderTextureBase::resize (unsigned int w, unsigned int h) virtual
Resizes the texture.
Reimplemented in RenderTextureMS.
Definition at line 35 of file RenderTexture.cpp.
References freeGLIds(), and initialize().
Referenced by FixedUpdatingSystem::handleBackEndMessage().
Member Data Documentation
height
unsigned int RenderTextureBase::height = 0 protected
Definition at line 34 of file RenderTexture.h.
Referenced by getHeight(), initialize(), and RenderTextureMS::initializeUnsafe().
initialized
bool RenderTextureBase::initialized = false protected
Definition at line 41 of file RenderTexture.h.
Referenced by freeGLIds(), initialize(), and RenderTextureMS::initializeUnsafe().
status
GLenum RenderTextureBase::status protected
Definition at line 40 of file RenderTexture.h.
Referenced by RenderTextureMS::getMaxMultisample(), initialize(), and RenderTextureMS::initializeUnsafe().
textureFBO
GLuint RenderTextureBase::textureFBO = 0 protected
Definition at line 36 of file RenderTexture.h.
Referenced by freeGLIds(), getFBO(), initialize(), and RenderTextureMS::initializeUnsafe().
textureID
GLuint RenderTextureBase::textureID = 0 protected
Definition at line 37 of file RenderTexture.h.
Referenced by freeGLIds(), getTextureID(), initialize(), and RenderTextureMS::initializeUnsafe().
textureRBO
GLuint RenderTextureBase::textureRBO = 0 protected
Definition at line 38 of file RenderTexture.h.
Referenced by freeGLIds(), initialize(), and RenderTextureMS::initializeUnsafe().
width
unsigned int RenderTextureBase::width = 0 protected
Definition at line 33 of file RenderTexture.h.
Referenced by getWidth(), initialize(), and RenderTextureMS::initializeUnsafe().
The documentation for this class was generated from the following files:
src/game/rendering/RenderTexture.h
src/game/rendering/RenderTexture.cpp