LightShow_Boilerplate: TextMap Class Reference
TextMap Class Reference
#include <TextMap.h>
Public Member Functions
void createMap (const std::string &textDatMapLocation)
const Glyph *const getGlyph (const char &key)
uint32_t getMaxPixelHeightOfAllGlyphs ()
Private Attributes
bool isBigEndianness = false
uint32_t maxPixelHeight = 0
std::vector< Glyph > map
Detailed Description
Definition at line 8 of file TextMap.h.
Member Function Documentation
createMap()
void TextMap::createMap (const std::string & textDatMapLocation)
Definition at line 23 of file TextMap.cpp.
References Glyph::character, Glyph::getHeight(), SL::isBigEndian(), isBigEndianness, map, maxPixelHeight, SL::readBytes(), Glyph::x, Glyph::xMax, Glyph::y, and Glyph::yMax.
getGlyph()
const Glyph *const TextMap::getGlyph (const char & key)
Definition at line 3 of file TextMap.cpp.
References map.
Referenced by GuiString::mainRender().
getMaxPixelHeightOfAllGlyphs()
uint32_t TextMap::getMaxPixelHeightOfAllGlyphs () inline
Definition at line 15 of file TextMap.h.
References maxPixelHeight.
Referenced by GuiString::mainRender().
Member Data Documentation
isBigEndianness
bool TextMap::isBigEndianness = false private
Definition at line 20 of file TextMap.h.
Referenced by createMap().
map
std::vector<Glyph> TextMap::map private
Definition at line 24 of file TextMap.h.
Referenced by createMap(), and getGlyph().
maxPixelHeight
uint32_t TextMap::maxPixelHeight = 0 private
Definition at line 22 of file TextMap.h.
Referenced by createMap(), and getMaxPixelHeightOfAllGlyphs().
The documentation for this class was generated from the following files:
src/TextMap.h
src/TextMap.cpp