LightShow_Boilerplate: GUIResizingInformation Class Reference
GUIResizingInformation Class Reference
#include <GUIResizingInfo.h>
Public Member Functions
int getTopScreenPosition () const
int getBottomScreenPosition () const
int getLeftScreenPosition () const
int getRightScreenPosition () const
float getWidthUnit () const
float getHeightUnit () const
void updateInformation ()
Private Attributes
float widthByWidth = 0
float heightByHeight = 0
Detailed Description
Definition at line 5 of file GUIResizingInfo.h.
Member Function Documentation
getBottomScreenPosition()
int GUIResizingInformation::getBottomScreenPosition () const inline
Definition at line 9 of file GUIResizingInfo.h.
References GameInfo::getWindowHeight().
getHeightUnit()
float GUIResizingInformation::getHeightUnit () const inline
Definition at line 14 of file GUIResizingInfo.h.
References heightByHeight.
getLeftScreenPosition()
int GUIResizingInformation::getLeftScreenPosition () const inline
Definition at line 10 of file GUIResizingInfo.h.
References GameInfo::getWindowWidth().
Referenced by DisplayStatisticsSystem::fixedUpdate().
getRightScreenPosition()
int GUIResizingInformation::getRightScreenPosition () const inline
Definition at line 11 of file GUIResizingInfo.h.
References GameInfo::getWindowWidth().
getTopScreenPosition()
int GUIResizingInformation::getTopScreenPosition () const inline
Definition at line 8 of file GUIResizingInfo.h.
References GameInfo::getWindowHeight().
Referenced by DisplayStatisticsSystem::fixedUpdate().
getWidthUnit()
float GUIResizingInformation::getWidthUnit () const inline
Definition at line 13 of file GUIResizingInfo.h.
References widthByWidth.
Referenced by DisplayStatisticsSystem::fixedUpdate(), and PauseMenuSystem::update().
updateInformation()
void GUIResizingInformation::updateInformation () inline
Definition at line 16 of file GUIResizingInfo.h.
References GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), heightByHeight, GameInfo::START_WINDOW_HEIGHT, GameInfo::START_WINDOW_WIDTH, and widthByWidth.
Referenced by FixedUpdatingSystem::handleBackEndMessage(), and FixedUpdatingSystem::initialize().
Member Data Documentation
heightByHeight
float GUIResizingInformation::heightByHeight = 0 private
Definition at line 23 of file GUIResizingInfo.h.
Referenced by getHeightUnit(), and updateInformation().
widthByWidth
float GUIResizingInformation::widthByWidth = 0 private
Definition at line 22 of file GUIResizingInfo.h.
Referenced by getWidthUnit(), and updateInformation().
The documentation for this class was generated from the following file:
src/GUIResizingInfo.h