LightShow_Boilerplate: RenderTextureMS Class Reference
RenderTextureMS Class Reference
The RenderTextureMS class is used to create a multisampled texture that you can render to. This is a component.
#include <RenderTexture.h>
Public Member Functions
virtual ~RenderTextureMS ()
void resize (unsigned int w, unsigned int h)
Resize the texture.
void resize (unsigned int w, unsigned int h, unsigned int samples)
Resize the texture and set the multisamples.
void initialize (unsigned int w, unsigned int h)
Initialize.
void initialize (unsigned int w, unsigned int h, unsigned int samples)
int getCurrentMultisampleCount () const
Public Member Functions inherited from RenderTextureBase
GLint getTextureID () const
GLuint getFBO () const
unsigned int getWidth () const
unsigned int getHeight () const
virtual ~RenderTextureBase ()
Public Member Functions inherited from Component< RenderTextureMS >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Static Public Member Functions
static int getMaxMultisample ()
Retrieves the max amount of multisamples the computer can handle if it hasn't already.
Private Member Functions
void initializeUnsafe (unsigned int w, unsigned int h, unsigned int samples)
Doesn't check if samples are supported. (prevents recursion in getMaxMultisample()).
Private Attributes
int currentMultisamples = -1
used for resizing.
Additional Inherited Members
Static Public Attributes inherited from Component< RenderTextureMS >
static int32_t type
Protected Member Functions inherited from RenderTextureBase
void freeGLIds ()
Frees openGL id's.
Protected Attributes inherited from RenderTextureBase
unsigned int width = 0
unsigned int height = 0
GLuint textureFBO = 0
GLuint textureID = 0
GLuint textureRBO = 0
GLenum status
bool initialized = false
Detailed Description
The RenderTextureMS class is used to create a multisampled texture that you can render to. This is a component.
Definition at line 50 of file RenderTexture.h.
Constructor & Destructor Documentation
~RenderTextureMS()
virtual RenderTextureMS::~RenderTextureMS () inline virtual
Definition at line 53 of file RenderTexture.h.
Member Function Documentation
getCurrentMultisampleCount()
int RenderTextureMS::getCurrentMultisampleCount () const inline
Definition at line 69 of file RenderTexture.h.
References currentMultisamples.
Referenced by RenderingSystem::render().
getMaxMultisample()
int RenderTextureMS::getMaxMultisample () static
Retrieves the max amount of multisamples the computer can handle if it hasn't already.
Definition at line 55 of file RenderTexture.cpp.
References DBG_LOG, RenderTextureBase::freeGLIds(), initializeUnsafe(), and RenderTextureBase::status.
Referenced by initialize(), and resize().
initialize() [1/2]
void RenderTextureMS::initialize (unsigned int w, unsigned int h) virtual
Initialize.
Reimplemented from RenderTextureBase.
Definition at line 90 of file RenderTexture.cpp.
References getMaxMultisample().
Referenced by resize().
initialize() [2/2]
void RenderTextureMS::initialize (unsigned int w, unsigned int h, unsigned int samples)
Definition at line 94 of file RenderTexture.cpp.
References DBG_LOG, getMaxMultisample(), and initializeUnsafe().
initializeUnsafe()
void RenderTextureMS::initializeUnsafe (unsigned int w, unsigned int h, unsigned int samples) private
Doesn't check if samples are supported. (prevents recursion in getMaxMultisample()).
Definition at line 104 of file RenderTexture.cpp.
References currentMultisamples, DBG_LOG, RenderTextureBase::height, RenderTextureBase::initialized, RenderTextureBase::status, RenderTextureBase::textureFBO, RenderTextureBase::textureID, RenderTextureBase::textureRBO, and RenderTextureBase::width.
Referenced by getMaxMultisample(), and initialize().
resize() [1/2]
void RenderTextureMS::resize (unsigned int w, unsigned int h) virtual
Resize the texture.
Reimplemented from RenderTextureBase.
Definition at line 78 of file RenderTexture.cpp.
References currentMultisamples, RenderTextureBase::freeGLIds(), getMaxMultisample(), and initialize().
resize() [2/2]
void RenderTextureMS::resize (unsigned int w, unsigned int h, unsigned int samples)
Resize the texture and set the multisamples.
Definition at line 85 of file RenderTexture.cpp.
References RenderTextureBase::freeGLIds(), and initialize().
Member Data Documentation
currentMultisamples
int RenderTextureMS::currentMultisamples = -1 private
used for resizing.
Definition at line 75 of file RenderTexture.h.
Referenced by getCurrentMultisampleCount(), initializeUnsafe(), and resize().
The documentation for this class was generated from the following files:
src/game/rendering/RenderTexture.h
src/game/rendering/RenderTexture.cpp