LightShow_Boilerplate: EnemyTestObject Class Reference
EnemyTestObject Class Reference
Test entity class.
#include <EntityTests.h>
Public Member Functions
~EnemyTestObject ()
void initialize (EntityVitals &vitals)
Public Member Functions inherited from EntityWrapper
virtual ~EntityWrapper ()
Private Attributes
_3DM::AnimatedModel model = _3DM::AnimatedModel("assets/Models/player/testplayer.3DMA")
EntityTransform transform
GlobalInformation info
EnemyController controller = EnemyController(glm::vec3(0, .5f, 0))
CollisionMesh collisionMesh
SimpleMaterial material
Shader shader
Detailed Description
Test entity class.
Definition at line 116 of file EntityTests.h.
Constructor & Destructor Documentation
~EnemyTestObject()
EnemyTestObject::~EnemyTestObject () inline
Definition at line 119 of file EntityTests.h.
Member Function Documentation
initialize()
void EnemyTestObject::initialize (EntityVitals & vitals) virtual
Implements EntityWrapper.
Definition at line 107 of file EntityTests.cpp.
References Scene::addComponent(), _3DM::AnimatedModel::amountOfMeshes(), EntityVitals::checkForNulls(), collisionMesh, controller, EntityVitals::currentSettings, DBG_LOG, Scene::generateEntity(), CollisionMesh::getRigidBody(), Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), info, CollisionMesh::initialize(), material, model, EntityVitals::scene, _3DM::AnimatedModel::setAnimationClip(), _3DM::AnimatedModel::setMeshMatrix(), shader, SimpleMaterial::shininess, and transform.
Member Data Documentation
collisionMesh
CollisionMesh EnemyTestObject::collisionMesh private
Definition at line 128 of file EntityTests.h.
Referenced by initialize().
controller
EnemyController EnemyTestObject::controller = EnemyController(glm::vec3(0, .5f, 0)) private
Definition at line 127 of file EntityTests.h.
Referenced by initialize().
info
GlobalInformation EnemyTestObject::info private
Definition at line 126 of file EntityTests.h.
Referenced by initialize().
material
SimpleMaterial EnemyTestObject::material private
Definition at line 129 of file EntityTests.h.
Referenced by initialize().
model
_3DM::AnimatedModel EnemyTestObject::model = _3DM::AnimatedModel("assets/Models/player/testplayer.3DMA") private
Definition at line 123 of file EntityTests.h.
Referenced by initialize().
shader
Shader EnemyTestObject::shader private
Definition at line 130 of file EntityTests.h.
Referenced by initialize().
transform
EntityTransform EnemyTestObject::transform private
Definition at line 125 of file EntityTests.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/EntityTests.h
src/EntityTests.cpp