LightShow_Boilerplate: DebugDrawer Class Reference
DebugDrawer Class Reference
#include <DebugDrawer.h>
Public Member Functions
void render (const glm::mat4 &projectionMatrix, const glm::mat4 &viewMatrix)
void initialize ()
DebugDrawer ()
~DebugDrawer ()
virtual void drawLine (const btVector3 &from, const btVector3 &to, const btVector3 &color)
virtual void drawContactPoint (const btVector3 &, const btVector3 &, btScalar, int, const btVector3 &)
virtual void reportErrorWarning (const char *warningString)
virtual void draw3dText (const btVector3 &, const char *)
virtual void setDebugMode (int debugMode)
virtual int getDebugMode () const
Private Attributes
Shader thisShader
glm::mat4 identitym = glm::mat4(1.0f)
int currentDebugMode = 0
unsigned int currentMaxAmountOfVertices = 0
unsigned int currentAmountOfLines = 0
GLuint VAO = 0
GLuint vertID = 0
GLint positionAttribute = 0
GLint projectionLocation = 0
GLint viewLocation = 0
bool initialized = false
Detailed Description
Definition at line 15 of file DebugDrawer.h.
Constructor & Destructor Documentation
DebugDrawer()
DebugDrawer::DebugDrawer () inline
Definition at line 21 of file DebugDrawer.h.
~DebugDrawer()
DebugDrawer::~DebugDrawer ()
Definition at line 48 of file DebugDrawer.cpp.
Member Function Documentation
draw3dText()
virtual void DebugDrawer::draw3dText (const btVector3 & , const char *) inline virtual
Definition at line 30 of file DebugDrawer.h.
drawContactPoint()
virtual void DebugDrawer::drawContactPoint (const btVector3 & , const btVector3 & , btScalar , int , const btVector3 &) inline virtual
Definition at line 26 of file DebugDrawer.h.
drawLine()
void DebugDrawer::drawLine (const btVector3 & from, const btVector3 & to, const btVector3 & color) virtual
Definition at line 60 of file DebugDrawer.cpp.
getDebugMode()
virtual int DebugDrawer::getDebugMode () const inline virtual
Definition at line 34 of file DebugDrawer.h.
References currentDebugMode.
initialize()
void DebugDrawer::initialize ()
Definition at line 28 of file DebugDrawer.cpp.
Referenced by PhysicsWorld::initializeDebugDraw().
render()
void DebugDrawer::render (const glm::mat4 & projectionMatrix, const glm::mat4 & viewMatrix)
Definition at line 3 of file DebugDrawer.cpp.
Referenced by PhysicsWorld::debugDraw().
reportErrorWarning()
void DebugDrawer::reportErrorWarning (const char * warningString) virtual
Definition at line 73 of file DebugDrawer.cpp.
setDebugMode()
void DebugDrawer::setDebugMode (int debugMode) virtual
Definition at line 69 of file DebugDrawer.cpp.
Referenced by PhysicsWorld::initializeDebugDraw(), and PhysicsWorld::setDebugMode().
Member Data Documentation
currentAmountOfLines
unsigned int DebugDrawer::currentAmountOfLines = 0 private
Definition at line 45 of file DebugDrawer.h.
currentDebugMode
int DebugDrawer::currentDebugMode = 0 private
Definition at line 43 of file DebugDrawer.h.
Referenced by getDebugMode().
currentMaxAmountOfVertices
unsigned int DebugDrawer::currentMaxAmountOfVertices = 0 private
Definition at line 44 of file DebugDrawer.h.
identitym
glm::mat4 DebugDrawer::identitym = glm::mat4(1.0f) private
Definition at line 39 of file DebugDrawer.h.
initialized
bool DebugDrawer::initialized = false private
Definition at line 53 of file DebugDrawer.h.
positionAttribute
GLint DebugDrawer::positionAttribute = 0 private
Definition at line 50 of file DebugDrawer.h.
projectionLocation
GLint DebugDrawer::projectionLocation = 0 private
Definition at line 51 of file DebugDrawer.h.
thisShader
Shader DebugDrawer::thisShader private
Definition at line 37 of file DebugDrawer.h.
VAO
GLuint DebugDrawer::VAO = 0 private
Definition at line 47 of file DebugDrawer.h.
vertID
GLuint DebugDrawer::vertID = 0 private
Definition at line 48 of file DebugDrawer.h.
viewLocation
GLint DebugDrawer::viewLocation = 0 private
Definition at line 52 of file DebugDrawer.h.
The documentation for this class was generated from the following files:
src/DebugDrawer.h
src/DebugDrawer.cpp