LightShow_Boilerplate: Game Class Reference
Game Class Reference
#include <Game.h>
Public Member Functions
void initialize (Time *time, Messenger< BackEndMessages > *backEndMessagingSystem)
void resetVitals (Time *time, Messenger< BackEndMessages > *backEndMessagingSystem)
void fixedUpdate ()
void render ()
void update ()
void uninitialize ()
Private Member Functions
bool areVitalsNull ()
void initializeShaders ()
void readBackendEventQueue ()
void freeEntities ()
void loadScene (int scene)
Private Attributes
Messenger< BackEndMessages > * backEndMessages = nullptr
Time * currentTime = nullptr
Settings settings = Settings(GameInfo::DEFAULT_GRAVITY, glm::vec3(-20, 0, 10))
PointLightShadowMap pointLightDepthMap
DirectionalLightShadowMap directionalLightDepthMap
RenderTexture renderTexture
UpdatingSystem updatingSystem
FixedUpdatingSystem fixedUpdatingSystem
RenderingSystem renderingSystem
SubSystems subSystems
Scene * scene = new Scene()
PhysicsWorld * physicsWorld = new PhysicsWorld(hh::toBtVec3(GameInfo::DEFAULT_GRAVITY))
std::vector< EntityWrapper * > sceneEntities
int currentScene = 0
TextMap map
Detailed Description
Definition at line 10 of file Game.h.
Member Function Documentation
areVitalsNull()
bool Game::areVitalsNull () private
Definition at line 8 of file Game.cpp.
References backEndMessages, currentTime, and DBG_LOG.
Referenced by fixedUpdate(), initialize(), and render().
fixedUpdate()
void Game::fixedUpdate ()
Definition at line 110 of file Game.cpp.
References areVitalsNull(), currentScene, currentTime, directionalLightDepthMap, FixedUpdatingSystem::fixedUpdate(), fixedUpdatingSystem, Locator< Input, NullInput >::getService(), loadScene(), pointLightDepthMap, readBackendEventQueue(), and scenes.
Referenced by Application::fixedUpdate().
freeEntities()
void Game::freeEntities () private
Definition at line 137 of file Game.cpp.
References sceneEntities.
Referenced by loadScene(), and uninitialize().
initialize()
void Game::initialize (Time * time, Messenger< BackEndMessages > * backEndMessagingSystem)
Definition at line 17 of file Game.cpp.
References areVitalsNull(), backEndMessages, TextMap::createMap(), currentTime, initializeShaders(), loadScene(), map, and Entities::registerEntities().
Referenced by Application::initialize().
initializeShaders()
void Game::initializeShaders () private
Definition at line 35 of file Game.cpp.
References directionalLightDepthMap, DirectionalLightShadowMap::getDepthMapShader(), PointLightShadowMap::getDepthMapShader(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), RenderTexture::initialize(), DirectionalLightShadowMap::initialize(), PointLightShadowMap::initialize(), pointLightDepthMap, renderTexture, Shader::setShaderTask(), and Shader::setShaderTaskShader().
Referenced by initialize().
loadScene()
void Game::loadScene (int scene) private
Definition at line 46 of file Game.cpp.
References Entities::allocateEntity(), currentScene, DBG_LOG, GameInfo::DEFAULT_GRAVITY, fixedUpdatingSystem, freeEntities(), UpdatingSystem::initialize(), RenderingSystem::initialize(), FixedUpdatingSystem::initialize(), map, Scene::performOperationsOnAllOfType(), physicsWorld, renderingSystem, scene, sceneEntities, scenes, settings, subSystems, hh::toBtVec3(), and updatingSystem.
Referenced by fixedUpdate(), and initialize().
readBackendEventQueue()
void Game::readBackendEventQueue () private
Definition at line 103 of file Game.cpp.
References backEndMessages, fixedUpdatingSystem, Messenger< T >::getMessagesThenRemove(), FixedUpdatingSystem::handleBackEndMessage(), and renderTexture.
Referenced by fixedUpdate().
render()
void Game::render ()
Definition at line 129 of file Game.cpp.
References areVitalsNull(), currentTime, directionalLightDepthMap, pointLightDepthMap, RenderingSystem::render(), renderingSystem, and renderTexture.
Referenced by Application::render().
resetVitals()
void Game::resetVitals (Time * time, Messenger< BackEndMessages > * backEndMessagingSystem)
Definition at line 3 of file Game.cpp.
References backEndMessages, and currentTime.
uninitialize()
void Game::uninitialize ()
Definition at line 148 of file Game.cpp.
References freeEntities(), physicsWorld, and scene.
Referenced by Application::uninitialize().
update()
void Game::update ()
Definition at line 125 of file Game.cpp.
References UpdatingSystem::update(), and updatingSystem.
Referenced by Application::update().
Member Data Documentation
backEndMessages
Messenger<BackEndMessages>* Game::backEndMessages = nullptr private
Definition at line 22 of file Game.h.
Referenced by areVitalsNull(), initialize(), readBackendEventQueue(), and resetVitals().
currentScene
int Game::currentScene = 0 private
Definition at line 48 of file Game.h.
Referenced by fixedUpdate(), and loadScene().
currentTime
Time* Game::currentTime = nullptr private
Definition at line 23 of file Game.h.
Referenced by areVitalsNull(), fixedUpdate(), initialize(), render(), and resetVitals().
directionalLightDepthMap
DirectionalLightShadowMap Game::directionalLightDepthMap private
Definition at line 35 of file Game.h.
Referenced by fixedUpdate(), initializeShaders(), and render().
fixedUpdatingSystem
FixedUpdatingSystem Game::fixedUpdatingSystem private
Definition at line 39 of file Game.h.
Referenced by fixedUpdate(), loadScene(), and readBackendEventQueue().
map
TextMap Game::map private
Definition at line 50 of file Game.h.
Referenced by initialize(), and loadScene().
physicsWorld
PhysicsWorld* Game::physicsWorld = new PhysicsWorld(hh::toBtVec3(GameInfo::DEFAULT_GRAVITY)) private
Definition at line 44 of file Game.h.
Referenced by loadScene(), and uninitialize().
pointLightDepthMap
PointLightShadowMap Game::pointLightDepthMap private
Definition at line 34 of file Game.h.
Referenced by fixedUpdate(), initializeShaders(), and render().
renderingSystem
RenderingSystem Game::renderingSystem private
Definition at line 40 of file Game.h.
Referenced by loadScene(), and render().
renderTexture
RenderTexture Game::renderTexture private
Definition at line 36 of file Game.h.
Referenced by initializeShaders(), readBackendEventQueue(), and render().
scene
Scene* Game::scene = new Scene() private
Definition at line 43 of file Game.h.
Referenced by loadScene(), and uninitialize().
sceneEntities
std::vector<EntityWrapper*> Game::sceneEntities private
Definition at line 46 of file Game.h.
Referenced by freeEntities(), and loadScene().
settings
Settings Game::settings = Settings(GameInfo::DEFAULT_GRAVITY, glm::vec3(-20, 0, 10)) private
Definition at line 32 of file Game.h.
Referenced by loadScene().
subSystems
SubSystems Game::subSystems private
Definition at line 41 of file Game.h.
Referenced by loadScene().
updatingSystem
UpdatingSystem Game::updatingSystem private
Definition at line 38 of file Game.h.
Referenced by loadScene(), and update().
The documentation for this class was generated from the following files:
src/Game.h
src/Game.cpp