LightShow_Boilerplate: BoneCollisionMesh Class Reference
BoneCollisionMesh Class Reference
#include <BoneCollisionMesh.h>
Public Member Functions
BoneCollisionMesh ()
template<typename T >
void addCollider (uint32_t boneID, const CollisionTag &cTag, const T &shape, const glm::vec3 &scale=glm::vec3(DEFAULT_BONE_COLLIDER_SCALE))
template<typename T >
void addCollider (uint32_t boneID, uint32_t entityID, COLLISION_TAGS tag, const T &shape, const glm::vec3 &scale=glm::vec3(DEFAULT_BONE_COLLIDER_SCALE))
template<typename func >
void iterateThroughColliders (func function)
void addCollider (uint32_t boneID, uint32_t entityID, COLLISION_TAGS tag, const glm::vec3 &scale=glm::vec3(DEFAULT_BONE_COLLIDER_SCALE))
void addCollider (uint32_t boneID, const CollisionTag &cTag, const glm::vec3 &scale=glm::vec3(DEFAULT_BONE_COLLIDER_SCALE))
void setCollisionTag (uint32_t boneID, const CollisionTag &cTag)
void setScale (const glm::vec3 &scale, uint32_t boneID)
void setOffset (const glm::vec3 &offset, uint32_t boneID)
void getColliderOffset (int32_t boneID, glm::vec3 &output) const
glm::vec3 getColliderOffset (int32_t boneID) const
const std::vector< const CollisionTag * > * getCollisionTags ()
Public Member Functions inherited from Component< BoneCollisionMesh >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
std::map< int32_t, glm::vec3 > boneOffsets
std::map< int32_t, CollisionMesh > colliders
std::vector< const CollisionTag * > collisionTags
Additional Inherited Members
Static Public Attributes inherited from Component< BoneCollisionMesh >
static int32_t type
Detailed Description
Definition at line 8 of file BoneCollisionMesh.h.
Constructor & Destructor Documentation
BoneCollisionMesh()
BoneCollisionMesh::BoneCollisionMesh () inline
Definition at line 11 of file BoneCollisionMesh.h.
Member Function Documentation
addCollider() [1/4]
void BoneCollisionMesh::addCollider (uint32_t boneID, const CollisionTag & cTag, const glm::vec3 & scale = glm::vec3(DEFAULT_BONE_COLLIDER_SCALE))
Definition at line 7 of file BoneCollisionMesh.cpp.
References addCollider().
addCollider() [2/4]
template<typename T > void BoneCollisionMesh::addCollider (uint32_t boneID, const CollisionTag & cTag, const T & shape, const glm::vec3 & scale = glm::vec3(DEFAULT_BONE_COLLIDER_SCALE)) inline
Definition at line 14 of file BoneCollisionMesh.h.
References colliders, collisionTags, and CollisionTag::entity.
Referenced by addCollider().
addCollider() [3/4]
void BoneCollisionMesh::addCollider (uint32_t boneID, uint32_t entityID, COLLISION_TAGS tag, const glm::vec3 & scale = glm::vec3(DEFAULT_BONE_COLLIDER_SCALE))
Definition at line 3 of file BoneCollisionMesh.cpp.
References addCollider(), and ComponentInterface::entityID.
addCollider() [4/4]
template<typename T > void BoneCollisionMesh::addCollider (uint32_t boneID, uint32_t entityID, COLLISION_TAGS tag, const T & shape, const glm::vec3 & scale = glm::vec3(DEFAULT_BONE_COLLIDER_SCALE)) inline
Definition at line 37 of file BoneCollisionMesh.h.
References addCollider(), and ComponentInterface::entityID.
getColliderOffset() [1/2]
glm::vec3 BoneCollisionMesh::getColliderOffset (int32_t boneID) const
Definition at line 54 of file BoneCollisionMesh.cpp.
References boneOffsets, and GameInfo::GLM_VEC3_ZERO.
getColliderOffset() [2/2]
void BoneCollisionMesh::getColliderOffset (int32_t boneID, glm::vec3 & output) const
Definition at line 44 of file BoneCollisionMesh.cpp.
References boneOffsets, and GameInfo::GLM_VEC3_ZERO.
Referenced by BoneCollisionMeshSystem::fixedUpdate().
getCollisionTags()
const std::vector<const CollisionTag*>* BoneCollisionMesh::getCollisionTags () inline
Definition at line 58 of file BoneCollisionMesh.h.
References collisionTags.
iterateThroughColliders()
template<typename func > void BoneCollisionMesh::iterateThroughColliders (func function) inline
Definition at line 42 of file BoneCollisionMesh.h.
References colliders.
Referenced by BoneCollisionMeshSystem::fixedUpdate().
setCollisionTag()
void BoneCollisionMesh::setCollisionTag (uint32_t boneID, const CollisionTag & cTag)
Definition at line 11 of file BoneCollisionMesh.cpp.
References colliders, and DBG_LOG.
setOffset()
void BoneCollisionMesh::setOffset (const glm::vec3 & offset, uint32_t boneID)
Definition at line 33 of file BoneCollisionMesh.cpp.
References boneOffsets, colliders, and DBG_LOG.
setScale()
void BoneCollisionMesh::setScale (const glm::vec3 & scale, uint32_t boneID)
Definition at line 22 of file BoneCollisionMesh.cpp.
References colliders, and DBG_LOG.
Member Data Documentation
boneOffsets
std::map<int32_t, glm::vec3> BoneCollisionMesh::boneOffsets private
Definition at line 61 of file BoneCollisionMesh.h.
Referenced by getColliderOffset(), and setOffset().
colliders
std::map<int32_t, CollisionMesh> BoneCollisionMesh::colliders private
Definition at line 62 of file BoneCollisionMesh.h.
Referenced by addCollider(), iterateThroughColliders(), setCollisionTag(), setOffset(), and setScale().
collisionTags
std::vector<const CollisionTag*> BoneCollisionMesh::collisionTags private
Definition at line 63 of file BoneCollisionMesh.h.
Referenced by addCollider(), and getCollisionTags().
The documentation for this class was generated from the following files:
src/BoneCollisionMesh.h
src/BoneCollisionMesh.cpp