LightShow_Boilerplate: FountainParticleSystem Class Reference
FountainParticleSystem Class Reference
#include <ParticleSystem.h>
Private Member Functions
void setParticleToDefault (Particle &particle, Particles &particles) override
void performParticleCalculations (Particle &particle, Particles &particles) override
Additional Inherited Members
Public Member Functions inherited from DefaultParticleSystem
virtual void renderParticles (Shader &shader, Particles &particles)
virtual void fixedUpdateParticles (Particles &particlesWrapper)
virtual void updateParticles (Particles &particlesWrapper)
Detailed Description
Definition at line 20 of file ParticleSystem.h.
Member Function Documentation
performParticleCalculations()
void FountainParticleSystem::performParticleCalculations (Particle & particle, Particles & particles) override private virtual
Reimplemented from DefaultParticleSystem.
Definition at line 131 of file ParticleSystem.cpp.
References Particle::color, Particles::currentWorldSettings, Particles::defaultColor, Particles::defaultLifeTime, GameInfo::getDeltaTime(), Settings::getGravity(), Settings::getWind(), Particle::position, Particle::size, Particle::speed, and Particle::weight.
setParticleToDefault()
void FountainParticleSystem::setParticleToDefault (Particle & particle, Particles & particles) override private virtual
Reimplemented from DefaultParticleSystem.
Definition at line 118 of file ParticleSystem.cpp.
References Particle::color, Particles::defaultColor, Particles::defaultLifeTime, Particles::defaultScale, Particles::emmisionPosition, hh::getRandomRange(), Particle::lifeTime, Particle::position, Particle::size, and Particle::speed.
The documentation for this class was generated from the following files:
src/game/systems/subsystems/ParticleSystem.h
src/game/systems/subsystems/ParticleSystem.cpp