LightShow_Boilerplate: DirectionalLightShadowMap Class Reference
DirectionalLightShadowMap Class Reference
#include <DirectionalLightShadowMap.h>
Classes
struct OrthographicBounds
Public Member Functions
const glm::mat4 *const getLightSpaceMatrix ()
GLint getDepthMapShader ()
GLint getDepthMap ()
GLuint getFBO ()
unsigned int getDepthMapWidth () const
unsigned int getDepthMapHeight () const
void setDepthMapResolution (const unsigned int &width, const unsigned int &height)
void setShadowActive (bool t)
bool isActive ()
glm::vec3 getCurrentLightDirection ()
void setCurrentLightDirection (const glm::vec3 &lightDir)
void updateDepthMap (const Camera &camera)
void initialize ()
~DirectionalLightShadowMap ()
Private Member Functions
void updateDepthMapResolution ()
Private Attributes
unsigned int DEPTH_MAP_WIDTH = 4096
unsigned int DEPTH_MAP_HEIGHT = 4096
const float securityAdditiveForDirection = .0001f
OrthographicBounds bounds { -40.0f, 40.0f, -40.0f, 40.0f, -150.0f, 150.0f }
glm::vec3 lightDirection = glm::vec3(0.0001f, -1.f, 0)
bool lightSupplied = false
glm::mat4 lightSpaceMatrix
GLuint depthMapFBO
Shader depthMapShader
GLuint depthMap
bool initialized = false
Detailed Description
Definition at line 12 of file DirectionalLightShadowMap.h.
Constructor & Destructor Documentation
~DirectionalLightShadowMap()
DirectionalLightShadowMap::~DirectionalLightShadowMap ()
Definition at line 64 of file DirectionalLightShadowMap.cpp.
References DBG_LOG, depthMap, depthMapFBO, and initialized.
Member Function Documentation
getCurrentLightDirection()
glm::vec3 DirectionalLightShadowMap::getCurrentLightDirection () inline
Definition at line 32 of file DirectionalLightShadowMap.h.
References lightDirection.
getDepthMap()
GLint DirectionalLightShadowMap::getDepthMap () inline
Definition at line 17 of file DirectionalLightShadowMap.h.
References depthMap.
Referenced by RenderingSystem::render(), and RenderingSystem::supplyLitShaderUniforms().
getDepthMapHeight()
unsigned int DirectionalLightShadowMap::getDepthMapHeight () const inline
Definition at line 21 of file DirectionalLightShadowMap.h.
References DEPTH_MAP_HEIGHT.
Referenced by RenderingSystem::render().
getDepthMapShader()
GLint DirectionalLightShadowMap::getDepthMapShader () inline
Definition at line 16 of file DirectionalLightShadowMap.h.
References depthMapShader, and Shader::getProgramID().
getDepthMapWidth()
unsigned int DirectionalLightShadowMap::getDepthMapWidth () const inline
Definition at line 20 of file DirectionalLightShadowMap.h.
References DEPTH_MAP_WIDTH.
Referenced by RenderingSystem::render().
getFBO()
GLuint DirectionalLightShadowMap::getFBO () inline
Definition at line 18 of file DirectionalLightShadowMap.h.
References depthMapFBO.
Referenced by RenderingSystem::render().
getLightSpaceMatrix()
const glm::mat4* const DirectionalLightShadowMap::getLightSpaceMatrix () inline
Definition at line 15 of file DirectionalLightShadowMap.h.
References lightSpaceMatrix.
Referenced by RenderingSystem::supplyLitShaderUniforms().
initialize()
void DirectionalLightShadowMap::initialize ()
Definition at line 16 of file DirectionalLightShadowMap.cpp.
References depthMap, depthMapFBO, depthMapShader, Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), initialized, and updateDepthMapResolution().
isActive()
bool DirectionalLightShadowMap::isActive () inline
Definition at line 30 of file DirectionalLightShadowMap.h.
References lightSupplied.
Referenced by RenderingSystem::render().
setCurrentLightDirection()
void DirectionalLightShadowMap::setCurrentLightDirection (const glm::vec3 & lightDir) inline
Definition at line 33 of file DirectionalLightShadowMap.h.
References lightDirection, and securityAdditiveForDirection.
Referenced by FixedUpdatingSystem::updateShadowMaps().
setDepthMapResolution()
void DirectionalLightShadowMap::setDepthMapResolution (const unsigned int & width, const unsigned int & height) inline
Definition at line 23 of file DirectionalLightShadowMap.h.
References DEPTH_MAP_HEIGHT, DEPTH_MAP_WIDTH, and updateDepthMapResolution().
setShadowActive()
void DirectionalLightShadowMap::setShadowActive (bool t) inline
Definition at line 29 of file DirectionalLightShadowMap.h.
References lightSupplied.
Referenced by FixedUpdatingSystem::updateShadowMaps().
updateDepthMap()
void DirectionalLightShadowMap::updateDepthMap (const Camera & camera)
Definition at line 3 of file DirectionalLightShadowMap.cpp.
References DirectionalLightShadowMap::OrthographicBounds::bottom, bounds, depthMapShader, Shader::getProgramID(), Camera::getTargetPosition(), Shaders::getUniformLocation(), DirectionalLightShadowMap::OrthographicBounds::left, lightDirection, Shaders::LightSpaceMatrix, lightSpaceMatrix, DirectionalLightShadowMap::OrthographicBounds::right, DirectionalLightShadowMap::OrthographicBounds::top, hh::UP_VECTOR, Shader::useProgram(), DirectionalLightShadowMap::OrthographicBounds::zFar, and DirectionalLightShadowMap::OrthographicBounds::zNear.
Referenced by FixedUpdatingSystem::updateShadowMaps().
updateDepthMapResolution()
void DirectionalLightShadowMap::updateDepthMapResolution () private
Definition at line 45 of file DirectionalLightShadowMap.cpp.
References DBG_LOG, DEPTH_MAP_HEIGHT, DEPTH_MAP_WIDTH, and depthMap.
Referenced by initialize(), and setDepthMapResolution().
Member Data Documentation
bounds
OrthographicBounds DirectionalLightShadowMap::bounds { -40.0f, 40.0f, -40.0f, 40.0f, -150.0f, 150.0f } private
Definition at line 60 of file DirectionalLightShadowMap.h.
Referenced by updateDepthMap().
DEPTH_MAP_HEIGHT
unsigned int DirectionalLightShadowMap::DEPTH_MAP_HEIGHT = 4096 private
Definition at line 43 of file DirectionalLightShadowMap.h.
Referenced by getDepthMapHeight(), setDepthMapResolution(), and updateDepthMapResolution().
DEPTH_MAP_WIDTH
unsigned int DirectionalLightShadowMap::DEPTH_MAP_WIDTH = 4096 private
Definition at line 42 of file DirectionalLightShadowMap.h.
Referenced by getDepthMapWidth(), setDepthMapResolution(), and updateDepthMapResolution().
depthMap
GLuint DirectionalLightShadowMap::depthMap private
Definition at line 69 of file DirectionalLightShadowMap.h.
Referenced by getDepthMap(), initialize(), updateDepthMapResolution(), and ~DirectionalLightShadowMap().
depthMapFBO
GLuint DirectionalLightShadowMap::depthMapFBO private
Definition at line 67 of file DirectionalLightShadowMap.h.
Referenced by getFBO(), initialize(), and ~DirectionalLightShadowMap().
depthMapShader
Shader DirectionalLightShadowMap::depthMapShader private
Definition at line 68 of file DirectionalLightShadowMap.h.
Referenced by getDepthMapShader(), initialize(), and updateDepthMap().
initialized
bool DirectionalLightShadowMap::initialized = false private
Definition at line 70 of file DirectionalLightShadowMap.h.
Referenced by initialize(), and ~DirectionalLightShadowMap().
lightDirection
glm::vec3 DirectionalLightShadowMap::lightDirection = glm::vec3(0.0001f, -1.f, 0) private
Definition at line 62 of file DirectionalLightShadowMap.h.
Referenced by getCurrentLightDirection(), setCurrentLightDirection(), and updateDepthMap().
lightSpaceMatrix
glm::mat4 DirectionalLightShadowMap::lightSpaceMatrix private
Definition at line 66 of file DirectionalLightShadowMap.h.
Referenced by getLightSpaceMatrix(), and updateDepthMap().
lightSupplied
bool DirectionalLightShadowMap::lightSupplied = false private
Definition at line 64 of file DirectionalLightShadowMap.h.
Referenced by isActive(), and setShadowActive().
securityAdditiveForDirection
const float DirectionalLightShadowMap::securityAdditiveForDirection = .0001f private
Definition at line 47 of file DirectionalLightShadowMap.h.
Referenced by setCurrentLightDirection().
The documentation for this class was generated from the following files:
src/DirectionalLightShadowMap.h
src/DirectionalLightShadowMap.cpp