LightShow_Boilerplate: DirectionalLight Struct Reference
DirectionalLight Struct Reference
#include <Lights.h>
Public Attributes
glm::vec3 direction = glm::vec3(0, -1, 0)
glm::vec3 ambient = glm::vec3(.05f, 0.05f, 0.05f)
glm::vec3 diffuse = glm::vec3(.4f, 0.4f, 0.4f)
glm::vec3 specular = glm::vec3(.6f, .54f, .5f)
Additional Inherited Members
Public Member Functions inherited from Component< DirectionalLight >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Static Public Attributes inherited from Component< DirectionalLight >
static int32_t type
Detailed Description
Definition at line 16 of file Lights.h.
Member Data Documentation
ambient
glm::vec3 DirectionalLight::ambient = glm::vec3(.05f, 0.05f, 0.05f)
Definition at line 18 of file Lights.h.
Referenced by LightTest::initialize(), and Shader::setDirectionalLight().
diffuse
glm::vec3 DirectionalLight::diffuse = glm::vec3(.4f, 0.4f, 0.4f)
Definition at line 19 of file Lights.h.
Referenced by DayNightCycleSystem::fixedUpdate(), LightTest::initialize(), and Shader::setDirectionalLight().
direction
glm::vec3 DirectionalLight::direction = glm::vec3(0, -1, 0)
Definition at line 17 of file Lights.h.
Referenced by DayNightCycleSystem::fixedUpdate(), LightTest::initialize(), and Shader::setDirectionalLight().
specular
glm::vec3 DirectionalLight::specular = glm::vec3(.6f, .54f, .5f)
Definition at line 20 of file Lights.h.
Referenced by LightTest::initialize(), and Shader::setDirectionalLight().
The documentation for this struct was generated from the following file:
src/Lights.h