LightShow_Boilerplate: TextureHandler Class Reference
TextureHandler Class Reference
#include <Texture.h>
Public Member Functions
Texture & getTexture (std::string filePath, GLint filtering=GL_LINEAR, bool repeatTexture=false)
CubeMap & getCubeMap (const std::string identifier, const std::vector< std::string > &faces)
~TextureHandler ()
Private Member Functions
Texture parseTexture (std::string filePath, GLint filtering, bool repeatTexture)
void verifySurfaceDimensions (const SDL_Surface &surface)
GLenum getSurfaceFormat (const SDL_Surface &surface)
void teximage2DFillerTexture (GLenum target)
Texture & addNewTexture (std::string filePath, GLint filtering, bool repeatTexture)
Texture * binarySearchTextures (const std::string &key)
Private Attributes
const GLubyte fillerTexturePixels [27]
std::vector< Texture * > textureLibrary
std::map< std::string, CubeMap * > cubeMapLibrary
Detailed Description
Definition at line 51 of file Texture.h.
Constructor & Destructor Documentation
~TextureHandler()
TextureHandler::~TextureHandler ()
Definition at line 280 of file Texture.cpp.
References cubeMapLibrary, DBG_LOG, and textureLibrary.
Member Function Documentation
addNewTexture()
Texture & TextureHandler::addNewTexture (std::string filePath, GLint filtering, bool repeatTexture) private
Definition at line 160 of file Texture.cpp.
References parseTexture(), and textureLibrary.
Referenced by getTexture().
binarySearchTextures()
Texture * TextureHandler::binarySearchTextures (const std::string & key) private
Definition at line 176 of file Texture.cpp.
References textureLibrary.
Referenced by getTexture().
getCubeMap()
CubeMap & TextureHandler::getCubeMap (const std::string identifier, const std::vector< std::string > & faces)
Definition at line 209 of file Texture.cpp.
References cubeMapLibrary, DBG_LOG, getSurfaceFormat(), teximage2DFillerTexture(), and verifySurfaceDimensions().
Referenced by LightTest::initialize().
getSurfaceFormat()
GLenum TextureHandler::getSurfaceFormat (const SDL_Surface & surface) private
Definition at line 121 of file Texture.cpp.
References DBG_LOG.
Referenced by getCubeMap(), and parseTexture().
getTexture()
Texture & TextureHandler::getTexture (std::string filePath, GLint filtering = GL_LINEAR, bool repeatTexture = false)
Definition at line 197 of file Texture.cpp.
References addNewTexture(), and binarySearchTextures().
Referenced by Player::initialize(), _3DM::Model::initializeTexture(), and _3DM::AnimatedModel::initializeTexture().
parseTexture()
Texture TextureHandler::parseTexture (std::string filePath, GLint filtering, bool repeatTexture) private
Definition at line 25 of file Texture.cpp.
References DBG_LOG, getSurfaceFormat(), teximage2DFillerTexture(), and verifySurfaceDimensions().
Referenced by addNewTexture().
teximage2DFillerTexture()
void TextureHandler::teximage2DFillerTexture (GLenum target) private
Definition at line 150 of file Texture.cpp.
References fillerTexturePixels.
Referenced by getCubeMap(), and parseTexture().
verifySurfaceDimensions()
void TextureHandler::verifySurfaceDimensions (const SDL_Surface & surface) private
Definition at line 93 of file Texture.cpp.
References DBG_LOG, and hh::isPowerOfTwo().
Referenced by getCubeMap(), and parseTexture().
Member Data Documentation
cubeMapLibrary
std::map<std::string, CubeMap*> TextureHandler::cubeMapLibrary private
Definition at line 93 of file Texture.h.
Referenced by getCubeMap(), and ~TextureHandler().
fillerTexturePixels
const GLubyte TextureHandler::fillerTexturePixels[27] private
Initial value:
= { 0, 0, 0, 255, 255, 255, 0, 0, 0,
                                              255, 255, 255, 0, 0, 0, 255, 255, 255,
                                              0, 0, 0, 255, 255, 255, 0, 0, 0 }
Definition at line 83 of file Texture.h.
Referenced by teximage2DFillerTexture().
textureLibrary
std::vector<Texture*> TextureHandler::textureLibrary private
Definition at line 90 of file Texture.h.
Referenced by addNewTexture(), binarySearchTextures(), and ~TextureHandler().
The documentation for this class was generated from the following files:
src/Texture.h
src/Texture.cpp