LightShow_Boilerplate: PlayerTestObject Class Reference
PlayerTestObject Class Reference
#include <EntityTests.h>
Public Member Functions
~PlayerTestObject ()
void initialize (EntityWrapper::EntityVitals &vitals)
Public Member Functions inherited from EntityWrapper
virtual ~EntityWrapper ()
Private Attributes
_3DM::AnimatedModel model = _3DM::AnimatedModel("assets/Models/player/testplayer.3DMA")
Shader textShader
PlayerCameraHandler cameraHandler
CollisionMesh collisionMesh
PlayerController testController = PlayerController(glm::vec3(0, .5f, 0))
SimpleMaterial material
Shader shader
BoneCollisionMesh bCollisionMesh
Detailed Description
Definition at line 82 of file EntityTests.h.
Constructor & Destructor Documentation
~PlayerTestObject()
PlayerTestObject::~PlayerTestObject () inline
Definition at line 85 of file EntityTests.h.
Member Function Documentation
initialize()
void PlayerTestObject::initialize (EntityWrapper::EntityVitals & vitals) virtual
Implements EntityWrapper.
Definition at line 53 of file EntityTests.cpp.
References Scene::addComponent(), _3DM::AnimatedModel::amountOfMeshes(), bCollisionMesh, cameraHandler, EntityWrapper::EntityVitals::checkForNulls(), collisionMesh, EntityWrapper::EntityVitals::currentSettings, DBG_LOG, Scene::generateEntity(), CollisionMesh::getRigidBody(), Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), CollisionMesh::initialize(), material, model, EntityWrapper::EntityVitals::scene, _3DM::AnimatedModel::setAnimationClip(), _3DM::AnimatedModel::setMeshMatrix(), shader, SimpleMaterial::shininess, testController, and textShader.
Member Data Documentation
bCollisionMesh
BoneCollisionMesh PlayerTestObject::bCollisionMesh private
Definition at line 98 of file EntityTests.h.
Referenced by initialize().
cameraHandler
PlayerCameraHandler PlayerTestObject::cameraHandler private
Definition at line 93 of file EntityTests.h.
Referenced by initialize().
collisionMesh
CollisionMesh PlayerTestObject::collisionMesh private
Definition at line 94 of file EntityTests.h.
Referenced by initialize().
material
SimpleMaterial PlayerTestObject::material private
Definition at line 96 of file EntityTests.h.
Referenced by initialize().
model
_3DM::AnimatedModel PlayerTestObject::model = _3DM::AnimatedModel("assets/Models/player/testplayer.3DMA") private
Definition at line 89 of file EntityTests.h.
Referenced by initialize().
shader
Shader PlayerTestObject::shader private
Definition at line 97 of file EntityTests.h.
Referenced by initialize().
testController
PlayerController PlayerTestObject::testController = PlayerController(glm::vec3(0, .5f, 0)) private
Definition at line 95 of file EntityTests.h.
Referenced by initialize().
textShader
Shader PlayerTestObject::textShader private
Definition at line 91 of file EntityTests.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/EntityTests.h
src/EntityTests.cpp