LightShow_Boilerplate: CollisionMesh Class Reference
CollisionMesh Class Reference
#include <CollisionMesh.h>
Public Member Functions
template<typename T >
void initialize (const btTransform &transformation, const T &shape, float mass, const CollisionTag usrTag=CollisionTag(), bool trigger=false, btVector3 localInertia=btVector3(0, 0, 0), float friction=0, float restitution=0, bool kinematic=false)
const CollisionTag *const getTag ()
void setUserTag (const CollisionTag &tag)
void initializeMeshShape (const btTransform &transformation, _3DM::Model &model, unsigned int meshIndex, float mass, CollisionTag usrTag=CollisionTag(), bool trigger=false, btVector3 localInertia=btVector3(0, 0, 0), float friction=0, float restitution=0, bool kinematic=false)
void initializeModelShape (const btTransform &transformation, _3DM::Model &model, float mass, CollisionTag usrTag=CollisionTag(), bool trigger=false, btVector3 localInertia=btVector3(0, 0, 0), float friction=0, float restitution=0, bool kinematic=false)
void initializeMeshShape (const btTransform &transformation, _3DM::AnimatedModel &model, unsigned int meshIndex, float mass, CollisionTag usrTag=CollisionTag(), bool trigger=false, btVector3 localInertia=btVector3(0, 0, 0), float friction=0, float restitution=0, bool kinematic=false)
void initializeModelShape (const btTransform &transformation, _3DM::AnimatedModel &model, float mass, CollisionTag usrTag=CollisionTag(), bool trigger=false, btVector3 localInertia=btVector3(0, 0, 0), float friction=0, float restitution=0, bool kinematic=false)
void setTrigger (bool t)
Transform getTransformation ()
~CollisionMesh ()
btDefaultMotionState *const getMotionState () const
btCollisionShape *const getShape () const
btRigidBody *const getRigidBody () const
void setScale (const glm::vec3 &scale)
glm::vec3 getScale ()
glm::vec3 getPosition ()
glm::quat getRotation ()
void translate (const glm::vec3 &addition)
void translate (const btVector3 &addition)
void addVelocity (const btVector3 &v)
void addVelocity (const glm::vec3 &v)
void setVelocity (const btVector3 &v)
void setVelocity (const glm::vec3 &v)
glm::vec3 getVelocity ()
btVector3 getVelocitybt () const
void applyCentralImpulse (const glm::vec3 &impulse)
void applyCentralImpulse (const btVector3 &impulse)
void activateRigidBody (bool t)
bool isKinematic () const
bool isTrigger () const
Public Member Functions inherited from Component< CollisionMesh >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Types
typedef btRigidBody::btRigidBodyConstructionInfo btCI
Private Member Functions
void deInit ()
void setKinematic (bool t)
btTriangleMesh * createTriangleMeshCollider (_3DM::AnimatedModel *model, unsigned int meshIndex)
btTriangleMesh * createTriangleModelCollider (_3DM::AnimatedModel *model)
btTriangleMesh * createTriangleMeshCollider (_3DM::Model *model, unsigned int meshIndex)
btTriangleMesh * createTriangleModelCollider (_3DM::Model *model)
Private Attributes
bool isKinematicBody = false
bool isTriggerBody = false
bool isMesh = false
bool hasInit = false
CollisionTag thisTag
btRigidBody * rigidBody
btCollisionShape * thisShape
btDefaultMotionState * thisMotionState
btTriangleMesh * thisMesh
Additional Inherited Members
Static Public Attributes inherited from Component< CollisionMesh >
static int32_t type
Detailed Description
Definition at line 11 of file CollisionMesh.h.
Member Typedef Documentation
btCI
typedef btRigidBody::btRigidBodyConstructionInfo CollisionMesh::btCI private
Definition at line 207 of file CollisionMesh.h.
Constructor & Destructor Documentation
~CollisionMesh()
CollisionMesh::~CollisionMesh ()
Definition at line 245 of file CollisionMesh.cpp.
References deInit().
Member Function Documentation
activateRigidBody()
void CollisionMesh::activateRigidBody (bool t) inline
Definition at line 191 of file CollisionMesh.h.
References DBG_CHECK, and rigidBody.
Referenced by PlayerControllerSystem::fixedUpdate(), and EnemyControllerSystem::update().
addVelocity() [1/2]
void CollisionMesh::addVelocity (const btVector3 & v) inline
Definition at line 145 of file CollisionMesh.h.
References DBG_CHECK, and rigidBody.
Referenced by PlayerControllerSystem::applyForces(), and PlayerControllerSystem::getPlayerInput().
addVelocity() [2/2]
void CollisionMesh::addVelocity (const glm::vec3 & v) inline
Definition at line 155 of file CollisionMesh.h.
References DBG_CHECK, and rigidBody.
applyCentralImpulse() [1/2]
void CollisionMesh::applyCentralImpulse (const btVector3 & impulse) inline
Definition at line 187 of file CollisionMesh.h.
References DBG_CHECK, and rigidBody.
applyCentralImpulse() [2/2]
void CollisionMesh::applyCentralImpulse (const glm::vec3 & impulse) inline
Definition at line 183 of file CollisionMesh.h.
References DBG_CHECK, rigidBody, and hh::toBtVec3().
Referenced by EnemyControllerSystem::applyForces(), PlayerControllerSystem::applyForces(), and PlayerControllerSystem::performJump().
createTriangleMeshCollider() [1/2]
btTriangleMesh * CollisionMesh::createTriangleMeshCollider (_3DM::AnimatedModel * model, unsigned int meshIndex) private
Definition at line 250 of file CollisionMesh.cpp.
References _3DM::AnimatedModel::amountOfMeshes(), _3DM::AnimatedModel::getMeshIndices(), and _3DM::AnimatedModel::getMeshVertices().
Referenced by initializeMeshShape().
createTriangleMeshCollider() [2/2]
btTriangleMesh * CollisionMesh::createTriangleMeshCollider (_3DM::Model * model, unsigned int meshIndex) private
Definition at line 311 of file CollisionMesh.cpp.
References _3DM::Model::amountOfMeshes(), _3DM::Model::getMeshIndices(), and _3DM::Model::getMeshVertices().
createTriangleModelCollider() [1/2]
btTriangleMesh * CollisionMesh::createTriangleModelCollider (_3DM::AnimatedModel * model) private
Definition at line 279 of file CollisionMesh.cpp.
References _3DM::AnimatedModel::amountOfMeshes(), DBG_LOG, _3DM::AnimatedModel::getMeshIndices(), and _3DM::AnimatedModel::getMeshVertices().
Referenced by initializeModelShape().
createTriangleModelCollider() [2/2]
btTriangleMesh * CollisionMesh::createTriangleModelCollider (_3DM::Model * model) private
Definition at line 341 of file CollisionMesh.cpp.
References _3DM::Model::amountOfMeshes(), DBG_LOG, _3DM::Model::getMeshIndices(), and _3DM::Model::getMeshVertices().
deInit()
void CollisionMesh::deInit () private
Definition at line 205 of file CollisionMesh.cpp.
References DBG_CHECK, hasInit, isMesh, rigidBody, thisMesh, thisMotionState, and thisShape.
Referenced by initialize(), initializeMeshShape(), initializeModelShape(), and ~CollisionMesh().
getMotionState()
btDefaultMotionState* const CollisionMesh::getMotionState () const inline
Definition at line 116 of file CollisionMesh.h.
References thisMotionState.
Referenced by BoneCollisionMeshSystem::fixedUpdate().
getPosition()
glm::vec3 CollisionMesh::getPosition () inline
Definition at line 129 of file CollisionMesh.h.
References DBG_CHECK, rigidBody, and hh::toGlmVec3().
Referenced by EnemyControllerSystem::applyNewTransform(), PlayerControllerSystem::applyNewTransform(), PlayerControllerSystem::getPlayerInput(), and PlayerControllerSystem::handleRayHit().
getRigidBody()
btRigidBody* const CollisionMesh::getRigidBody () const inline
Definition at line 118 of file CollisionMesh.h.
References rigidBody.
Referenced by PhysicsWorld::addRigidBody(), PlayerTestObject::initialize(), EnemyTestObject::initialize(), and PhysicsWorld::removeRigidBody().
getRotation()
glm::quat CollisionMesh::getRotation () inline
Definition at line 133 of file CollisionMesh.h.
References DBG_CHECK, rigidBody, and hh::toGlmQuat().
getScale()
glm::vec3 CollisionMesh::getScale () inline
Definition at line 125 of file CollisionMesh.h.
References DBG_CHECK, thisShape, and hh::toGlmVec3().
getShape()
btCollisionShape* const CollisionMesh::getShape () const inline
Definition at line 117 of file CollisionMesh.h.
References thisShape.
Referenced by FloorObject::initialize().
getTag()
const CollisionTag* const CollisionMesh::getTag () inline
Definition at line 55 of file CollisionMesh.h.
References rigidBody.
getTransformation()
Transform CollisionMesh::getTransformation ()
Definition at line 237 of file CollisionMesh.cpp.
References DBG_CHECK, rigidBody, thisShape, hh::toGlmQuat(), and hh::toGlmVec3().
Referenced by PlayerControllerSystem::fixedUpdate(), EnemyControllerSystem::update(), and FixedUpdatingSystem::updateCollision().
getVelocity()
glm::vec3 CollisionMesh::getVelocity () inline
Definition at line 175 of file CollisionMesh.h.
References DBG_CHECK, rigidBody, and hh::toGlmVec3().
getVelocitybt()
btVector3 CollisionMesh::getVelocitybt () const inline
Definition at line 179 of file CollisionMesh.h.
References DBG_CHECK, and rigidBody.
Referenced by PlayerControllerSystem::applyForces(), PlayerControllerSystem::executeRayTesting(), EnemyControllerSystem::executeRayTesting(), PlayerControllerSystem::handleRayHit(), and EnemyControllerSystem::handleRayHit().
initialize()
template<typename T > void CollisionMesh::initialize (const btTransform & transformation, const T & shape, float mass, const CollisionTag usrTag = CollisionTag(), bool trigger = false, btVector3 localInertia = btVector3(0, 0, 0), float friction = 0, float restitution = 0, bool kinematic = false) inline
Definition at line 16 of file CollisionMesh.h.
References DBG_LOG, deInit(), hasInit, rigidBody, setKinematic(), setTrigger(), thisMotionState, thisShape, and thisTag.
Referenced by PlayerTestObject::initialize(), EnemyTestObject::initialize(), and CubeTrigger::initialize().
initializeMeshShape() [1/2]
void CollisionMesh::initializeMeshShape (const btTransform & transformation, _3DM::AnimatedModel & model, unsigned int meshIndex, float mass, CollisionTag usrTag = CollisionTag(), bool trigger = false, btVector3 localInertia = btVector3(0, 0, 0), float friction = 0, float restitution = 0, bool kinematic = false)
Definition at line 107 of file CollisionMesh.cpp.
References createTriangleMeshCollider(), DBG_LOG, deInit(), hasInit, isMesh, rigidBody, setKinematic(), setTrigger(), thisMesh, thisMotionState, thisShape, and thisTag.
initializeMeshShape() [2/2]
void CollisionMesh::initializeMeshShape (const btTransform & transformation, _3DM::Model & model, unsigned int meshIndex, float mass, CollisionTag usrTag = CollisionTag(), bool trigger = false, btVector3 localInertia = btVector3(0, 0, 0), float friction = 0, float restitution = 0, bool kinematic = false)
Definition at line 3 of file CollisionMesh.cpp.
References createTriangleMeshCollider(), DBG_LOG, deInit(), hasInit, isMesh, rigidBody, setKinematic(), setTrigger(), thisMesh, thisMotionState, thisShape, and thisTag.
initializeModelShape() [1/2]
void CollisionMesh::initializeModelShape (const btTransform & transformation, _3DM::AnimatedModel & model, float mass, CollisionTag usrTag = CollisionTag(), bool trigger = false, btVector3 localInertia = btVector3(0, 0, 0), float friction = 0, float restitution = 0, bool kinematic = false)
Definition at line 149 of file CollisionMesh.cpp.
References createTriangleModelCollider(), DBG_LOG, deInit(), hasInit, isMesh, rigidBody, setKinematic(), setTrigger(), thisMesh, thisMotionState, thisShape, and thisTag.
initializeModelShape() [2/2]
void CollisionMesh::initializeModelShape (const btTransform & transformation, _3DM::Model & model, float mass, CollisionTag usrTag = CollisionTag(), bool trigger = false, btVector3 localInertia = btVector3(0, 0, 0), float friction = 0, float restitution = 0, bool kinematic = false)
Definition at line 55 of file CollisionMesh.cpp.
References createTriangleModelCollider(), DBG_LOG, deInit(), hasInit, isMesh, rigidBody, setKinematic(), setTrigger(), thisMesh, thisMotionState, thisShape, and thisTag.
Referenced by FloorObject::initialize().
isKinematic()
bool CollisionMesh::isKinematic () const inline
Definition at line 196 of file CollisionMesh.h.
References isKinematicBody.
Referenced by PhysicsWorld::addRigidBody().
isTrigger()
bool CollisionMesh::isTrigger () const inline
Definition at line 197 of file CollisionMesh.h.
References isTriggerBody.
Referenced by PhysicsWorld::addRigidBody().
setKinematic()
void CollisionMesh::setKinematic (bool t) private
Definition at line 226 of file CollisionMesh.cpp.
References DBG_CHECK, isKinematicBody, and rigidBody.
Referenced by initialize(), initializeMeshShape(), and initializeModelShape().
setScale()
void CollisionMesh::setScale (const glm::vec3 & scale) inline
Definition at line 120 of file CollisionMesh.h.
References DBG_CHECK, thisShape, and hh::toBtVec3().
setTrigger()
void CollisionMesh::setTrigger (bool t)
Definition at line 191 of file CollisionMesh.cpp.
References DBG_CHECK, isTriggerBody, and rigidBody.
Referenced by initialize(), initializeMeshShape(), and initializeModelShape().
setUserTag()
void CollisionMesh::setUserTag (const CollisionTag & tag) inline
Definition at line 59 of file CollisionMesh.h.
References rigidBody, and thisTag.
setVelocity() [1/2]
void CollisionMesh::setVelocity (const btVector3 & v) inline
Definition at line 165 of file CollisionMesh.h.
References DBG_CHECK, and rigidBody.
Referenced by EnemyControllerSystem::executeRayTesting(), PlayerControllerSystem::executeRayTesting(), PlayerControllerSystem::handleRayHit(), and EnemyControllerSystem::handleRayHit().
setVelocity() [2/2]
void CollisionMesh::setVelocity (const glm::vec3 & v) inline
Definition at line 170 of file CollisionMesh.h.
References DBG_CHECK, rigidBody, and hh::toBtVec3().
translate() [1/2]
void CollisionMesh::translate (const btVector3 & addition) inline
Definition at line 141 of file CollisionMesh.h.
References rigidBody.
translate() [2/2]
void CollisionMesh::translate (const glm::vec3 & addition) inline
Definition at line 138 of file CollisionMesh.h.
References rigidBody, and hh::toBtVec3().
Referenced by EnemyControllerSystem::handleRayHit(), and PlayerControllerSystem::handleRayHit().
Member Data Documentation
hasInit
bool CollisionMesh::hasInit = false private
Definition at line 210 of file CollisionMesh.h.
Referenced by deInit(), initialize(), initializeMeshShape(), and initializeModelShape().
isKinematicBody
bool CollisionMesh::isKinematicBody = false private
Definition at line 202 of file CollisionMesh.h.
Referenced by isKinematic(), and setKinematic().
isMesh
bool CollisionMesh::isMesh = false private
Definition at line 209 of file CollisionMesh.h.
Referenced by deInit(), initializeMeshShape(), and initializeModelShape().
isTriggerBody
bool CollisionMesh::isTriggerBody = false private
Definition at line 203 of file CollisionMesh.h.
Referenced by isTrigger(), and setTrigger().
rigidBody
btRigidBody* CollisionMesh::rigidBody private
Definition at line 214 of file CollisionMesh.h.
Referenced by activateRigidBody(), addVelocity(), applyCentralImpulse(), deInit(), getPosition(), getRigidBody(), getRotation(), getTag(), getTransformation(), getVelocity(), getVelocitybt(), initialize(), initializeMeshShape(), initializeModelShape(), setKinematic(), setTrigger(), setUserTag(), setVelocity(), and translate().
thisMesh
btTriangleMesh* CollisionMesh::thisMesh private
Definition at line 217 of file CollisionMesh.h.
Referenced by deInit(), initializeMeshShape(), and initializeModelShape().
thisMotionState
btDefaultMotionState* CollisionMesh::thisMotionState private
Definition at line 216 of file CollisionMesh.h.
Referenced by deInit(), getMotionState(), initialize(), initializeMeshShape(), and initializeModelShape().
thisShape
btCollisionShape* CollisionMesh::thisShape private
Definition at line 215 of file CollisionMesh.h.
Referenced by deInit(), getScale(), getShape(), getTransformation(), initialize(), initializeMeshShape(), initializeModelShape(), and setScale().
thisTag
CollisionTag CollisionMesh::thisTag private
Definition at line 212 of file CollisionMesh.h.
Referenced by initialize(), initializeMeshShape(), initializeModelShape(), and setUserTag().
The documentation for this class was generated from the following files:
src/CollisionMesh.h
src/CollisionMesh.cpp