LightShow_Boilerplate: Particles Class Reference
Particles Class Reference
#include <Particles.h>
Public Member Functions
Particles ()
Particles (unsigned int size)
void initialize (const Settings &worldSettings)
~Particles ()
bool areVitalsNull ()
unsigned int getParticlesPerSecond ()
const Texture *const getTexture ()
std::vector< Particle > *const getParticles ()
const PARTICLE_TYPE getParticleType ()
void setTexture (const Texture &pTexture)
void setWorldSettings (const Settings &worldSettings)
void setParticlesPerSecond (unsigned int pps)
void setWeight (float dfltWeight)
void setDefaultLifeTime (float dfltLifeTime)
void setDefaultStartScale (float scl)
void setDefaultColor (const glm::vec4 &color)
void setPosition (const glm::vec3 &position)
void setParticleType (PARTICLE_TYPE t)
Public Member Functions inherited from Component< Particles >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
PARTICLE_TYPE particleType = PARTICLE_TYPE::Default
const Texture * particleTexture = nullptr
std::vector< Particle > particles
const Settings * currentWorldSettings = nullptr
float defaultLifeTime = 1
float defaultWeight = 1
float defaultScale = .3f
glm::vec4 defaultColor = glm::vec4(1, 1, 1, 1)
glm::vec3 emmisionPosition = glm::vec3(0.0f, 0.0f, 0.0f)
unsigned int particlesPerSecond = 1
float newparticles = 0
int renderingSize = 0
GLuint vertexArrayObject = 0
GLuint bufferObject = 0
GLuint instanceBufferObject = 0
bool initialized = false
Friends
class DefaultParticleSystem
class FountainParticleSystem
Additional Inherited Members
Static Public Attributes inherited from Component< Particles >
static int32_t type
Detailed Description
Definition at line 34 of file Particles.h.
Constructor & Destructor Documentation
Particles() [1/2]
Particles::Particles () inline
Definition at line 36 of file Particles.h.
References particles.
Particles() [2/2]
Particles::Particles (unsigned int size) inline
Definition at line 41 of file Particles.h.
References particles.
~Particles()
Particles::~Particles ()
Definition at line 3 of file Particles.cpp.
References bufferObject, DBG_LOG, initialized, instanceBufferObject, and vertexArrayObject.
Member Function Documentation
areVitalsNull()
bool Particles::areVitalsNull ()
Definition at line 92 of file Particles.cpp.
References currentWorldSettings, DBG_LOG, and initialized.
Referenced by DefaultParticleSystem::renderParticles().
getParticles()
std::vector<Particle>* const Particles::getParticles () inline
Definition at line 53 of file Particles.h.
References particles.
getParticlesPerSecond()
unsigned int Particles::getParticlesPerSecond () inline
Definition at line 51 of file Particles.h.
References particlesPerSecond.
getParticleType()
const PARTICLE_TYPE Particles::getParticleType () inline
Definition at line 54 of file Particles.h.
References particleType.
Referenced by RenderingSystem::renderParticles().
getTexture()
const Texture* const Particles::getTexture () inline
Definition at line 52 of file Particles.h.
References particleTexture.
Referenced by DefaultParticleSystem::renderParticles().
initialize()
void Particles::initialize (const Settings & worldSettings)
Definition at line 16 of file Particles.cpp.
References bufferObject, Particle::color, currentWorldSettings, Shaders::getAttribLocation(), initialized, instanceBufferObject, Shaders::ParticleColor, Shaders::ParticlePosition, Shaders::ParticleScale, Particle::position, Shaders::Position, hh::quadVertices, Particle::size, Shaders::TextureCoordinates, and vertexArrayObject.
Referenced by ParticleTest::initialize().
setDefaultColor()
void Particles::setDefaultColor (const glm::vec4 & color) inline
Definition at line 65 of file Particles.h.
References defaultColor.
Referenced by ParticleTest::initialize().
setDefaultLifeTime()
void Particles::setDefaultLifeTime (float dfltLifeTime) inline
Definition at line 63 of file Particles.h.
References defaultLifeTime.
Referenced by ParticleTest::initialize().
setDefaultStartScale()
void Particles::setDefaultStartScale (float scl) inline
Definition at line 64 of file Particles.h.
References defaultScale.
Referenced by ParticleTest::initialize().
setParticlesPerSecond()
void Particles::setParticlesPerSecond (unsigned int pps) inline
Definition at line 61 of file Particles.h.
References particlesPerSecond.
Referenced by ParticleTest::initialize().
setParticleType()
void Particles::setParticleType (PARTICLE_TYPE t) inline
Definition at line 67 of file Particles.h.
References particleType.
Referenced by ParticleTest::initialize().
setPosition()
void Particles::setPosition (const glm::vec3 & position) inline
Definition at line 66 of file Particles.h.
References emmisionPosition.
Referenced by ParticleTest::initialize().
setTexture()
void Particles::setTexture (const Texture & pTexture) inline
Definition at line 56 of file Particles.h.
References particleTexture.
Referenced by ParticleTest::initialize().
setWeight()
void Particles::setWeight (float dfltWeight) inline
Definition at line 62 of file Particles.h.
References defaultWeight.
Referenced by ParticleTest::initialize().
setWorldSettings()
void Particles::setWorldSettings (const Settings & worldSettings) inline
Definition at line 58 of file Particles.h.
References currentWorldSettings.
Friends And Related Function Documentation
DefaultParticleSystem
friend class DefaultParticleSystem friend
Definition at line 93 of file Particles.h.
FountainParticleSystem
friend class FountainParticleSystem friend
Definition at line 94 of file Particles.h.
Member Data Documentation
bufferObject
GLuint Particles::bufferObject = 0 private
Definition at line 88 of file Particles.h.
Referenced by initialize(), and ~Particles().
currentWorldSettings
const Settings* Particles::currentWorldSettings = nullptr private
Definition at line 74 of file Particles.h.
Referenced by areVitalsNull(), initialize(), FountainParticleSystem::performParticleCalculations(), and setWorldSettings().
defaultColor
glm::vec4 Particles::defaultColor = glm::vec4(1, 1, 1, 1) private
Definition at line 80 of file Particles.h.
Referenced by FountainParticleSystem::performParticleCalculations(), setDefaultColor(), DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
defaultLifeTime
float Particles::defaultLifeTime = 1 private
Definition at line 76 of file Particles.h.
Referenced by FountainParticleSystem::performParticleCalculations(), setDefaultLifeTime(), DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
defaultScale
float Particles::defaultScale = .3f private
Definition at line 78 of file Particles.h.
Referenced by setDefaultStartScale(), DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
defaultWeight
float Particles::defaultWeight = 1 private
Definition at line 77 of file Particles.h.
Referenced by setWeight().
emmisionPosition
glm::vec3 Particles::emmisionPosition = glm::vec3(0.0f, 0.0f, 0.0f) private
Definition at line 81 of file Particles.h.
Referenced by DefaultParticleSystem::setParticleToDefault(), FountainParticleSystem::setParticleToDefault(), and setPosition().
initialized
bool Particles::initialized = false private
Definition at line 91 of file Particles.h.
Referenced by areVitalsNull(), initialize(), and ~Particles().
instanceBufferObject
GLuint Particles::instanceBufferObject = 0 private
Definition at line 89 of file Particles.h.
Referenced by initialize(), DefaultParticleSystem::renderParticles(), and ~Particles().
newparticles
float Particles::newparticles = 0 private
Definition at line 84 of file Particles.h.
Referenced by DefaultParticleSystem::fixedUpdateParticles().
particles
std::vector<Particle> Particles::particles private
Definition at line 72 of file Particles.h.
Referenced by DefaultParticleSystem::fixedUpdateParticles(), getParticles(), Particles(), DefaultParticleSystem::renderParticles(), and DefaultParticleSystem::updateParticles().
particlesPerSecond
unsigned int Particles::particlesPerSecond = 1 private
Definition at line 83 of file Particles.h.
Referenced by DefaultParticleSystem::fixedUpdateParticles(), getParticlesPerSecond(), and setParticlesPerSecond().
particleTexture
const Texture* Particles::particleTexture = nullptr private
Definition at line 71 of file Particles.h.
Referenced by getTexture(), and setTexture().
particleType
PARTICLE_TYPE Particles::particleType = PARTICLE_TYPE::Default private
Definition at line 70 of file Particles.h.
Referenced by getParticleType(), and setParticleType().
renderingSize
int Particles::renderingSize = 0 private
Definition at line 85 of file Particles.h.
Referenced by DefaultParticleSystem::fixedUpdateParticles(), DefaultParticleSystem::renderParticles(), and DefaultParticleSystem::updateParticles().
vertexArrayObject
GLuint Particles::vertexArrayObject = 0 private
Definition at line 87 of file Particles.h.
Referenced by initialize(), DefaultParticleSystem::renderParticles(), and ~Particles().
The documentation for this class was generated from the following files:
src/Particles.h
src/Particles.cpp