LightShow_Boilerplate: Player Class Reference
Player Class Reference
Test entity class The Player contains all of the necessary ui and controls to move and view the PlayerTestObject entity.
#include <EntityTests.h>
Public Member Functions
~Player ()
void initialize (EntityVitals &vitals)
Public Member Functions inherited from EntityWrapper
virtual ~EntityWrapper ()
Private Attributes
DisplayStatistics statDisplayer
Shader textShader
PauseMenu menu
DirectionalShadowDebugger dirShadowDbgr
Camera camera
UserControls userControls
Detailed Description
Test entity class The Player contains all of the necessary ui and controls to move and view the PlayerTestObject entity.
Definition at line 80 of file EntityTests.h.
Constructor & Destructor Documentation
~Player()
Player::~Player () inline
Definition at line 83 of file EntityTests.h.
Member Function Documentation
initialize()
void Player::initialize (EntityVitals & vitals) virtual
Implements EntityWrapper.
Definition at line 31 of file EntityTests.cpp.
References Scene::addComponent(), camera, EntityVitals::checkForNulls(), EntityVitals::currentSettings, DBG_LOG, dirShadowDbgr, Scene::generateEntity(), Locator< ShaderHandler, ShaderHandler >::getService(), Locator< TextureHandler, TextureHandler >::getService(), ShaderHandler::getShader(), TextureHandler::getTexture(), DirectionalShadowDebugger::initialize(), DisplayStatistics::initialize(), PauseMenu::initialize(), EntityVitals::map, menu, EntityVitals::scene, statDisplayer, textShader, and userControls.
Member Data Documentation
camera
Camera Player::camera private
Definition at line 91 of file EntityTests.h.
Referenced by initialize().
dirShadowDbgr
DirectionalShadowDebugger Player::dirShadowDbgr private
Definition at line 90 of file EntityTests.h.
Referenced by initialize().
menu
PauseMenu Player::menu private
Definition at line 89 of file EntityTests.h.
Referenced by initialize().
statDisplayer
DisplayStatistics Player::statDisplayer private
Definition at line 87 of file EntityTests.h.
Referenced by initialize().
textShader
Shader Player::textShader private
Definition at line 88 of file EntityTests.h.
Referenced by initialize().
userControls
UserControls Player::userControls private
Definition at line 92 of file EntityTests.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/game/entities/EntityTests.h
src/game/entities/EntityTests.cpp