LightShow_Boilerplate: GuiSprite Class Reference
GuiSprite Class Reference
#include <GuiSprite.h>
Public Member Functions
GuiSprite ()
GuiSprite (Texture &txtre)
void initialize (Texture &txtre)
void setSprite (float spriteXlocPXL, float spriteYlocPXL, float spriteWPXL, float spriteHPXL)
void setScale (float widthInPixels, float heightInPixels)
void setScale (const glm::vec2 &scaleInPixels)
void setPosition (float x, float y)
void setPosition (const glm::vec2 &pos)
void render (Shader &shader)
Protected Attributes
glm::vec2 position = glm::vec2(0.0f, 0.0f)
glm::vec2 scale = glm::vec2(0.0f, 0.0f)
float spriteXStart = 0
float spriteYStart = 0
float spriteWidth = 0
float spriteHeight = 0
Texture * texture = nullptr
Quad quad
Detailed Description
Definition at line 7 of file GuiSprite.h.
Constructor & Destructor Documentation
GuiSprite() [1/2]
GuiSprite::GuiSprite () inline
Definition at line 10 of file GuiSprite.h.
GuiSprite() [2/2]
GuiSprite::GuiSprite (Texture & txtre) inline
Definition at line 12 of file GuiSprite.h.
References initialize().
Member Function Documentation
initialize()
void GuiSprite::initialize (Texture & txtre) inline
Definition at line 16 of file GuiSprite.h.
References Texture::getHeight(), Texture::getWidth(), position, scale, spriteHeight, spriteWidth, and texture.
Referenced by GuiSprite(), and PauseMenu::initialize().
render()
void GuiSprite::render (Shader & shader) inline virtual
Implements GuiBase.
Definition at line 53 of file GuiSprite.h.
References DBG_LOG, position, quad, Quad::render3D(), scale, spriteHeight, spriteWidth, spriteXStart, spriteYStart, and texture.
Referenced by PauseMenuSystem::render().
setPosition() [1/2]
void GuiSprite::setPosition (const glm::vec2 & pos) inline
Definition at line 49 of file GuiSprite.h.
References position.
setPosition() [2/2]
void GuiSprite::setPosition (float x, float y) inline
Definition at line 45 of file GuiSprite.h.
References position.
setScale() [1/2]
void GuiSprite::setScale (const glm::vec2 & scaleInPixels) inline
Definition at line 41 of file GuiSprite.h.
References scale.
setScale() [2/2]
void GuiSprite::setScale (float widthInPixels, float heightInPixels) inline
Definition at line 37 of file GuiSprite.h.
References scale.
Referenced by PauseMenuSystem::update().
setSprite()
void GuiSprite::setSprite (float spriteXlocPXL, float spriteYlocPXL, float spriteWPXL, float spriteHPXL) inline
Definition at line 26 of file GuiSprite.h.
References spriteHeight, spriteWidth, spriteXStart, and spriteYStart.
Member Data Documentation
position
glm::vec2 GuiSprite::position = glm::vec2(0.0f, 0.0f) protected
Definition at line 70 of file GuiSprite.h.
Referenced by initialize(), GuiButton::mouseIsInsideButton(), render(), and setPosition().
quad
Quad GuiSprite::quad protected
Definition at line 80 of file GuiSprite.h.
Referenced by render().
scale
glm::vec2 GuiSprite::scale = glm::vec2(0.0f, 0.0f) protected
Definition at line 71 of file GuiSprite.h.
Referenced by initialize(), GuiButton::mouseIsInsideButton(), render(), and setScale().
spriteHeight
float GuiSprite::spriteHeight = 0 protected
Definition at line 77 of file GuiSprite.h.
Referenced by initialize(), render(), and setSprite().
spriteWidth
float GuiSprite::spriteWidth = 0 protected
Definition at line 76 of file GuiSprite.h.
Referenced by initialize(), render(), and setSprite().
spriteXStart
float GuiSprite::spriteXStart = 0 protected
Definition at line 73 of file GuiSprite.h.
Referenced by render(), and setSprite().
spriteYStart
float GuiSprite::spriteYStart = 0 protected
Definition at line 74 of file GuiSprite.h.
Referenced by render(), and setSprite().
texture
Texture* GuiSprite::texture = nullptr protected
Definition at line 79 of file GuiSprite.h.
Referenced by initialize(), and render().
The documentation for this class was generated from the following file:
src/GuiSprite.h