LightShow_Boilerplate: UpdatingSystem Class Reference
UpdatingSystem Class Reference
#include <UpdatingSystem.h>
Public Member Functions
~UpdatingSystem ()
void initialize (Scene &scene, Settings &settings, PhysicsWorld &world, SubSystems &systems) override
void update ()
Public Member Functions inherited from MainSystemBase
virtual ~MainSystemBase ()
void setScene (Scene &scene)
void setCurrentSettings (Settings &settings)
void setPhysicsWorld (PhysicsWorld &world)
bool areVitalsNull ()
Additional Inherited Members
Protected Attributes inherited from MainSystemBase
SubSystems * systems
PhysicsWorld * physicsWorld = nullptr
Settings * currentSettings = nullptr
Scene * currentScene = nullptr
Detailed Description
Definition at line 15 of file UpdatingSystem.h.
Constructor & Destructor Documentation
~UpdatingSystem()
UpdatingSystem::~UpdatingSystem () inline
Definition at line 18 of file UpdatingSystem.h.
Member Function Documentation
initialize()
void UpdatingSystem::initialize (Scene & scene, Settings & settings, PhysicsWorld & world, SubSystems & systems) override virtual
Implements MainSystemBase.
Definition at line 3 of file UpdatingSystem.cpp.
References MainSystemBase::currentScene, MainSystemBase::currentSettings, MainSystemBase::physicsWorld, and MainSystemBase::systems.
update()
void UpdatingSystem::update ()
Definition at line 12 of file UpdatingSystem.cpp.
References SubSystems::cameraSystem, MainSystemBase::currentScene, DBG_LOG, Default, SubSystems::defaultParticleSystem, Fountain, SubSystems::fountainParticleSystem, Scene::getAllEntities(), Scene::getComponent(), Scene::getFirstActiveComponentOfType(), Locator< Input, NullInput >::getService(), SubSystems::guiResizingInfo, Input::isKeyPressedOnce(), Max, SubSystems::pauseMenuSystem, SubSystems::playerCameraHandlingSystem, SubSystems::playerControllerSystem, PlayerCameraHandlingSystem::setThirdPersonCameraTargetPosition(), MainSystemBase::systems, PauseMenuSystem::update(), CameraSystem::update(), PlayerControllerSystem::update(), and DefaultParticleSystem::updateParticles().
The documentation for this class was generated from the following files:
src/game/systems/UpdatingSystem.h
src/game/systems/UpdatingSystem.cpp