LightShow_Boilerplate: Engine Namespace Reference
Engine Namespace Reference
Contains the engine side of things.
Classes
class Application
The Application class manages important tasks like creating a Game, managing the Window and Locators (single instance services) such as Input, Textures, Audio, and Shaders.
class Game
Handles the Game's physics, scene loading, rendering, and updating. Managed by Application.
class Window
Handles all of the window logic for the application.
Functions
unsigned const int getGameWindowWidth ()
unsigned const int getGameWindowHeight ()
static void setMousePosition (int xPos, int yPos)
Variables
bool isRunning = true
The game loop will only run if this is true.
Engine::Window gameWindow = Engine::Window(GameInfo::START_WINDOW_WIDTH, GameInfo::START_WINDOW_HEIGHT)
The window used for the game.
Detailed Description
Contains the engine side of things.
Function Documentation
getGameWindowHeight()
unsigned const int Engine::getGameWindowHeight () inline
Definition at line 21 of file Application.h.
References gameWindow, and Engine::Window::getHeight().
Referenced by GameInfo::getWindowHeight().
getGameWindowWidth()
unsigned const int Engine::getGameWindowWidth () inline
Definition at line 17 of file Application.h.
References gameWindow, and Engine::Window::getWidth().
Referenced by GameInfo::getWindowWidth().
setMousePosition()
static void Engine::setMousePosition (int xPos, int yPos) inline static
Definition at line 25 of file Application.h.
References gameWindow, and Engine::Window::getWindow().
Referenced by GameInfo::setMousePosition().
Variable Documentation
gameWindow
Engine::Window Engine::gameWindow = Engine::Window(GameInfo::START_WINDOW_WIDTH, GameInfo::START_WINDOW_HEIGHT)
The window used for the game.
Definition at line 24 of file Application.cpp.
Referenced by getGameWindowHeight(), getGameWindowWidth(), Engine::Window::initialize(), Engine::Application::initializeSDL(), Engine::Application::render(), Engine::Window::resizeWindow(), setMousePosition(), Engine::Window::setWindowTitle(), Engine::Application::update(), and Engine::Window::~Window().
isRunning
bool Engine::isRunning = true
The game loop will only run if this is true.
Definition at line 25 of file Application.cpp.
Referenced by Engine::Application::run(), and GameInfo::terminateGame().