LightShow_Boilerplate: _3DM::Model Class Reference
_3DM::Model Class Reference
#include <Model.h>
Public Member Functions
Model (const std::string &path)
Model ()
~Model ()
void renderSingleMesh (unsigned int index, Shader &shader)
int getMeshIndex (const std::string &MeshName) const
void initialize (Shader &shader)
void renderAll (Shader &shader)
glm::mat4 getMeshMatrix (unsigned int index) const
void setMeshMatrix (unsigned int index, const glm::mat4 &newMatrix)
unsigned int amountOfMeshes ()
std::vector< glm::vec3 > * getMeshVertices (unsigned int index)
std::vector< uint32_t > * getMeshIndices (unsigned int index)
Public Member Functions inherited from Component< Model >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Public Member Functions inherited from ModelBase
virtual ~ModelBase ()
bool isAnimatedModel ()
Private Member Functions
void initializeBuffers (_3DM::Mesh &mesh, Shader &shader)
void initializeTexture (_3DM::Mesh &mesh, Shader &shader)
void renderMesh (unsigned int index, Shader &shader)
Private Attributes
std::vector< Mesh > meshes
std::string rootPath
bool modelLoaded = false
bool initialized = false
Friends
class _3DM::_3DM_IO
Additional Inherited Members
Public Attributes inherited from ModelBase
Transform transform
Static Public Attributes inherited from Component< Model >
static int32_t type
Protected Attributes inherited from ModelBase
bool animatedModel = false
Detailed Description
Definition at line 17 of file Model.h.
Constructor & Destructor Documentation
Model() [1/2]
_3DM::Model::Model (const std::string & path)
Definition at line 2 of file Model.cpp.
References modelLoaded, and _3DM::_3DM_IO::readModel().
Model() [2/2]
_3DM::Model::Model () inline
Definition at line 20 of file Model.h.
~Model()
_3DM::Model::~Model ()
Definition at line 119 of file Model.cpp.
References DBG_LOG, _3DM::Mesh::elementBufferObject, _3DM::Mesh::normalBufferObject, _3DM::Mesh::uvBufferObject, _3DM::Mesh::vertexArrayObject, and _3DM::Mesh::vertexBufferObject.
Member Function Documentation
amountOfMeshes()
unsigned int _3DM::Model::amountOfMeshes () inline
Definition at line 29 of file Model.h.
References meshes.
Referenced by CollisionMesh::createTriangleMeshCollider(), and CollisionMesh::createTriangleModelCollider().
getMeshIndex()
int _3DM::Model::getMeshIndex (const std::string & MeshName) const
Definition at line 24 of file Model.cpp.
getMeshIndices()
std::vector< uint32_t > * _3DM::Model::getMeshIndices (unsigned int index)
Definition at line 173 of file Model.cpp.
Referenced by CollisionMesh::createTriangleMeshCollider(), and CollisionMesh::createTriangleModelCollider().
getMeshMatrix()
glm::mat4 _3DM::Model::getMeshMatrix (unsigned int index) const
Definition at line 150 of file Model.cpp.
References DBG_LOG.
getMeshVertices()
std::vector< glm::vec3 > * _3DM::Model::getMeshVertices (unsigned int index)
Definition at line 165 of file Model.cpp.
Referenced by CollisionMesh::createTriangleMeshCollider(), and CollisionMesh::createTriangleModelCollider().
initialize()
void _3DM::Model::initialize (Shader & shader) virtual
Implements ModelBase.
Definition at line 100 of file Model.cpp.
initializeBuffers()
void _3DM::Model::initializeBuffers (_3DM::Mesh & mesh, Shader & shader) private
Definition at line 68 of file Model.cpp.
References _3DM::Mesh::elementBufferObject, Shaders::getAttribLocation(), _3DM::Mesh::indices, Shaders::Normal, _3DM::Mesh::normalBufferObject, _3DM::Mesh::normals, Shaders::Position, Shaders::TextureCoordinates, _3DM::Mesh::uvBufferObject, _3DM::Mesh::uvs, _3DM::Mesh::vertexArrayObject, _3DM::Mesh::vertexBufferObject, and _3DM::Mesh::vertices.
initializeTexture()
void _3DM::Model::initializeTexture (_3DM::Mesh & mesh, Shader & shader) private
Definition at line 33 of file Model.cpp.
References _3DM::Diffuse, _3DM::Mesh::diffuseIndex, Shaders::DiffuseTexture, Locator< TextureHandler, TextureHandler >::getService(), TextureHandler::getTexture(), Texture::getTextureData(), Shaders::getUniformName(), _3DM::Normals, _3DM::Mesh::normalsIndex, Shaders::NormalTexture, _3DM::Specular, _3DM::Mesh::specularIndex, Shaders::SpecularTexture, and _3DM::Mesh::textures.
renderAll()
void _3DM::Model::renderAll (Shader & shader) virtual
Implements ModelBase.
Definition at line 137 of file Model.cpp.
renderMesh()
void _3DM::Model::renderMesh (unsigned int index, Shader & shader) private
Definition at line 181 of file Model.cpp.
References Shader::getProgramID(), Shaders::getUniformLocation(), and Shaders::ModelMatrix.
renderSingleMesh()
void _3DM::Model::renderSingleMesh (unsigned int index, Shader & shader) virtual
Implements ModelBase.
Definition at line 12 of file Model.cpp.
References DBG_LOG.
setMeshMatrix()
void _3DM::Model::setMeshMatrix (unsigned int index, const glm::mat4 & newMatrix)
Definition at line 159 of file Model.cpp.
Friends And Related Function Documentation
_3DM::_3DM_IO
friend class _3DM::_3DM_IO friend
Definition at line 48 of file Model.h.
Member Data Documentation
initialized
bool _3DM::Model::initialized = false private
Definition at line 46 of file Model.h.
meshes
std::vector<Mesh> _3DM::Model::meshes private
Definition at line 36 of file Model.h.
Referenced by amountOfMeshes(), _3DM::_3DM_IO::readModel(), and _3DM::_3DM_IO::writeModel().
modelLoaded
bool _3DM::Model::modelLoaded = false private
Definition at line 45 of file Model.h.
Referenced by Model(), _3DM::_3DM_IO::readModel(), and _3DM::_3DM_IO::writeModel().
rootPath
std::string _3DM::Model::rootPath private
Definition at line 44 of file Model.h.
Referenced by _3DM::_3DM_IO::readModel(), and _3DM::_3DM_IO::writeModel().
The documentation for this class was generated from the following files:
src/Model.h
src/Model.cpp