LightShow_Boilerplate: FixedUpdatingSystem Class Reference
FixedUpdatingSystem Class Reference
#include <FixedUpdatingSystem.h>
Public Member Functions
~FixedUpdatingSystem ()
void initialize (Scene &scene, Settings &settings, PhysicsWorld &world, SubSystems &systems) override
Called in Game.cpp.
void fixedUpdate (GameState &gameState, const Time &time, PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap)
Called in Game.cpp.
void handleBackEndMessage (BackEndMessages msg, RenderTextureBase &renderTexture)
Called in Game.cpp.
Public Member Functions inherited from MainSystemBase
virtual ~MainSystemBase ()
void setScene (Scene &scene)
void setCurrentSettings (Settings &settings)
void setPhysicsWorld (PhysicsWorld &world)
bool areVitalsNull ()
Private Member Functions
bool updateGUI (const Time &time, PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap)
Updates GUI (Will be called even if the game is paused) will return true if the game is paused.
void updateShadowMaps (PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap, Camera &currentCamera)
Updates the shadow maps and sets the current shadows light position.
void updateCollision (const int32_t entity, CollisionMesh &collisionMesh)
Updates any collision logic if necessery.
void updateCollisionTriggers (const CollisionTag &thisTag)
checks to see if an entity is colliding with another entity.
void handleCollisionTrigger (const CollisionTag &thisTag, const CollisionTag &otherTag)
executes any logic regarding collisions.
Additional Inherited Members
Protected Attributes inherited from MainSystemBase
SubSystems * systems
PhysicsWorld * physicsWorld = nullptr
Settings * currentSettings = nullptr
Scene * currentScene = nullptr
Detailed Description
Definition at line 20 of file FixedUpdatingSystem.h.
Constructor & Destructor Documentation
~FixedUpdatingSystem()
FixedUpdatingSystem::~FixedUpdatingSystem () inline
Definition at line 23 of file FixedUpdatingSystem.h.
Member Function Documentation
fixedUpdate()
void FixedUpdatingSystem::fixedUpdate (GameState & gameState, const Time & time, PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap)
Called in Game.cpp.
Definition at line 44 of file FixedUpdatingSystem.cpp.
References MainSystemBase::areVitalsNull(), SubSystems::boneCollisionMeshSystem, DebuggingSystem::controlPhysicsDebugDraw(), MainSystemBase::currentScene, SubSystems::dayNightCycleSystem, SubSystems::debuggingSystem, Default, SubSystems::defaultParticleSystem, BoneCollisionMeshSystem::fixedUpdate(), DayNightCycleSystem::fixedUpdate(), PhysicsWorld::fixedUpdate(), DefaultParticleSystem::fixedUpdateParticles(), Fountain, SubSystems::fountainParticleSystem, Scene::getComponent(), GameState::getCurrentSceneIndex(), GameState::getSceneCount(), Locator< Input, NullInput >::getService(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), Scene::Entity::id, Scene::Entity::isActive, GameState::loadScene(), Scene::loopEntities(), Scene::performOperationsOnAllOfType(), MainSystemBase::physicsWorld, GameInfo::setMousePosition(), MainSystemBase::systems, updateCollision(), updateCollisionTriggers(), updateGUI(), and updateShadowMaps().
handleBackEndMessage()
void FixedUpdatingSystem::handleBackEndMessage (BackEndMessages msg, RenderTextureBase & renderTexture)
Called in Game.cpp.
Definition at line 19 of file FixedUpdatingSystem.cpp.
References SubSystems::cameraSystem, MainSystemBase::currentScene, DBG_LOG, Scene::getFirstActiveComponentOfType(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), SubSystems::guiResizingInfo, MESSAGES_END, NULL_MESSAGE, REFRESH_CAMERA, CameraSystem::refreshCamera(), RenderTextureBase::resize(), MainSystemBase::systems, and GUIResizingInformation::updateInformation().
handleCollisionTrigger()
void FixedUpdatingSystem::handleCollisionTrigger (const CollisionTag & thisTag, const CollisionTag & otherTag) private
executes any logic regarding collisions.
Definition at line 263 of file FixedUpdatingSystem.cpp.
References MainSystemBase::currentScene, DBG_LOG, CollisionTag::entity, GET_COLLISION_TAG_NAME(), Scene::isEntityActive(), Player, Scene::setEntityActive(), TAG_ENTITY_UNDEFINED, CollisionTag::tagName, and TestCollisionTag.
Referenced by updateCollisionTriggers().
initialize()
void FixedUpdatingSystem::initialize (Scene & scene, Settings & settings, PhysicsWorld & world, SubSystems & systems) override virtual
Called in Game.cpp.
Implements MainSystemBase.
Definition at line 4 of file FixedUpdatingSystem.cpp.
References SubSystems::cameraSystem, MainSystemBase::currentScene, MainSystemBase::currentSettings, Scene::getFirstActiveComponentOfType(), SubSystems::guiResizingInfo, CameraSystem::initializeCamera(), MainSystemBase::physicsWorld, MainSystemBase::systems, and GUIResizingInformation::updateInformation().
updateCollision()
void FixedUpdatingSystem::updateCollision (const int32_t entity, CollisionMesh & collisionMesh) private
Updates any collision logic if necessery.
Set transforms of models to collision transforms.
Definition at line 200 of file FixedUpdatingSystem.cpp.
References MainSystemBase::currentScene, SubSystems::enemyControllerSystem, PlayerControllerSystem::fixedUpdate(), Scene::getAllComponentsOfType(), Scene::getComponent(), Scene::getFirstActiveComponentOfType(), Locator< Input, NullInput >::getService(), CollisionMesh::getTransformation(), MainSystemBase::physicsWorld, SubSystems::playerControllerSystem, Transform::position, _3DM::AnimatedModel::setAnimationClip(), GlobalInformation::setPlayersPosition(), MainSystemBase::systems, ModelBase::transform, and EnemyControllerSystem::update().
Referenced by fixedUpdate().
updateCollisionTriggers()
void FixedUpdatingSystem::updateCollisionTriggers (const CollisionTag & thisTag) private
checks to see if an entity is colliding with another entity.
Checks for collision tag, if it exists then it will execute triggers on any objects colliding.
Definition at line 250 of file FixedUpdatingSystem.cpp.
References CollisionTag::collidingWith, handleCollisionTrigger(), TAG_EMPTY, and CollisionTag::tagName.
Referenced by fixedUpdate().
updateGUI()
bool FixedUpdatingSystem::updateGUI (const Time & time, PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap) private
Updates GUI (Will be called even if the game is paused) will return true if the game is paused.
Updates GUI.
returns true if the pause menu is showing.
Definition at line 143 of file FixedUpdatingSystem.cpp.
References MainSystemBase::currentScene, Scene::getComponent(), Scene::getFirstActiveComponentOfType(), Scene::Entity::id, Scene::Entity::isActive, and Scene::loopEntities().
Referenced by fixedUpdate().
updateShadowMaps()
void FixedUpdatingSystem::updateShadowMaps (PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap, Camera & currentCamera) private
Updates the shadow maps and sets the current shadows light position.
Provides info for the shadow maps such as the lights' positions.
Definition at line 170 of file FixedUpdatingSystem.cpp.
References MainSystemBase::currentScene, Scene::performOperationsOnAllOfType(), DirectionalLightShadowMap::setCurrentLightDirection(), PointLightShadowMap::setCurrentLightPosition(), DirectionalLightShadowMap::setShadowActive(), PointLightShadowMap::setShadowActive(), DirectionalLightShadowMap::updateDepthMap(), and PointLightShadowMap::updateDepthMap().
Referenced by fixedUpdate().
The documentation for this class was generated from the following files:
src/game/systems/FixedUpdatingSystem.h
src/game/systems/FixedUpdatingSystem.cpp