LightShow_Boilerplate: Camera Class Reference
Camera Class Reference
#include <Camera.h>
Public Member Functions
Camera ()
~Camera ()
glm::vec3 getTargetPosition () const
float getCameraDistance () const
glm::vec3 getRight () const
glm::vec3 getForward () const
glm::mat4 *const getViewMatrix ()
glm::mat4 *const getProjectionMatrix ()
float getFOV ()
float getNearPlane ()
float getFarPlane ()
void setTargetPosition (const glm::vec3 &p)
void setCameraDistance (float distance)
void setFOV (float fov)
Public Member Functions inherited from Component< Camera >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Public Attributes
glm::vec3 position = glm::vec3(0.0f, 0.0f, 3.0f)
Private Attributes
float currentFOV = 70.0f
float nearPlane = .5f
float farPlane = 300.0f
float cameraDistance = 12
float speed = 3.f
int currentWidthOfWindow = 0
int currentHeightOfWindow = 0
glm::mat4 viewMatrix
glm::mat4 projectionMatrix
glm::vec3 cameraFront = glm::vec3(0.0f, 0.0f, -1.0f)
glm::vec3 cameraUp = glm::vec3(0.0f, 1.0f, 0.0f)
glm::vec3 rotation = glm::vec3(90.f, 0.f, -90.f)
glm::vec3 targetPosition = glm::vec3(0, 0, 0)
Friends
class CameraSystem
Additional Inherited Members
Static Public Attributes inherited from Component< Camera >
static int32_t type
Detailed Description
Definition at line 10 of file Camera.h.
Constructor & Destructor Documentation
Camera()
Camera::Camera () inline
Definition at line 13 of file Camera.h.
~Camera()
Camera::~Camera () inline
Definition at line 14 of file Camera.h.
Member Function Documentation
getCameraDistance()
float Camera::getCameraDistance () const inline
Definition at line 22 of file Camera.h.
References cameraDistance.
Referenced by CameraSystem::update().
getFarPlane()
float Camera::getFarPlane () inline
Definition at line 36 of file Camera.h.
References farPlane.
getForward()
glm::vec3 Camera::getForward () const inline
Definition at line 27 of file Camera.h.
References cameraFront.
Referenced by PlayerControllerSystem::fixedUpdate(), PlayerControllerSystem::getPlayerInput(), and PlayerControllerSystem::update().
getFOV()
float Camera::getFOV () inline
Definition at line 33 of file Camera.h.
References currentFOV.
getNearPlane()
float Camera::getNearPlane () inline
Definition at line 35 of file Camera.h.
References nearPlane.
getProjectionMatrix()
glm::mat4* const Camera::getProjectionMatrix () inline
Definition at line 30 of file Camera.h.
References projectionMatrix.
Referenced by RenderingSystem::renderDebugging(), RenderingSystem::supplyDefaultShaderUniforms(), and RenderingSystem::supplyParticleShaderUniforms().
getRight()
glm::vec3 Camera::getRight () const inline
Definition at line 25 of file Camera.h.
References cameraFront, and cameraUp.
Referenced by PlayerControllerSystem::getPlayerInput().
getTargetPosition()
glm::vec3 Camera::getTargetPosition () const inline
Definition at line 19 of file Camera.h.
References targetPosition.
Referenced by DirectionalLightShadowMap::updateDepthMap().
getViewMatrix()
glm::mat4* const Camera::getViewMatrix () inline
Definition at line 29 of file Camera.h.
References viewMatrix.
Referenced by CubeShape::render(), RenderingSystem::renderDebugging(), RenderingSystem::supplyDefaultShaderUniforms(), and RenderingSystem::supplyParticleShaderUniforms().
setCameraDistance()
void Camera::setCameraDistance (float distance) inline
Definition at line 42 of file Camera.h.
References cameraDistance.
Referenced by CameraSystem::update().
setFOV()
void Camera::setFOV (float fov) inline
Definition at line 44 of file Camera.h.
References currentFOV.
setTargetPosition()
void Camera::setTargetPosition (const glm::vec3 & p) inline
Definition at line 39 of file Camera.h.
References targetPosition.
Referenced by PlayerCameraHandlingSystem::setThirdPersonCameraTargetPosition().
Friends And Related Function Documentation
CameraSystem
friend class CameraSystem friend
Definition at line 66 of file Camera.h.
Member Data Documentation
cameraDistance
float Camera::cameraDistance = 12 private
Definition at line 51 of file Camera.h.
Referenced by getCameraDistance(), setCameraDistance(), and CameraSystem::update().
cameraFront
glm::vec3 Camera::cameraFront = glm::vec3(0.0f, 0.0f, -1.0f) private
Definition at line 60 of file Camera.h.
Referenced by getForward(), getRight(), and CameraSystem::update().
cameraUp
glm::vec3 Camera::cameraUp = glm::vec3(0.0f, 1.0f, 0.0f) private
Definition at line 61 of file Camera.h.
Referenced by getRight().
currentFOV
float Camera::currentFOV = 70.0f private
Definition at line 47 of file Camera.h.
Referenced by getFOV(), CameraSystem::refreshCamera(), and setFOV().
currentHeightOfWindow
int Camera::currentHeightOfWindow = 0 private
Definition at line 55 of file Camera.h.
currentWidthOfWindow
int Camera::currentWidthOfWindow = 0 private
Definition at line 54 of file Camera.h.
farPlane
float Camera::farPlane = 300.0f private
Definition at line 49 of file Camera.h.
Referenced by getFarPlane(), and CameraSystem::refreshCamera().
nearPlane
float Camera::nearPlane = .5f private
Definition at line 48 of file Camera.h.
Referenced by getNearPlane(), and CameraSystem::refreshCamera().
position
glm::vec3 Camera::position = glm::vec3(0.0f, 0.0f, 3.0f)
Definition at line 16 of file Camera.h.
Referenced by RenderingSystem::supplyDefaultShaderUniforms(), and CameraSystem::update().
projectionMatrix
glm::mat4 Camera::projectionMatrix private
Definition at line 58 of file Camera.h.
Referenced by getProjectionMatrix(), and CameraSystem::refreshCamera().
rotation
glm::vec3 Camera::rotation = glm::vec3(90.f, 0.f, -90.f) private
Definition at line 63 of file Camera.h.
Referenced by CameraSystem::update().
speed
float Camera::speed = 3.f private
Definition at line 52 of file Camera.h.
Referenced by CameraSystem::update().
targetPosition
glm::vec3 Camera::targetPosition = glm::vec3(0, 0, 0) private
Definition at line 64 of file Camera.h.
Referenced by getTargetPosition(), setTargetPosition(), and CameraSystem::update().
viewMatrix
glm::mat4 Camera::viewMatrix private
Definition at line 57 of file Camera.h.
Referenced by getViewMatrix(), and CameraSystem::update().
The documentation for this class was generated from the following file:
src/game/components/Camera.h