LightShow_Boilerplate: CubeTrigger Class Reference
CubeTrigger Class Reference
Test entity class.
#include <EntityTests.h>
Public Member Functions
~CubeTrigger ()
void initialize (EntityVitals &vitals)
Public Member Functions inherited from EntityWrapper
virtual ~EntityWrapper ()
Private Attributes
_3DM::Model model = _3DM::Model("assets/Models/cube.3DM")
CollisionMesh collisionMesh
Material material
Shader shader
Detailed Description
Test entity class.
Definition at line 134 of file EntityTests.h.
Constructor & Destructor Documentation
~CubeTrigger()
CubeTrigger::~CubeTrigger () inline
Definition at line 137 of file EntityTests.h.
Member Function Documentation
initialize()
void CubeTrigger::initialize (EntityVitals & vitals) virtual
Implements EntityWrapper.
Definition at line 164 of file EntityTests.cpp.
References Scene::addComponent(), _3DM::Model::addTexture(), EntityVitals::checkForNulls(), collisionMesh, EntityVitals::currentSettings, DBG_LOG, _3DM::Diffuse, Scene::generateEntity(), Locator< TextureHandler, TextureHandler >::getService(), Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), CollisionMesh::initialize(), material, model, EntityVitals::scene, shader, _3DM::Specular, and TestCollisionTag.
Member Data Documentation
collisionMesh
CollisionMesh CubeTrigger::collisionMesh private
Definition at line 142 of file EntityTests.h.
Referenced by initialize().
material
Material CubeTrigger::material private
Definition at line 143 of file EntityTests.h.
Referenced by initialize().
model
_3DM::Model CubeTrigger::model = _3DM::Model("assets/Models/cube.3DM") private
Definition at line 141 of file EntityTests.h.
Referenced by initialize().
shader
Shader CubeTrigger::shader private
Definition at line 144 of file EntityTests.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/EntityTests.h
src/EntityTests.cpp