LightShow_Boilerplate: DirectionalShadowDebugger Class Reference
DirectionalShadowDebugger Class Reference
Component to render a depthmap to a quad.
#include <DirectionalShadowDebugger.h>
Public Member Functions
void initialize (const glm::mat4 &QuadTransform)
Public Member Functions inherited from Component< DirectionalShadowDebugger >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
glm::mat4 quadTransform = glm::mat4(1.0f)
Shader depthShader
Quad depthQuad
Friends
class DirectionalShadowDebuggerSystem
Additional Inherited Members
Static Public Attributes inherited from Component< DirectionalShadowDebugger >
static int32_t type
Detailed Description
Component to render a depthmap to a quad.
Definition at line 7 of file DirectionalShadowDebugger.h.
Member Function Documentation
initialize()
void DirectionalShadowDebugger::initialize (const glm::mat4 & QuadTransform) inline
Definition at line 10 of file DirectionalShadowDebugger.h.
References depthShader, Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), and quadTransform.
Referenced by Player::initialize().
Friends And Related Function Documentation
DirectionalShadowDebuggerSystem
friend class DirectionalShadowDebuggerSystem friend
Definition at line 21 of file DirectionalShadowDebugger.h.
Member Data Documentation
depthQuad
Quad DirectionalShadowDebugger::depthQuad private
Definition at line 18 of file DirectionalShadowDebugger.h.
Referenced by DirectionalShadowDebuggerSystem::render().
depthShader
Shader DirectionalShadowDebugger::depthShader private
Definition at line 17 of file DirectionalShadowDebugger.h.
Referenced by initialize(), and DirectionalShadowDebuggerSystem::render().
quadTransform
glm::mat4 DirectionalShadowDebugger::quadTransform = glm::mat4(1.0f) private
Definition at line 16 of file DirectionalShadowDebugger.h.
Referenced by initialize(), and DirectionalShadowDebuggerSystem::render().
The documentation for this class was generated from the following file:
src/game/components/DirectionalShadowDebugger.h