LightShow_Boilerplate: ParticleTest Class Reference
ParticleTest Class Reference
#include <EntityTests.h>
Public Member Functions
~ParticleTest ()
void initialize (EntityWrapper::EntityVitals &vitals)
Public Member Functions inherited from EntityWrapper
virtual ~EntityWrapper ()
Private Attributes
Particles particles = Particles(2000)
Shader particleShader
Detailed Description
Definition at line 55 of file EntityTests.h.
Constructor & Destructor Documentation
~ParticleTest()
ParticleTest::~ParticleTest () inline
Definition at line 58 of file EntityTests.h.
Member Function Documentation
initialize()
void ParticleTest::initialize (EntityWrapper::EntityVitals & vitals) virtual
Implements EntityWrapper.
Definition at line 3 of file EntityTests.cpp.
References Scene::addComponent(), EntityWrapper::EntityVitals::checkForNulls(), EntityWrapper::EntityVitals::currentSettings, DBG_LOG, Fountain, Scene::generateEntity(), Locator< ShaderHandler, ShaderHandler >::getService(), Locator< TextureHandler, TextureHandler >::getService(), ShaderHandler::getShader(), Particles::initialize(), particles, particleShader, EntityWrapper::EntityVitals::scene, Particles::setDefaultColor(), Particles::setDefaultLifeTime(), Particles::setDefaultStartScale(), Particles::setParticlesPerSecond(), Particles::setParticleType(), Particles::setPosition(), Particles::setTexture(), and Particles::setWeight().
Member Data Documentation
particles
Particles ParticleTest::particles = Particles(2000) private
Definition at line 62 of file EntityTests.h.
Referenced by initialize().
particleShader
Shader ParticleTest::particleShader private
Definition at line 63 of file EntityTests.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/EntityTests.h
src/EntityTests.cpp