LightShow_Boilerplate: RenderingSystem Class Reference
RenderingSystem Class Reference
#include <RenderingSystem.h>
Public Member Functions
~RenderingSystem ()
void initialize (Scene &scene, Settings &settings, PhysicsWorld &world, SubSystems &systems) override
void render (PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap, Time &currentTime, const RenderTextureMS &renderTexture)
Public Member Functions inherited from MainSystemBase
virtual ~MainSystemBase ()
void setScene (Scene &scene)
void setCurrentSettings (Settings &settings)
void setPhysicsWorld (PhysicsWorld &world)
bool areVitalsNull ()
Private Member Functions
void renderAll (Camera &currentCamera, Time &currentTime, PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap)
void renderDebugging (Camera &currentCamera)
void renderModels (Camera &currentCamera, Time &currentTime, PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap)
void renderOthers (Camera &currentCamera, Time &currentTime, DirectionalLightShadowMap &directionalLightDepthMap)
void renderParticles (Particles &particles, Camera &currentCamera, Time &currentTime)
void initializeLights (Shader &litShader)
void initializeModels (Shader &shader, const int32_t &entity)
Shader * prepareShader (const int32_t &entity, PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap, Camera &currentCamera, Time &currentTime)
Prepares and retrieves the first shader found in scene that is associated with entity.
void supplyLitShaderUniforms (Shader &shader, PointLightShadowMap &pointLightDepthMap, DirectionalLightShadowMap &directionalLightDepthMap, Camera &currentCamera, Time &currentTime)
void supplyDefaultShaderUniforms (Shader &shader, Camera &currentCamera, Time &currentTime)
void supplyParticleShaderUniforms (Shader &particleShader, Camera &currentCamera, Time &currentTime)
Private Attributes
Quad screenQuad
Used to render the scene to a quad.
Shader screenShader
The shader used for the screenQuad.
Additional Inherited Members
Protected Attributes inherited from MainSystemBase
SubSystems * systems
PhysicsWorld * physicsWorld = nullptr
Settings * currentSettings = nullptr
Scene * currentScene = nullptr
Detailed Description
Definition at line 20 of file RenderingSystem.h.
Constructor & Destructor Documentation
~RenderingSystem()
RenderingSystem::~RenderingSystem () inline
Definition at line 23 of file RenderingSystem.h.
Member Function Documentation
initialize()
void RenderingSystem::initialize (Scene & scene, Settings & settings, PhysicsWorld & world, SubSystems & systems) override virtual
Implements MainSystemBase.
Definition at line 3 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, MainSystemBase::currentSettings, Scene::getComponent(), Scene::Entity::id, Scene::loopEntities(), MainSystemBase::physicsWorld, and MainSystemBase::systems.
initializeLights()
void RenderingSystem::initializeLights (Shader & litShader) private
Definition at line 40 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, MainSystemBase::currentSettings, Scene::getAllComponentsOfType(), Scene::getFirstActiveComponentOfType(), Shader::setDirectionalLight(), Shader::setPointLight(), and Shader::useProgram().
Referenced by render().
initializeModels()
void RenderingSystem::initializeModels (Shader & shader, const int32_t & entity) private
Definition at line 68 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, and Scene::getComponent().
prepareShader()
Shader * RenderingSystem::prepareShader (const int32_t & entity, PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap, Camera & currentCamera, Time & currentTime) private
Prepares and retrieves the first shader found in scene that is associated with entity.
*Does use program.
Definition at line 320 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, Scene::getComponent(), Shader::getShaderType(), Scene::isEntityActive(), supplyDefaultShaderUniforms(), supplyLitShaderUniforms(), and Shader::useProgram().
render()
void RenderingSystem::render (PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap, Time & currentTime, const RenderTextureMS & renderTexture)
Definition at line 77 of file RenderingSystem.cpp.
References MainSystemBase::areVitalsNull(), MainSystemBase::currentScene, DBG_LOG, Scene::getAllComponentsOfType(), RenderTextureMS::getCurrentMultisampleCount(), DirectionalLightShadowMap::getDepthMapHeight(), PointLightShadowMap::getDepthMapHeight(), DirectionalLightShadowMap::getDepthMapWidth(), PointLightShadowMap::getDepthMapWidth(), RenderTextureBase::getFBO(), DirectionalLightShadowMap::getFBO(), PointLightShadowMap::getFBO(), Scene::getFirstActiveComponentOfType(), RenderTextureBase::getHeight(), Shader::getProgramID(), RenderTextureBase::getTextureID(), Shaders::getUniformLocation(), RenderTextureBase::getWidth(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), initializeLights(), DirectionalLightShadowMap::isActive(), PointLightShadowMap::isActive(), Shaders::MultisampleCount, Quad::render2D(), renderAll(), screenQuad, screenShader, Shader::setShaderTask(), and Shader::useProgram().
renderAll()
void RenderingSystem::renderAll (Camera & currentCamera, Time & currentTime, PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap) private
Definition at line 167 of file RenderingSystem.cpp.
References renderDebugging(), renderModels(), and renderOthers().
Referenced by render().
renderDebugging()
void RenderingSystem::renderDebugging (Camera & currentCamera) private
Definition at line 174 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, SubSystems::dayNightCycleSystem, SubSystems::debuggingSystem, PlayerControllerSystem::debugRender(), DayNightCycleSystem::debugRender(), DebuggingSystem::executeDebugRendering(), Scene::getAllComponentsOfType(), Camera::getProjectionMatrix(), Shader::getShaderTask(), Camera::getViewMatrix(), MainSystemBase::physicsWorld, SubSystems::playerControllerSystem, and MainSystemBase::systems.
Referenced by renderAll().
renderModels()
void RenderingSystem::renderModels (Camera & currentCamera, Time & currentTime, PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap) private
Definition at line 189 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, Scene::getComponent(), Scene::Entity::id, Scene::Entity::isActive, and Scene::loopEntities().
Referenced by renderAll().
renderOthers()
void RenderingSystem::renderOthers (Camera & currentCamera, Time & currentTime, DirectionalLightShadowMap & directionalLightDepthMap) private
Definition at line 238 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, SubSystems::directionalShadowDebuggerSystem, SubSystems::displayStatisticsSystem, Scene::getAllComponentsOfType(), Scene::getComponent(), ComponentInterface::getEntityID(), Scene::getFirstActiveComponentOfType(), Shader::getShaderTask(), Shader::getShaderType(), Scene::Entity::id, Scene::loopEntities(), SubSystems::pauseMenuSystem, SkyBoxSystem::render(), DirectionalShadowDebuggerSystem::render(), DisplayStatisticsSystem::render(), PauseMenuSystem::render(), renderParticles(), SubSystems::skyBoxSystem, supplyDefaultShaderUniforms(), MainSystemBase::systems, and Shader::useProgram().
Referenced by renderAll().
renderParticles()
void RenderingSystem::renderParticles (Particles & particles, Camera & currentCamera, Time & currentTime) private
Definition at line 301 of file RenderingSystem.cpp.
References MainSystemBase::currentScene, Default, SubSystems::defaultParticleSystem, Fountain, SubSystems::fountainParticleSystem, Scene::getComponent(), ComponentInterface::getEntityID(), Particles::getParticleType(), DefaultParticleSystem::renderParticles(), supplyParticleShaderUniforms(), and MainSystemBase::systems.
Referenced by renderOthers().
supplyDefaultShaderUniforms()
void RenderingSystem::supplyDefaultShaderUniforms (Shader & shader, Camera & currentCamera, Time & currentTime) private
Definition at line 353 of file RenderingSystem.cpp.
References Shader::getProgramID(), Camera::getProjectionMatrix(), Shaders::getUniformLocation(), Camera::getViewMatrix(), Camera::position, Shaders::ProjectionMatrix, Shaders::ViewMatrix, and Shaders::ViewPosition.
Referenced by prepareShader(), renderOthers(), and supplyLitShaderUniforms().
supplyLitShaderUniforms()
void RenderingSystem::supplyLitShaderUniforms (Shader & shader, PointLightShadowMap & pointLightDepthMap, DirectionalLightShadowMap & directionalLightDepthMap, Camera & currentCamera, Time & currentTime) private
Definition at line 363 of file RenderingSystem.cpp.
References Shaders::DEPTH_MAP_LOCATION_DIRECTIONAL, Shaders::DEPTH_MAP_LOCATION_OMNIDIRECTIONAL, Shaders::DirectionalShadowMap, Shaders::FarPlane, PointLightShadowMap::getCubeMap(), PointLightShadowMap::getCurrentLightPosition(), DirectionalLightShadowMap::getDepthMap(), PointLightShadowMap::getFarPlane(), DirectionalLightShadowMap::getLightSpaceMatrix(), Shader::getProgramID(), Shaders::getUniformLocation(), PointLightShadowMap::isActive(), Shaders::LightPosition, Shaders::LightSpaceMatrix, Shaders::PointShadowMap, and supplyDefaultShaderUniforms().
Referenced by prepareShader().
supplyParticleShaderUniforms()
void RenderingSystem::supplyParticleShaderUniforms (Shader & particleShader, Camera & currentCamera, Time & currentTime) private
Definition at line 393 of file RenderingSystem.cpp.
References Shader::getProgramID(), Camera::getProjectionMatrix(), Shaders::getUniformLocation(), Camera::getViewMatrix(), Shaders::ProjectionMatrix, Shader::useProgram(), and Shaders::ViewMatrix.
Referenced by renderParticles().
Member Data Documentation
screenQuad
Quad RenderingSystem::screenQuad private
Used to render the scene to a quad.
Definition at line 49 of file RenderingSystem.h.
Referenced by render().
screenShader
Shader RenderingSystem::screenShader private
The shader used for the screenQuad.
Definition at line 52 of file RenderingSystem.h.
Referenced by render().
The documentation for this class was generated from the following files:
src/game/systems/RenderingSystem.h
src/game/systems/RenderingSystem.cpp