LightShow_Boilerplate: PauseMenuSystem Class Reference
PauseMenuSystem Class Reference
#include <PauseMenuSystem.h>
Public Member Functions
void update (Input &input, PauseMenu &menu, GUIResizingInformation &guiInfo, const UserControls &userControls)
void render (Shader &shader, PauseMenu &menu)
Detailed Description
Definition at line 8 of file PauseMenuSystem.h.
Member Function Documentation
render()
void PauseMenuSystem::render (Shader & shader, PauseMenu & menu) inline
Definition at line 39 of file PauseMenuSystem.h.
References GuiString::getWidthOfString(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), PauseMenu::isShowing, GuiString::render(), GuiSprite::render(), PauseMenu::resumeButton, GuiString::setPosition(), GuiString::setVerticalPadding(), and PauseMenu::str.
Referenced by RenderingSystem::renderOthers().
update()
void PauseMenuSystem::update (Input & input, PauseMenu & menu, GUIResizingInformation & guiInfo, const UserControls & userControls) inline
Definition at line 10 of file PauseMenuSystem.h.
References UserControls::getGuiControlPauseMenuKey(), GUIResizingInformation::getWidthUnit(), PauseMenu::isShowing, Input::keyPressedOnce(), PauseMenu::lastUnit, GuiButton::onButtonClickedOnce(), PauseMenu::resumeButton, GuiSprite::setScale(), GuiString::setScale(), PauseMenu::str, and GuiButton::update().
Referenced by UpdatingSystem::update().
The documentation for this class was generated from the following file:
src/PauseMenuSystem.h