LightShow_Boilerplate: Input Class Reference
Input Class Reference
#include <Input.h>
Classes
struct KeyData
Contains data for all of the keys.
Public Member Functions
Input ()
virtual void updateTimers (float dt)
Updates timers for timeBetweenPress and timeBetweenPressReset. Should only be called in Application.cpp.
virtual bool isMousePressedOnce (MOUSE_BUTTON)
Checks if the mouse is pressed and returns true if the timeBetweenPress is zero, if it's the first press, or if timeUntilContinious is 0.
virtual bool isMouseButtonPressed (MOUSE_BUTTON)
Checks if a mouse button is pressed.
virtual bool isKeyPressedOnce (const SDL_Keycode &keycode)
Checks if the key is pressed and returns true if the timeBetweenPress is zero, if it's the first press, or if timeUntilContinious is 0.
virtual bool isKeyDown (const SDL_Keycode &keycode)
Checks if a key is pressed.
virtual void handleEvents (SDL_Event &sdlEventSystem, SDL_EventType t)
Called by Application.cpp to handle SDL's new events.
virtual glm::ivec2 getMousePosition () const
Returns the mouse position relative to the top left of the screen.
virtual glm::ivec2 getMouseDelta () const
Returns the mouse position relative to the center of the screen.
Private Member Functions
bool isPressedOnce (KeyData &data)
Checks if the KeyData d is pressed and returns true if the timeBetweenPress is zero, if it's the first press, or if timeUntilContinious is 0.
Private Attributes
std::vector< KeyData * > currentPressedOnce
For updating the timers every update. Gets cleared every update.
KeyData keyData [SDL_NUM_SCANCODES]
KeyData mouseData [3]
glm::ivec2 mousePosition = glm::ivec2(0, 0)
glm::ivec2 mouseLastPosition = glm::ivec2(0, 0)
Detailed Description
Definition at line 29 of file Input.h.
Constructor & Destructor Documentation
Input()
Input::Input ()
Definition at line 23 of file Input.cpp.
Member Function Documentation
getMouseDelta()
virtual glm::ivec2 Input::getMouseDelta () const inline virtual
Returns the mouse position relative to the center of the screen.
To get the delta value, the mouse position is expected to be set to the window's center every FixedUpdate.
Reimplemented in NullInput.
Definition at line 61 of file Input.h.
References GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), and mousePosition.
Referenced by CameraSystem::update().
getMousePosition()
virtual glm::ivec2 Input::getMousePosition () const inline virtual
Returns the mouse position relative to the top left of the screen.
Reimplemented in NullInput.
Definition at line 55 of file Input.h.
References mousePosition.
Referenced by GuiButton::update().
handleEvents()
void Input::handleEvents (SDL_Event & sdlEventSystem, SDL_EventType t) virtual
Called by Application.cpp to handle SDL's new events.
Reimplemented in NullInput.
Definition at line 64 of file Input.cpp.
References Input::KeyData::isPressed, keyData, mouseData, mousePosition, and GameInfo::terminateGame().
Referenced by Engine::Application::update().
isKeyDown()
bool Input::isKeyDown (const SDL_Keycode & keycode) virtual
Checks if a key is pressed.
Reimplemented in NullInput.
Definition at line 15 of file Input.cpp.
References Input::KeyData::isPressed, and keyData.
Referenced by PlayerControllerSystem::getPlayerInput().
isKeyPressedOnce()
bool Input::isKeyPressedOnce (const SDL_Keycode & keycode) virtual
Checks if the key is pressed and returns true if the timeBetweenPress is zero, if it's the first press, or if timeUntilContinious is 0.
NOTE: isPressedOnce function's timeBeetweenPress only works properly in Update, not FixedUpdate.
Reimplemented in NullInput.
Definition at line 19 of file Input.cpp.
References isPressedOnce(), and keyData.
Referenced by DebuggingSystem::controlPhysicsDebugDraw(), PlayerControllerSystem::getPlayerInput(), PauseMenuSystem::update(), and UpdatingSystem::update().
isMouseButtonPressed()
bool Input::isMouseButtonPressed (MOUSE_BUTTON ind) virtual
Checks if a mouse button is pressed.
Reimplemented in NullInput.
Definition at line 123 of file Input.cpp.
References Input::KeyData::isPressed, and mouseData.
Referenced by GuiButton::update().
isMousePressedOnce()
bool Input::isMousePressedOnce (MOUSE_BUTTON ind) virtual
Checks if the mouse is pressed and returns true if the timeBetweenPress is zero, if it's the first press, or if timeUntilContinious is 0.
NOTE: isPressedOnce function's timeBeetweenPress only works properly in Update, not FixedUpdate.
Reimplemented in NullInput.
Definition at line 11 of file Input.cpp.
References isPressedOnce(), and mouseData.
isPressedOnce()
bool Input::isPressedOnce (KeyData & data) private
Checks if the KeyData d is pressed and returns true if the timeBetweenPress is zero, if it's the first press, or if timeUntilContinious is 0.
NOTE: isPressedOnce function's timeBeetweenPress only works properly in Update, not FixedUpdate.
Definition at line 90 of file Input.cpp.
References currentPressedOnce, Input::KeyData::isPressed, Input::KeyData::timeBetweenPress, and Input::KeyData::timeUntilContinious.
Referenced by isKeyPressedOnce(), and isMousePressedOnce().
updateTimers()
void Input::updateTimers (float dt) virtual
Updates timers for timeBetweenPress and timeBetweenPressReset. Should only be called in Application.cpp.
Reimplemented in NullInput.
Definition at line 27 of file Input.cpp.
References currentPressedOnce, Engine::InputData::NO_CONTINIOUS_PRESS, Engine::InputData::TIME_BETWEEN_KEY_PRESS_RESET, and Engine::InputData::TIME_UNTIL_CONTINIOUS_PRESS_RESET.
Referenced by Engine::Application::update().
Member Data Documentation
currentPressedOnce
std::vector<KeyData*> Input::currentPressedOnce private
For updating the timers every update. Gets cleared every update.
Definition at line 76 of file Input.h.
Referenced by isPressedOnce(), and updateTimers().
keyData
KeyData Input::keyData[SDL_NUM_SCANCODES] private
Definition at line 82 of file Input.h.
Referenced by handleEvents(), isKeyDown(), and isKeyPressedOnce().
mouseData
KeyData Input::mouseData[3] private
Definition at line 83 of file Input.h.
Referenced by handleEvents(), isMouseButtonPressed(), and isMousePressedOnce().
mouseLastPosition
glm::ivec2 Input::mouseLastPosition = glm::ivec2(0, 0) private
Definition at line 86 of file Input.h.
mousePosition
glm::ivec2 Input::mousePosition = glm::ivec2(0, 0) private
Definition at line 85 of file Input.h.
Referenced by getMouseDelta(), getMousePosition(), and handleEvents().
The documentation for this class was generated from the following files:
src/engine/locators/Input.h
src/engine/locators/Input.cpp