LightShow_Boilerplate: Texture Class Reference
Texture Class Reference
#include <Texture.h>
Public Member Functions
Texture (std::string loc, GLuint txture, GLuint w, GLuint h, bool istransparent)
~Texture ()
bool checkTransparency () const
GLuint getWidth () const
GLuint getHeight () const
GLuint getTextureData () const
std::string getLocation () const
Private Attributes
GLuint imageWidth = 0
GLuint imageHeight = 0
GLuint texture = 0
bool isTransparent = false
std::string location
Detailed Description
Definition at line 15 of file Texture.h.
Constructor & Destructor Documentation
Texture()
Texture::Texture (std::string loc, GLuint txture, GLuint w, GLuint h, bool istransparent)
Definition at line 3 of file Texture.cpp.
References imageHeight, imageWidth, isTransparent, location, and texture.
~Texture()
Texture::~Texture ()
Definition at line 10 of file Texture.cpp.
References DBG_LOG, and texture.
Member Function Documentation
checkTransparency()
bool Texture::checkTransparency () const inline
Definition at line 20 of file Texture.h.
References isTransparent.
getHeight()
GLuint Texture::getHeight () const inline
Definition at line 22 of file Texture.h.
References imageHeight.
Referenced by GuiSprite::initialize(), and Quad::render3D().
getLocation()
std::string Texture::getLocation () const inline
Definition at line 24 of file Texture.h.
References location.
getTextureData()
GLuint Texture::getTextureData () const inline
Definition at line 23 of file Texture.h.
References texture.
Referenced by _3DM::Model::initializeTexture(), _3DM::AnimatedModel::initializeTexture(), Quad::render3D(), and DefaultParticleSystem::renderParticles().
getWidth()
GLuint Texture::getWidth () const inline
Definition at line 21 of file Texture.h.
References imageWidth.
Referenced by GuiSprite::initialize(), and Quad::render3D().
Member Data Documentation
imageHeight
GLuint Texture::imageHeight = 0 private
Definition at line 28 of file Texture.h.
Referenced by getHeight(), and Texture().
imageWidth
GLuint Texture::imageWidth = 0 private
Definition at line 27 of file Texture.h.
Referenced by getWidth(), and Texture().
isTransparent
bool Texture::isTransparent = false private
Definition at line 30 of file Texture.h.
Referenced by checkTransparency(), and Texture().
location
std::string Texture::location private
Definition at line 31 of file Texture.h.
Referenced by getLocation(), and Texture().
texture
GLuint Texture::texture = 0 private
Definition at line 29 of file Texture.h.
Referenced by getTextureData(), Texture(), and ~Texture().
The documentation for this class was generated from the following files:
src/Texture.h
src/Texture.cpp