LightShow_Boilerplate: RayCaster Class Reference
RayCaster Class Reference
#include <RayCaster.h>
Public Member Functions
RayCaster (const glm::vec3 &from, const glm::vec3 &to)
RayCaster ()
bool hasHit ()
const RayResultCallback * getCallback ()
void rayTest (const btCollisionWorld &collisionWorld)
void rayTest (const btCollisionWorld &collisionWorld, const btVector3 &from, const btVector3 &to)
void rayTest (const btCollisionWorld &collisionWorld, const glm::vec3 &from, const glm::vec3 &to)
void resetCallback (const glm::vec3 &from, const glm::vec3 &to)
void resetCallback (const btVector3 &from, const btVector3 &to)
void resetCallback ()
float getHitFraction (int index) const
float getLength () const
float getHitFractionRaySpace (int index) const
const btCollisionObject * getCollisionObject (int index) const
int size () const
btVector3 getHitNormal (int index)
Public Member Functions inherited from Component< RayCaster >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
float length = 0
btVector3 rayFrom
btVector3 rayTo
RayResultCallback rayCallback = RayResultCallback(btVector3(0, 0, 0), btVector3(0, 0, 0))
Additional Inherited Members
Static Public Attributes inherited from Component< RayCaster >
static int32_t type
Detailed Description
Definition at line 9 of file RayCaster.h.
Constructor & Destructor Documentation
RayCaster() [1/2]
RayCaster::RayCaster (const glm::vec3 & from, const glm::vec3 & to) inline
Definition at line 12 of file RayCaster.h.
References rayFrom, rayTo, resetCallback(), and hh::toBtVec3().
RayCaster() [2/2]
RayCaster::RayCaster () inline
Definition at line 18 of file RayCaster.h.
Member Function Documentation
getCallback()
const RayResultCallback* RayCaster::getCallback () inline
Definition at line 24 of file RayCaster.h.
References rayCallback.
getCollisionObject()
const btCollisionObject* RayCaster::getCollisionObject (int index) const inline
Definition at line 70 of file RayCaster.h.
References rayCallback.
Referenced by EnemyControllerSystem::getLowestRayHitIndex(), and PlayerControllerSystem::getLowestRayHitIndex().
getHitFraction()
float RayCaster::getHitFraction (int index) const inline
Definition at line 60 of file RayCaster.h.
References rayCallback.
Referenced by EnemyControllerSystem::getLowestRayHitIndex(), and PlayerControllerSystem::getLowestRayHitIndex().
getHitFractionRaySpace()
float RayCaster::getHitFractionRaySpace (int index) const inline
Definition at line 66 of file RayCaster.h.
References length, and rayCallback.
Referenced by EnemyControllerSystem::getLowestRayHitForAllRays(), and PlayerControllerSystem::getLowestRayHitForAllRays().
getHitNormal()
btVector3 RayCaster::getHitNormal (int index) inline
Definition at line 74 of file RayCaster.h.
References rayCallback.
Referenced by EnemyControllerSystem::executeRayTesting(), and PlayerControllerSystem::executeRayTesting().
getLength()
float RayCaster::getLength () const inline
Definition at line 64 of file RayCaster.h.
References length.
Referenced by EnemyControllerSystem::getLowestRayHitForAllRays(), and PlayerControllerSystem::getLowestRayHitForAllRays().
hasHit()
bool RayCaster::hasHit () inline
Definition at line 20 of file RayCaster.h.
References rayCallback.
rayTest() [1/3]
void RayCaster::rayTest (const btCollisionWorld & collisionWorld) inline
Definition at line 28 of file RayCaster.h.
References rayCallback, rayFrom, and rayTo.
Referenced by EnemyControllerSystem::executeRayTesting(), and PlayerControllerSystem::executeRayTesting().
rayTest() [2/3]
void RayCaster::rayTest (const btCollisionWorld & collisionWorld, const btVector3 & from, const btVector3 & to) inline
Definition at line 32 of file RayCaster.h.
References rayCallback, rayFrom, rayTo, and resetCallback().
rayTest() [3/3]
void RayCaster::rayTest (const btCollisionWorld & collisionWorld, const glm::vec3 & from, const glm::vec3 & to) inline
Definition at line 39 of file RayCaster.h.
References rayCallback, rayFrom, rayTo, resetCallback(), and hh::toBtVec3().
resetCallback() [1/3]
void RayCaster::resetCallback () inline
Definition at line 55 of file RayCaster.h.
References length, rayCallback, rayFrom, rayTo, and hh::toGlmVec3().
Referenced by RayCaster(), and rayTest().
resetCallback() [2/3]
void RayCaster::resetCallback (const btVector3 & from, const btVector3 & to) inline
Definition at line 51 of file RayCaster.h.
References length, rayCallback, rayFrom, rayTo, and hh::toGlmVec3().
resetCallback() [3/3]
void RayCaster::resetCallback (const glm::vec3 & from, const glm::vec3 & to) inline
Definition at line 47 of file RayCaster.h.
References length, rayCallback, rayFrom, rayTo, hh::toBtVec3(), and hh::toGlmVec3().
size()
int RayCaster::size () const inline
Definition at line 72 of file RayCaster.h.
References rayCallback.
Referenced by EnemyControllerSystem::executeRayTesting(), PlayerControllerSystem::executeRayTesting(), PlayerControllerSystem::getLowestRayHitIndex(), and EnemyControllerSystem::getLowestRayHitIndex().
Member Data Documentation
length
float RayCaster::length = 0 private
Definition at line 77 of file RayCaster.h.
Referenced by getHitFractionRaySpace(), getLength(), and resetCallback().
rayCallback
RayResultCallback RayCaster::rayCallback = RayResultCallback(btVector3(0, 0, 0), btVector3(0, 0, 0)) private
Definition at line 81 of file RayCaster.h.
Referenced by getCallback(), getCollisionObject(), getHitFraction(), getHitFractionRaySpace(), getHitNormal(), hasHit(), rayTest(), resetCallback(), and size().
rayFrom
btVector3 RayCaster::rayFrom private
Definition at line 79 of file RayCaster.h.
Referenced by RayCaster(), rayTest(), and resetCallback().
rayTo
btVector3 RayCaster::rayTo private
Definition at line 80 of file RayCaster.h.
Referenced by RayCaster(), rayTest(), and resetCallback().
The documentation for this class was generated from the following file:
src/RayCaster.h