LightShow_Boilerplate: SkyBox Class Reference
SkyBox Class Reference
#include <SkyBox.h>
Public Member Functions
CubeShape * getCube ()
CubeMap * getCubeMap ()
void supplyMap (CubeMap &m)
Public Member Functions inherited from Component< SkyBox >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
CubeShape cube
CubeMap * map
Additional Inherited Members
Static Public Attributes inherited from Component< SkyBox >
static int32_t type
Detailed Description
Definition at line 6 of file SkyBox.h.
Member Function Documentation
getCube()
CubeShape* SkyBox::getCube () inline
Definition at line 9 of file SkyBox.h.
References cube.
Referenced by SkyBoxSystem::init(), and SkyBoxSystem::render().
getCubeMap()
CubeMap* SkyBox::getCubeMap () inline
Definition at line 10 of file SkyBox.h.
References map.
Referenced by SkyBoxSystem::render().
supplyMap()
void SkyBox::supplyMap (CubeMap & m) inline
Definition at line 18 of file SkyBox.h.
References map.
Referenced by LightTest::initialize().
Member Data Documentation
cube
CubeShape SkyBox::cube private
Definition at line 21 of file SkyBox.h.
Referenced by getCube().
map
CubeMap* SkyBox::map private
Definition at line 22 of file SkyBox.h.
Referenced by getCubeMap(), and supplyMap().
The documentation for this class was generated from the following file:
src/SkyBox.h