LightShow_Boilerplate: FloorObject Class Reference
FloorObject Class Reference
Test entity class.
#include <EntityTests.h>
Public Member Functions
~FloorObject ()
void initialize (EntityVitals &vitals)
Public Member Functions inherited from EntityWrapper
virtual ~EntityWrapper ()
Private Attributes
_3DM::Model model = _3DM::Model("assets/models/scenes/test/testlevel.3DM")
_3DM::Model cm = _3DM::Model("assets/models/scenes/test/testlevel-cm.3DM")
CollisionMesh collisionMesh
Material floorMaterial
Shader shader
Detailed Description
Test entity class.
Definition at line 148 of file EntityTests.h.
Constructor & Destructor Documentation
~FloorObject()
FloorObject::~FloorObject () inline
Definition at line 150 of file EntityTests.h.
Member Function Documentation
initialize()
void FloorObject::initialize (EntityVitals & vitals) virtual
Implements EntityWrapper.
Definition at line 193 of file EntityTests.cpp.
References Scene::addComponent(), EntityVitals::checkForNulls(), cm, collisionMesh, EntityVitals::currentSettings, DBG_LOG, floorMaterial, Scene::generateEntity(), Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), CollisionMesh::getShape(), CollisionMesh::initializeModelShape(), model, EntityVitals::scene, shader, and Material::shininess.
Member Data Documentation
cm
_3DM::Model FloorObject::cm = _3DM::Model("assets/models/scenes/test/testlevel-cm.3DM") private
Definition at line 155 of file EntityTests.h.
Referenced by initialize().
collisionMesh
CollisionMesh FloorObject::collisionMesh private
Definition at line 156 of file EntityTests.h.
Referenced by initialize().
floorMaterial
Material FloorObject::floorMaterial private
Definition at line 157 of file EntityTests.h.
Referenced by initialize().
model
_3DM::Model FloorObject::model = _3DM::Model("assets/models/scenes/test/testlevel.3DM") private
Definition at line 154 of file EntityTests.h.
Referenced by initialize().
shader
Shader FloorObject::shader private
Definition at line 158 of file EntityTests.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/game/entities/EntityTests.h
src/game/entities/EntityTests.cpp