LightShow_Boilerplate: CubeShape Class Reference
CubeShape Class Reference
#include <Cube.h>
Public Member Functions
void create ()
void render (Shader &shader, Camera &camera)
~CubeShape ()
Private Attributes
std::vector< GLfloat > vertices
GLuint VAOID
GLuint vertID
bool initialized = false
Detailed Description
Definition at line 11 of file Cube.h.
Constructor & Destructor Documentation
~CubeShape()
CubeShape::~CubeShape () inline
Definition at line 91 of file Cube.h.
References DBG_LOG, initialized, VAOID, and vertID.
Member Function Documentation
create()
void CubeShape::create () inline
Definition at line 13 of file Cube.h.
References Shaders::getAttribLocation(), initialized, Shaders::Position, VAOID, vertices, and vertID.
Referenced by SkyBoxSystem::init().
render()
void CubeShape::render (Shader & shader, Camera & camera) inline
Definition at line 69 of file Cube.h.
References Shader::getProgramID(), Shaders::getUniformLocation(), Camera::getViewMatrix(), Shaders::ModelMatrix, VAOID, vertices, vertID, and Shaders::ViewMatrix.
Referenced by SkyBoxSystem::render().
Member Data Documentation
initialized
bool CubeShape::initialized = false private
Definition at line 107 of file Cube.h.
Referenced by create(), and ~CubeShape().
VAOID
GLuint CubeShape::VAOID private
Definition at line 105 of file Cube.h.
Referenced by create(), render(), and ~CubeShape().
vertices
std::vector<GLfloat> CubeShape::vertices private
Definition at line 104 of file Cube.h.
Referenced by create(), and render().
vertID
GLuint CubeShape::vertID private
Definition at line 106 of file Cube.h.
Referenced by create(), render(), and ~CubeShape().
The documentation for this class was generated from the following file:
src/Cube.h