LightShow_Boilerplate: ShaderHandler Class Reference
ShaderHandler Class Reference
#include <Shader.h>
Public Member Functions
Shader & getShader (const std::string &id, const Settings &currentSettings, const std::string &vertexPath, const std::string &fragmentPath, const SHADER_TYPE &type, const std::string &geometryPath="")
Shader & getShader (const std::string &id, const std::string &vertexPath, const std::string &fragmentPath, const SHADER_TYPE &type, const std::string &geometryPath="")
~ShaderHandler ()
Private Member Functions
Shader * binarySearchShaders (const std::string &key)
Shader & addNewShader (const std::string &id, const std::string &vertexPath, const std::string &fragmentPath, const SHADER_TYPE &type, const std::string &geometryPath)
Shader & addNewShader (const std::string &id, const Settings &currentSettings, const std::string &vertexPath, const std::string &fragmentPath, const SHADER_TYPE &type, const std::string &geometryPath)
Private Attributes
std::vector< Shader * > shaderLibrary
Detailed Description
Definition at line 110 of file Shader.h.
Constructor & Destructor Documentation
~ShaderHandler()
ShaderHandler::~ShaderHandler () inline
Definition at line 143 of file Shader.h.
References DBG_LOG, and shaderLibrary.
Member Function Documentation
addNewShader() [1/2]
Shader& ShaderHandler::addNewShader (const std::string & id, const Settings & currentSettings, const std::string & vertexPath, const std::string & fragmentPath, const SHADER_TYPE & type, const std::string & geometryPath) inline private
Definition at line 195 of file Shader.h.
References shaderLibrary.
addNewShader() [2/2]
Shader& ShaderHandler::addNewShader (const std::string & id, const std::string & vertexPath, const std::string & fragmentPath, const SHADER_TYPE & type, const std::string & geometryPath) inline private
Definition at line 176 of file Shader.h.
References shaderLibrary.
Referenced by getShader().
binarySearchShaders()
Shader* ShaderHandler::binarySearchShaders (const std::string & key) inline private
Definition at line 156 of file Shader.h.
References shaderLibrary.
Referenced by getShader().
getShader() [1/2]
Shader& ShaderHandler::getShader (const std::string & id, const Settings & currentSettings, const std::string & vertexPath, const std::string & fragmentPath, const SHADER_TYPE & type, const std::string & geometryPath = "") inline
Definition at line 113 of file Shader.h.
References addNewShader(), and binarySearchShaders().
Referenced by DirectionalShadowDebugger::initialize(), DirectionalLightShadowMap::initialize(), PointLightShadowMap::initialize(), Engine::DebugDrawer::initialize(), LightTest::initialize(), ParticleTest::initialize(), Player::initialize(), PlayerTestObject::initialize(), EnemyTestObject::initialize(), CubeTrigger::initialize(), and FloorObject::initialize().
getShader() [2/2]
Shader& ShaderHandler::getShader (const std::string & id, const std::string & vertexPath, const std::string & fragmentPath, const SHADER_TYPE & type, const std::string & geometryPath = "") inline
Definition at line 128 of file Shader.h.
References addNewShader(), and binarySearchShaders().
Member Data Documentation
shaderLibrary
std::vector<Shader*> ShaderHandler::shaderLibrary private
Definition at line 217 of file Shader.h.
Referenced by addNewShader(), binarySearchShaders(), and ~ShaderHandler().
The documentation for this class was generated from the following file:
src/game/rendering/Shader.h