LightShow_Boilerplate: hh Namespace Reference
hh Namespace Reference
Functions
int getRandomRange (int minInclusive, int maxExclusive)
float getRandomRange (float minInclusive, float maxExclusive)
template<typename T >
bool compareFloatingPoint (T a, T b, T epsilon)
btVector3 toBtVec3 (const glm::vec3 &)
glm::quat toQuaternion (const glm::vec3 &)
glm::vec3 toGlmVec3 (const btVector3 &)
glm::quat toGlmQuat (const btQuaternion &)
template<typename T , typename A , typename B >
std::vector< T > combineVectors (std::vector< A > &v1, std::vector< B > &v2)
template<typename T , typename A >
std::vector< T > combineVectors (std::vector< A > &v1, std::vector< A > &v2)
template<typename T >
std::vector< T > combineVectors (std::vector< T > &v1, std::vector< T > &v2)
glm::quat eularToQuat (const glm::vec3 &pitchYawRoll)
float signedRadiansBetweenVectors (glm::vec3 vec1, glm::vec3 vec2)
glm::vec3 sphericalToCartisean (float theta, float phi, float radius)
bool isPointWithinCone (const glm::vec3 &coneTipPosition, const glm::vec3 &coneCenterLine, const glm::vec3 &point, const float fovRadians)
bool isPointWithinConePreCos (const glm::vec3 &coneTipPosition, const glm::vec3 &coneCenterLine, const glm::vec3 &point, const float fovRadiansPreCos)
bool isPointWithinCone (const glm::vec3 &coneTipPosition, const glm::vec3 &coneCenterLine, const glm::vec3 &point, const float fovRadians, const float withinDistance)
bool isPointWithinConePreCos (const glm::vec3 &coneTipPosition, const glm::vec3 &coneCenterLine, const glm::vec3 &point, const float fovRadiansPreCos, const float withinDistance)
template<class T >
void swapVal (T &a, T &b)
template<typename T >
T lerp (const T &a, const T &b, float t)
template<typename T >
void moveItemToBack (std::vector< T > &v, size_t itemIndex)
template<typename T >
int binarySearchVector (const std::vector< T > &sorted_vec, const T &key)
static int isPowerOfTwo (unsigned int x)
Variables
const float quadVertices [20]
const glm::vec3 UP_VECTOR = glm::vec3(0.0f, 1.0f, 0.0f)
Function Documentation
binarySearchVector()
template<typename T > int hh::binarySearchVector (const std::vector< T > & sorted_vec, const T & key)
Definition at line 144 of file HelpingHand.h.
combineVectors() [1/3]
template<typename T , typename A > std::vector<T> hh::combineVectors (std::vector< A > & v1, std::vector< A > & v2)
Definition at line 60 of file HelpingHand.h.
combineVectors() [2/3]
template<typename T , typename A , typename B > std::vector<T> hh::combineVectors (std::vector< A > & v1, std::vector< B > & v2)
Definition at line 52 of file HelpingHand.h.
combineVectors() [3/3]
template<typename T > std::vector<T> hh::combineVectors (std::vector< T > & v1, std::vector< T > & v2)
Definition at line 68 of file HelpingHand.h.
compareFloatingPoint()
template<typename T > bool hh::compareFloatingPoint (T a, T b, T epsilon)
Definition at line 42 of file HelpingHand.h.
eularToQuat()
glm::quat hh::eularToQuat (const glm::vec3 & pitchYawRoll)
Definition at line 32 of file HelpingHand.cpp.
getRandomRange() [1/2]
float hh::getRandomRange (float minInclusive, float maxExclusive)
Definition at line 7 of file HelpingHand.cpp.
getRandomRange() [2/2]
int hh::getRandomRange (int minInclusive, int maxExclusive)
Definition at line 3 of file HelpingHand.cpp.
Referenced by LightTest::initialize(), and FountainParticleSystem::setParticleToDefault().
isPointWithinCone() [1/2]
bool hh::isPointWithinCone (const glm::vec3 & coneTipPosition, const glm::vec3 & coneCenterLine, const glm::vec3 & point, const float fovRadians)
Definition at line 69 of file HelpingHand.cpp.
isPointWithinCone() [2/2]
bool hh::isPointWithinCone (const glm::vec3 & coneTipPosition, const glm::vec3 & coneCenterLine, const glm::vec3 & point, const float fovRadians, const float withinDistance)
Definition at line 85 of file HelpingHand.cpp.
isPointWithinConePreCos() [1/2]
bool hh::isPointWithinConePreCos (const glm::vec3 & coneTipPosition, const glm::vec3 & coneCenterLine, const glm::vec3 & point, const float fovRadiansPreCos)
Definition at line 81 of file HelpingHand.cpp.
isPointWithinConePreCos() [2/2]
bool hh::isPointWithinConePreCos (const glm::vec3 & coneTipPosition, const glm::vec3 & coneCenterLine, const glm::vec3 & point, const float fovRadiansPreCos, const float withinDistance)
Definition at line 94 of file HelpingHand.cpp.
isPowerOfTwo()
static int hh::isPowerOfTwo (unsigned int x) static
Definition at line 164 of file HelpingHand.h.
Referenced by TextureHandler::verifySurfaceDimensions().
lerp()
template<typename T > T hh::lerp (const T & a, const T & b, float t)
Definition at line 132 of file HelpingHand.h.
Referenced by _3DM::AnimatedModel::blendBoneTree(), and _3DM::AnimatedModel::updateBoneTree().
moveItemToBack()
template<typename T > void hh::moveItemToBack (std::vector< T > & v, size_t itemIndex)
Definition at line 137 of file HelpingHand.h.
Referenced by Messenger< BackEndMessages >::findThenRemoveMessage().
signedRadiansBetweenVectors()
float hh::signedRadiansBetweenVectors (glm::vec3 vec1, glm::vec3 vec2)
Definition at line 48 of file HelpingHand.cpp.
Referenced by PlayerControllerSystem::applyNewRotation(), and EnemyControllerSystem::applyNewTransform().
sphericalToCartisean()
glm::vec3 hh::sphericalToCartisean (float theta, float phi, float radius)
Definition at line 58 of file HelpingHand.cpp.
Referenced by DayNightCycleSystem::fixedUpdate(), and CameraSystem::update().
swapVal()
template<class T > void hh::swapVal (T & a, T & b)
Definition at line 122 of file HelpingHand.h.
Referenced by DefaultParticleSystem::fixedUpdateParticles().
toBtVec3()
btVector3 hh::toBtVec3 (const glm::vec3 & v)
Definition at line 12 of file HelpingHand.cpp.
Referenced by CollisionMesh::applyCentralImpulse(), Game::fixedUpdate(), RayCaster::RayCaster(), RayCaster::rayTest(), RayCaster::resetCallback(), CollisionMesh::setScale(), CollisionMesh::setVelocity(), and CollisionMesh::translate().
toGlmQuat()
glm::quat hh::toGlmQuat (const btQuaternion & quat)
Definition at line 24 of file HelpingHand.cpp.
Referenced by CollisionMesh::getRotation(), and CollisionMesh::getTransformation().
toGlmVec3()
glm::vec3 hh::toGlmVec3 (const btVector3 & vector)
Definition at line 20 of file HelpingHand.cpp.
Referenced by EnemyControllerSystem::executeRayTesting(), PlayerControllerSystem::executeRayTesting(), CollisionMesh::getPosition(), CollisionMesh::getScale(), CollisionMesh::getTransformation(), CollisionMesh::getVelocity(), and RayCaster::resetCallback().
toQuaternion()
glm::quat hh::toQuaternion (const glm::vec3 & vec)
Definition at line 16 of file HelpingHand.cpp.
Referenced by _3DM::AnimatedModel::overwriteRotationKeyFrames().
Variable Documentation
quadVertices
const float hh::quadVertices[20]
Initial value:
= {
    -1.0f, 1.0f, -1.0f,
    0, 1,
    -1.0f, -1.0f, -1.0f,
    0, 0,
    1.0f, 1.0f, -1.0f,
    1, 1,
    1.0f, -1.0f, -1.0f,
    1, 0
}
Definition at line 99 of file HelpingHand.h.
Referenced by Particles::initialize().
UP_VECTOR
const glm::vec3 hh::UP_VECTOR = glm::vec3(0.0f, 1.0f, 0.0f)
Definition at line 128 of file HelpingHand.h.
Referenced by DirectionalLightShadowMap::updateDepthMap().