LightShow_Boilerplate: PauseMenu Class Reference
PauseMenu Class Reference
#include <PauseMenu.h>
Public Member Functions
bool showing () const
void initialize (TextMap &map, Texture &textImage)
Public Member Functions inherited from Component< PauseMenu >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
GuiString str = GuiString(10)
GuiButton resumeButton
bool isShowing = false
float lastUnit = 0.0f
Friends
class PauseMenuSystem
Additional Inherited Members
Static Public Attributes inherited from Component< PauseMenu >
static int32_t type
Detailed Description
Definition at line 8 of file PauseMenu.h.
Member Function Documentation
initialize()
void PauseMenu::initialize (TextMap & map, Texture & textImage) inline
Definition at line 15 of file PauseMenu.h.
References Locator< TextureHandler, TextureHandler >::getService(), GuiString::initialize(), GuiSprite::initialize(), resumeButton, and str.
Referenced by Player::initialize().
showing()
bool PauseMenu::showing () const inline
Definition at line 11 of file PauseMenu.h.
References isShowing.
Friends And Related Function Documentation
PauseMenuSystem
friend class PauseMenuSystem friend
Definition at line 26 of file PauseMenu.h.
Member Data Documentation
isShowing
bool PauseMenu::isShowing = false private
Definition at line 23 of file PauseMenu.h.
Referenced by PauseMenuSystem::render(), showing(), and PauseMenuSystem::update().
lastUnit
float PauseMenu::lastUnit = 0.0f private
Definition at line 24 of file PauseMenu.h.
Referenced by PauseMenuSystem::update().
resumeButton
GuiButton PauseMenu::resumeButton private
Definition at line 22 of file PauseMenu.h.
Referenced by initialize(), PauseMenuSystem::render(), and PauseMenuSystem::update().
str
GuiString PauseMenu::str = GuiString(10) private
Definition at line 21 of file PauseMenu.h.
Referenced by initialize(), PauseMenuSystem::render(), and PauseMenuSystem::update().
The documentation for this class was generated from the following file:
src/PauseMenu.h