LightShow_Boilerplate: _3DM::_3DM_IO Class Reference
_3DM::_3DM_IO Class Reference
#include <ModelSerialization.h>
Public Member Functions
AnimatedModel readAnimatedModel (const std::string &path)
void writeAnimatedModel (AnimatedModel &model, std::ofstream &oStream)
Model readModel (const std::string &path)
void writeModel (Model &model, std::ofstream &oStream)
~_3DM_IO ()
Private Member Functions
void setIfstream (const char *path)
template<typename T , typename Func >
std::vector< T > readVector (Func func, std::ifstream &iStream)
template<typename T , typename Func >
void writeVector (Func func, std::vector< T > &items, std::ofstream &oStream)
template<typename T >
void writeGLMVec (std::ofstream &oStream, std::vector< T > &glmVec, unsigned int amount, int sizeOfElement)
template<typename T >
std::vector< T > readGLMVec (std::ifstream &iStream, unsigned int amount, int sizeOfElement)
Channel readChannel (std::ifstream &iStream)
Animation readAnimation (std::ifstream &iStream)
AnimatedMesh readAnimatedMesh (std::ifstream &iStream)
AnimationClip readAnimationClip (std::ifstream &iStream)
Mesh readMesh (std::ifstream &iStream)
void readBoneHierarchyFromFile (std::ifstream &iStream, BoneNode &futureRootNode)
void writeChannel (Channel &, std::ofstream &oStream)
void writeAnimation (Animation &animation, std::ofstream &oStream)
void writeAnimatedMesh (AnimatedMesh &mesh, std::ofstream &oStream)
void writeAnimationClip (AnimationClip &animClip, std::ofstream &oStream)
void writeBoneHierarchyToFile (BoneNode &boneNode, std::ofstream &oStream)
void writeMesh (Mesh &mesh, std::ofstream &oStream)
Private Attributes
bool isBigEndianness = false
std::ifstream iStream
Detailed Description
Definition at line 27 of file ModelSerialization.h.
Constructor & Destructor Documentation
~_3DM_IO()
_3DM::_3DM_IO::~_3DM_IO ()
Definition at line 623 of file ModelSerialization.cpp.
Member Function Documentation
readAnimatedMesh()
_3DM::AnimatedMesh _3DM::_3DM_IO::readAnimatedMesh (std::ifstream & iStream) private
Definition at line 433 of file ModelSerialization.cpp.
References _3DM::AnimatedMesh::boneIDs, _3DM::AnimatedMesh::mesh, SL::readBytes(), SL::SIZE_OF_FLOAT, and _3DM::AnimatedMesh::weights.
readAnimatedModel()
_3DM::AnimatedModel _3DM::_3DM_IO::readAnimatedModel (const std::string & path)
Definition at line 523 of file ModelSerialization.cpp.
References _3DM::AnimatedModel::animationClips, _3DM::AnimatedModel::boneIDMap, SL::isBigEndian(), _3DM::AnimatedModel::meshes, _3DM::AnimatedModel::modelLoaded, _3DM::AnimatedModel::modelsAnimation, SL::readBytes(), and _3DM::AnimatedModel::rootPath.
Referenced by _3DM::AnimatedModel::AnimatedModel().
readAnimation()
_3DM::Animation _3DM::_3DM_IO::readAnimation (std::ifstream & iStream) private
Definition at line 231 of file ModelSerialization.cpp.
References _3DM::Animation::boneOffset, _3DM::Animation::boneTransformations, _3DM::Animation::channels, _3DM::Animation::duration, _3DM::Mat_4_ROW_COL_SIZE, SL::readBytes(), _3DM::Animation::rootBone, SL::SIZE_OF_FLOAT, and _3DM::Animation::ticksPerSecond.
readAnimationClip()
_3DM::AnimationClip _3DM::_3DM_IO::readAnimationClip (std::ifstream & iStream) private
Definition at line 459 of file ModelSerialization.cpp.
References _3DM::AnimationClip::endTime, _3DM::AnimationClip::name, SL::readBytes(), SL::SIZE_OF_FLOAT, and _3DM::AnimationClip::startTime.
readBoneHierarchyFromFile()
void _3DM::_3DM_IO::readBoneHierarchyFromFile (std::ifstream & iStream, _3DM::BoneNode & futureRootNode) private
Definition at line 21 of file ModelSerialization.cpp.
References _3DM::BoneNode::children, _3DM::BoneNode::name, and SL::readBytes().
readChannel()
_3DM::Channel _3DM::_3DM_IO::readChannel (std::ifstream & iStream) private
Definition at line 124 of file ModelSerialization.cpp.
References _3DM::Channel::name, _3DM::Channel::positionKeys, SL::readBytes(), _3DM::Channel::rotationKeys, _3DM::Channel::scalingKeys, and SL::SIZE_OF_FLOAT.
readGLMVec()
template<typename T > std::vector<T> _3DM::_3DM_IO::readGLMVec (std::ifstream & iStream, unsigned int amount, int sizeOfElement) inline private
Definition at line 98 of file ModelSerialization.h.
readMesh()
_3DM::Mesh _3DM::_3DM_IO::readMesh (std::ifstream & iStream) private
Definition at line 348 of file ModelSerialization.cpp.
References _3DM::Mesh::baseModelMatrix, _3DM::Mesh::indices, _3DM::Mat_4_ROW_COL_SIZE, _3DM::Mesh::name, _3DM::Mesh::normals, SL::readBytes(), SL::SIZE_OF_FLOAT, _3DM::Mesh::textures, _3DM::Mesh::uvs, and _3DM::Mesh::vertices.
readModel()
_3DM::Model _3DM::_3DM_IO::readModel (const std::string & path)
Definition at line 598 of file ModelSerialization.cpp.
References _3DM::Model::meshes, _3DM::Model::modelLoaded, SL::readBytes(), and _3DM::Model::rootPath.
Referenced by _3DM::Model::Model().
readVector()
template<typename T , typename Func > std::vector<T> _3DM::_3DM_IO::readVector (Func func, std::ifstream & iStream) inline private
Definition at line 63 of file ModelSerialization.h.
References _3DM::DEFAULT_SIZE_OF_VECTOR, and SL::readBytes().
setIfstream()
void _3DM::_3DM_IO::setIfstream (const char * path) private
Definition at line 485 of file ModelSerialization.cpp.
writeAnimatedMesh()
void _3DM::_3DM_IO::writeAnimatedMesh (_3DM::AnimatedMesh & animatedMesh, std::ofstream & oStream) private
Definition at line 421 of file ModelSerialization.cpp.
References _3DM::AnimatedMesh::boneIDs, _3DM::AnimatedMesh::mesh, SL::SIZE_OF_FLOAT, _3DM::AnimatedMesh::weights, and SL::writeBytes().
writeAnimatedModel()
void _3DM::_3DM_IO::writeAnimatedModel (_3DM::AnimatedModel & model, std::ofstream & oStream)
Definition at line 490 of file ModelSerialization.cpp.
References _3DM::_3DMA_Signature, _3DM::AnimatedModel::animationClips, _3DM::AnimatedModel::boneIDMap, _3DM::AnimatedModel::meshes, _3DM::AnimatedModel::modelLoaded, _3DM::AnimatedModel::modelsAnimation, _3DM::AnimatedModel::rootPath, and SL::writeBytes().
writeAnimation()
void _3DM::_3DM_IO::writeAnimation (_3DM::Animation & animation, std::ofstream & oStream) private
Definition at line 194 of file ModelSerialization.cpp.
References _3DM::Animation::boneOffset, _3DM::Animation::boneTransformations, _3DM::Animation::channels, _3DM::Animation::duration, _3DM::Mat_4_ROW_COL_SIZE, _3DM::Animation::rootBone, SL::SIZE_OF_FLOAT, _3DM::Animation::ticksPerSecond, and SL::writeBytes().
writeAnimationClip()
void _3DM::_3DM_IO::writeAnimationClip (_3DM::AnimationClip & animClip, std::ofstream & oStream) private
Definition at line 449 of file ModelSerialization.cpp.
References _3DM::AnimationClip::endTime, _3DM::AnimationClip::name, SL::SIZE_OF_FLOAT, and _3DM::AnimationClip::startTime.
writeBoneHierarchyToFile()
void _3DM::_3DM_IO::writeBoneHierarchyToFile (_3DM::BoneNode & boneNode, std::ofstream & oStream) private
Definition at line 3 of file ModelSerialization.cpp.
References _3DM::BoneNode::children, _3DM::BoneNode::name, and SL::writeBytes().
writeChannel()
void _3DM::_3DM_IO::writeChannel (_3DM::Channel & channel, std::ofstream & oStream) private
Definition at line 53 of file ModelSerialization.cpp.
References _3DM::Channel::name, _3DM::Channel::positionKeys, _3DM::Channel::rotationKeys, _3DM::Channel::scalingKeys, and SL::SIZE_OF_FLOAT.
writeGLMVec()
template<typename T > void _3DM::_3DM_IO::writeGLMVec (std::ofstream & oStream, std::vector< T > & glmVec, unsigned int amount, int sizeOfElement) inline private
Definition at line 89 of file ModelSerialization.h.
writeMesh()
void _3DM::_3DM_IO::writeMesh (_3DM::Mesh & mesh, std::ofstream & oStream) private
Definition at line 297 of file ModelSerialization.cpp.
References _3DM::Mesh::baseModelMatrix, _3DM::Mesh::indices, _3DM::Mat_4_ROW_COL_SIZE, _3DM::Mesh::name, _3DM::Mesh::normals, SL::SIZE_OF_FLOAT, _3DM::Mesh::textures, _3DM::Mesh::uvs, _3DM::Mesh::vertices, and SL::writeBytes().
writeModel()
void _3DM::_3DM_IO::writeModel (_3DM::Model & model, std::ofstream & oStream)
Definition at line 588 of file ModelSerialization.cpp.
References _3DM::Model::meshes, _3DM::Model::modelLoaded, _3DM::Model::rootPath, and SL::writeBytes().
writeVector()
template<typename T , typename Func > void _3DM::_3DM_IO::writeVector (Func func, std::vector< T > & items, std::ofstream & oStream) inline private
Definition at line 79 of file ModelSerialization.h.
References _3DM::DEFAULT_SIZE_OF_VECTOR, and SL::writeBytes().
Member Data Documentation
isBigEndianness
bool _3DM::_3DM_IO::isBigEndianness = false private
Definition at line 53 of file ModelSerialization.h.
iStream
std::ifstream _3DM::_3DM_IO::iStream private
Definition at line 60 of file ModelSerialization.h.
The documentation for this class was generated from the following files:
src/ModelSerialization.h
src/ModelSerialization.cpp