LightShow_Boilerplate: GuiString Class Reference
GuiString Class Reference
#include <GuiString.h>
Public Member Functions
void initialize (TextMap &textMap, Texture &texture)
GuiString (unsigned int capacity=5, const std::string &string="")
void render (Shader &shader)
void render (Shader &shader, const std::string &string)
void render (Shader &shader, const std::string &string, unsigned int newCapacity)
void render (Shader &shader, int horizontalpad, int verticalpad=1, int spacesize=8, const glm::ivec2 &=glm::ivec2(0))
void render (Shader &shader, const std::string &string, int horizontalpad, int verticalpad=1, int spacesize=8, const glm::ivec2 &position=glm::ivec2(0))
void setTexture (Texture &texture)
void setTextMap (TextMap &textmap)
void setPosition (const glm::vec2 &position)
void setScale (const glm::vec2 &scl)
void setString (const std::string &string)
void setCapacity (unsigned int capacity)
void setHorizontalPadding (int hPadding=2)
void setVerticalPadding (int vPadding=1)
void setSpaceSize (int spacesize=8)
const std::string *const getString ()
const int getHorizontalPadding () const
const int getVerticalPadding () const
const int getSpaceSize () const
const glm::ivec2 getPosition () const
const glm::vec2 *const getScale ()
float getWidthOfString () const
Private Member Functions
void mainRender (Shader &shader)
Private Attributes
float widthOfString = 0
int horizontalPadding = 2
int verticalPadding = 1
int spaceSize = 8
glm::vec2 scale = glm::vec2(1, 1)
glm::vec2 textPosition = glm::vec2(0, 0)
Texture * currentTexture = nullptr
TextMap * currentTextMap = nullptr
std::string currentString
std::vector< GuiTextCharacter > characters
Detailed Description
Definition at line 10 of file GuiString.h.
Constructor & Destructor Documentation
GuiString()
GuiString::GuiString (unsigned int capacity = 5, const std::string & string = "")
Definition at line 8 of file GuiString.cpp.
References characters, and currentString.
Member Function Documentation
getHorizontalPadding()
const int GuiString::getHorizontalPadding () const inline
Definition at line 50 of file GuiString.h.
References horizontalPadding.
getPosition()
const glm::ivec2 GuiString::getPosition () const inline
Definition at line 62 of file GuiString.h.
References textPosition.
getScale()
const glm::vec2* const GuiString::getScale () inline
Definition at line 66 of file GuiString.h.
References scale.
getSpaceSize()
const int GuiString::getSpaceSize () const inline
Definition at line 58 of file GuiString.h.
References spaceSize.
getString()
const std::string* const GuiString::getString () inline
Definition at line 46 of file GuiString.h.
References currentString.
getVerticalPadding()
const int GuiString::getVerticalPadding () const inline
Definition at line 54 of file GuiString.h.
References verticalPadding.
getWidthOfString()
float GuiString::getWidthOfString () const inline
Definition at line 70 of file GuiString.h.
References widthOfString.
Referenced by PauseMenuSystem::render().
initialize()
void GuiString::initialize (TextMap & textMap, Texture & texture)
Definition at line 3 of file GuiString.cpp.
References currentTextMap, and currentTexture.
Referenced by DisplayStatistics::initialize(), and PauseMenu::initialize().
mainRender()
void GuiString::mainRender (Shader & shader) private
Definition at line 57 of file GuiString.cpp.
References characters, currentString, currentTextMap, currentTexture, DBG_LOG, TextMap::getGlyph(), Glyph::getHeight(), TextMap::getMaxPixelHeightOfAllGlyphs(), Glyph::getWidth(), horizontalPadding, scale, spaceSize, textPosition, verticalPadding, and widthOfString.
Referenced by render().
render() [1/5]
void GuiString::render (Shader & shader) virtual
Implements GuiBase.
Definition at line 16 of file GuiString.cpp.
References mainRender().
Referenced by DisplayStatisticsSystem::render(), and PauseMenuSystem::render().
render() [2/5]
void GuiString::render (Shader & shader, const std::string & string)
Definition at line 20 of file GuiString.cpp.
References currentString, and mainRender().
render() [3/5]
void GuiString::render (Shader & shader, const std::string & string, int horizontalpad, int verticalpad = 1, int spacesize = 8, const glm::ivec2 & position = glm::ivec2(0))
Definition at line 25 of file GuiString.cpp.
References currentString, horizontalPadding, mainRender(), spaceSize, textPosition, and verticalPadding.
render() [4/5]
void GuiString::render (Shader & shader, const std::string & string, unsigned int newCapacity)
Definition at line 42 of file GuiString.cpp.
References characters, currentString, and mainRender().
render() [5/5]
void GuiString::render (Shader & shader, int horizontalpad, int verticalpad = 1, int spacesize = 8, const glm::ivec2 & = glm::ivec2(0))
Definition at line 48 of file GuiString.cpp.
References horizontalPadding, mainRender(), spaceSize, and verticalPadding.
setCapacity()
void GuiString::setCapacity (unsigned int capacity) inline
Definition at line 41 of file GuiString.h.
References characters.
setHorizontalPadding()
void GuiString::setHorizontalPadding (int hPadding = 2) inline
Definition at line 42 of file GuiString.h.
References horizontalPadding.
setPosition()
void GuiString::setPosition (const glm::vec2 & position) inline
Definition at line 38 of file GuiString.h.
References textPosition.
Referenced by DisplayStatisticsSystem::fixedUpdate(), and PauseMenuSystem::render().
setScale()
void GuiString::setScale (const glm::vec2 & scl) inline
Definition at line 39 of file GuiString.h.
References scale.
Referenced by DisplayStatisticsSystem::fixedUpdate(), and PauseMenuSystem::update().
setSpaceSize()
void GuiString::setSpaceSize (int spacesize = 8) inline
Definition at line 44 of file GuiString.h.
References spaceSize.
setString()
void GuiString::setString (const std::string & string) inline
Definition at line 40 of file GuiString.h.
References currentString.
Referenced by DisplayStatisticsSystem::fixedUpdate().
setTextMap()
void GuiString::setTextMap (TextMap & textmap) inline
Definition at line 37 of file GuiString.h.
References currentTextMap.
setTexture()
void GuiString::setTexture (Texture & texture) inline
Definition at line 36 of file GuiString.h.
References currentTexture.
setVerticalPadding()
void GuiString::setVerticalPadding (int vPadding = 1) inline
Definition at line 43 of file GuiString.h.
References verticalPadding.
Referenced by PauseMenuSystem::render().
Member Data Documentation
characters
std::vector<GuiTextCharacter> GuiString::characters private
Definition at line 88 of file GuiString.h.
Referenced by GuiString(), mainRender(), render(), and setCapacity().
currentString
std::string GuiString::currentString private
Definition at line 87 of file GuiString.h.
Referenced by getString(), GuiString(), mainRender(), render(), and setString().
currentTextMap
TextMap* GuiString::currentTextMap = nullptr private
Definition at line 85 of file GuiString.h.
Referenced by initialize(), mainRender(), and setTextMap().
currentTexture
Texture* GuiString::currentTexture = nullptr private
Definition at line 84 of file GuiString.h.
Referenced by initialize(), mainRender(), and setTexture().
horizontalPadding
int GuiString::horizontalPadding = 2 private
Definition at line 77 of file GuiString.h.
Referenced by getHorizontalPadding(), mainRender(), render(), and setHorizontalPadding().
scale
glm::vec2 GuiString::scale = glm::vec2(1, 1) private
Definition at line 81 of file GuiString.h.
Referenced by getScale(), mainRender(), and setScale().
spaceSize
int GuiString::spaceSize = 8 private
Definition at line 79 of file GuiString.h.
Referenced by getSpaceSize(), mainRender(), render(), and setSpaceSize().
textPosition
glm::vec2 GuiString::textPosition = glm::vec2(0, 0) private
Definition at line 82 of file GuiString.h.
Referenced by getPosition(), mainRender(), render(), and setPosition().
verticalPadding
int GuiString::verticalPadding = 1 private
Definition at line 78 of file GuiString.h.
Referenced by getVerticalPadding(), mainRender(), render(), and setVerticalPadding().
widthOfString
float GuiString::widthOfString = 0 private
Definition at line 75 of file GuiString.h.
Referenced by getWidthOfString(), and mainRender().
The documentation for this class was generated from the following files:
src/GuiString.h
src/GuiString.cpp