LightShow_Boilerplate: ComponentInterface Class Reference
ComponentInterface Class Reference abstract
#include <Component.h>
Public Member Functions
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
bool active = true
int32_t ID = -1
int32_t entityID = -1
friend Scene
Detailed Description
Definition at line 12 of file Component.h.
Constructor & Destructor Documentation
~ComponentInterface()
virtual ComponentInterface::~ComponentInterface () inline virtual
Definition at line 14 of file Component.h.
Member Function Documentation
getEntityID()
int32_t ComponentInterface::getEntityID () const inline
Definition at line 16 of file Component.h.
References entityID.
Referenced by RenderingSystem::renderOthers(), and RenderingSystem::renderParticles().
getType()
virtual int32_t ComponentInterface::getType () const pure virtual
Implemented in Component< T >.
isActive()
bool ComponentInterface::isActive () const inline
Definition at line 19 of file Component.h.
References active.
Referenced by setActive().
setActive()
void ComponentInterface::setActive (bool isActive) inline
Definition at line 20 of file Component.h.
References active, and isActive().
Referenced by LightTest::initialize().
setEntityID()
void ComponentInterface::setEntityID (int32_t id) inline
Definition at line 17 of file Component.h.
References entityID.
Member Data Documentation
active
bool ComponentInterface::active = true private
Definition at line 23 of file Component.h.
Referenced by isActive(), and setActive().
entityID
int32_t ComponentInterface::entityID = -1 private
Definition at line 25 of file Component.h.
Referenced by BoneCollisionMesh::addCollider(), Scene::addComponent(), getEntityID(), and setEntityID().
ID
int32_t ComponentInterface::ID = -1 private
Definition at line 24 of file Component.h.
Referenced by Scene::addComponent().
Scene
friend ComponentInterface::Scene private
Definition at line 27 of file Component.h.
The documentation for this class was generated from the following file:
src/Component.h