LightShow_Boilerplate: Transform Struct Reference
Transform Struct Reference
#include <Transform.h>
Public Member Functions
Transform (const glm::vec3 &pstin, const glm::quat &rttn, const glm::vec3 &scl)
Transform ()
Public Attributes
glm::vec3 position = glm::vec3(0.0f, 0.0f, 0.0f)
glm::quat rotation = glm::quat(.0f, .0f, .0f, 1.0f)
glm::vec3 scale = glm::vec3(1.0f, 1.0f, 1.0f)
Detailed Description
Definition at line 4 of file Transform.h.
Constructor & Destructor Documentation
Transform() [1/2]
Transform::Transform (const glm::vec3 & pstin, const glm::quat & rttn, const glm::vec3 & scl) inline
Definition at line 5 of file Transform.h.
References position, rotation, and scale.
Transform() [2/2]
Transform::Transform () inline
Definition at line 10 of file Transform.h.
Member Data Documentation
position
glm::vec3 Transform::position = glm::vec3(0.0f, 0.0f, 0.0f)
Definition at line 12 of file Transform.h.
Referenced by EnemyControllerSystem::applyNewTransform(), PlayerControllerSystem::applyNewTransform(), EnemyControllerSystem::executeRayTesting(), PlayerControllerSystem::executeRayTesting(), BoneCollisionMeshSystem::fixedUpdate(), PlayerCameraHandlingSystem::setThirdPersonCameraTargetPosition(), Transform(), and FixedUpdatingSystem::updateCollision().
rotation
glm::quat Transform::rotation = glm::quat(.0f, .0f, .0f, 1.0f)
Definition at line 14 of file Transform.h.
Referenced by PlayerControllerSystem::applyNewRotation(), EnemyControllerSystem::applyNewTransform(), BoneCollisionMeshSystem::fixedUpdate(), Transform(), and EnemyControllerSystem::update().
scale
glm::vec3 Transform::scale = glm::vec3(1.0f, 1.0f, 1.0f)
Definition at line 16 of file Transform.h.
Referenced by BoneCollisionMeshSystem::fixedUpdate(), and Transform().
The documentation for this struct was generated from the following file:
src/Transform.h