LightShow_Boilerplate: _3DM::AnimatedModel Class Reference
_3DM::AnimatedModel Class Reference
The AnimatedModel controls the lifecycle of a 3D Animated Model. This includes init, rendering, and freeing the data to render the AnimatedModel.
#include <AnimatedModel.h>
Classes
struct InterpolatedFrame
Used to interpolate two frames for smooth animation transitions.
Public Member Functions
AnimatedModel (const std::string &path)
~AnimatedModel ()
void initialize (Shader &shader)
Initializes the model. Should be called before rendering.
glm::mat4 getMeshMatrix (unsigned int index) const
Retrieves matrix of mesh at index.
int getMeshIndex (const std::string &MeshName) const
Retrieves the index of a mesh via mesh name.
int getAnimationIndex (const std::string &name) const
Retrieves animation index of Model via animations name.
int getChannelIndex (const std::string &channelName) const
Retrieves animation's channel index via channel's name.
int getBoneID (const std::string &nodeName) const
Retrieves id of bone via bones name.
std::string getBoneName (uint32_t id) const
Retrieves bone name via bone's id.
int amountOfAnimations () const
Returns amount of animations for the animated model.
glm::mat4 getBoneTransformation (unsigned int boneId) const
Returns the current transform of the bone.
glm::mat4 getBoneTransformationWithoutOffset (unsigned int boneId) const
Returns the current transform of the bone, without bone's offset matrix.
glm::mat4 getBoneTransformationWithoutOffset (const std::string &name) const
Returns the current transform of the bone via bone name, without bone's offset matrix.
unsigned int amountOfBones () const
Returns the amount of bones in the animated model.
unsigned int amountOfMeshes () const
Returns the amount of meshes in the animated model.
std::vector< glm::vec3 > * getMeshVertices (unsigned int index)
Retrieves vertices of mesh at index.
std::vector< uint32_t > * getMeshIndices (unsigned int index)
Retrieves indices of mesh at index.
void setMeshMatrix (unsigned int index, const glm::mat4 &newMatrix)
Sets matrix of mesh at index.
void setBoneMatrix (const glm::mat4 &transformation, unsigned int boneId)
Sets matrix of a bone at index.
void setAnimationClip (unsigned int clip)
Sets the current animation clip to be ran.
void addTexture (const Texture &texture, int meshIndex, const _3DM::TextureType &type)
Used to add a texture manually to a mesh.
void fixedUpdateAnimation ()
Updates the animation a single frame.
void renderAll (Shader &shader)
Renders all meshes in model.
void renderSingleMesh (unsigned int index, Shader &shader)
Renders a mesh at index.
void removeKeyframes (unsigned int channelIndex)
Removes a channel via it's index.
void addRotationToKeyFrames (const glm::quat &rotation, unsigned int channelIndex)
Add rotation to a channel.
void addRotationToKeyFrames (const glm::vec3 &rotation, unsigned int channelIndex)
Add rotation to a channel.
void overwriteRotationKeyFrames (const glm::vec3 &rotation, unsigned int channelIndex)
Overwrite rotation of a channel.
void overwriteRotationKeyFrames (const glm::quat &rotation, unsigned int channelIndex)
Overwrite rotation of a channel.
void addScaleToKeyFrames (const glm::vec3 &scale, unsigned int channelIndex)
Add scale to a channel.
void overwriteScaleKeyFrames (const glm::vec3 &scale, unsigned int channelIndex)
Overwrite scale of a channel.
void addPositionToKeyFrames (const glm::vec3 &position, unsigned int channelIndex)
Add position to a channel.
void overWritePositionToKeyFrames (const glm::vec3 &position, unsigned int channelIndex)
Overwrite position of a channel.
void setBlendingTime (const float newTime)
Set's amount of time it takes to interpolate one animation to another.
Public Member Functions inherited from Component< AnimatedModel >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Public Member Functions inherited from ModelBase
virtual ~ModelBase ()
bool isAnimatedModel ()
Private Member Functions
template<typename T >
InterpolatedFrame getKeyframesAtTime (std::vector< T > &keys, float currentTime)
Returns interpolated keyframes at a given time.
template<typename T >
unsigned int getNearestFrameAtTime (std::vector< T > &keys, float currentTime)
Retrieves the nearest keyframe based on the current time.
void initializeBuffers (Mesh &mesh, Shader &shader)
Initializes the buffers for a mesh.
void initializeTexture (Mesh &mesh, Shader &shader)
Initializes the textures for a mesh.
void renderMesh (unsigned int index, Shader &shader)
Renders a mesh at index.
void initializeBoneBuffers (AnimatedMesh &mesh, Shader &shader)
Initializes the bone buffers for a mesh.
void updateBoneTree (const float &timeInTicks, BoneNode *node, const glm::mat4 &parentTransform)
This function will recursively update the bonetree according to the time given. it will also interpolate properly between each keyframe.
void blendBoneTree (const float &lastAnimationTime, _3DM::BoneNode *node, const glm::mat4 &parentTransform)
This function will recursively blend the bonetree according to the time given. it will also interpolate properly between each keyframe.
void bindBuffers (Shader &shader, AnimatedMesh &mesh)
Bind's buffers before rendering.
AnimatedModel ()
Private Attributes
Animation modelsAnimation
The animation of the model.
std::vector< AnimatedMesh > meshes
The meshes of the model.
std::map< std::string, uint32_t > boneIDMap
The boneId's mapped to the bone name.
uint16_t currentAnimationClip = 0
uint16_t lastAnimationClip = 0
float timeSinceAnimationStarted = 0
float blendingTime = .1f
float currentBlendingTime = 0
float blendingLastFrameTime = 0
uint16_t blendinglastAnimationClip = 0
std::vector< AnimationClip > animationClips
Animation clips for the AnimatedModel.
std::string rootPath
bool modelLoaded = false
bool initialized = false
Friends
class _3DM::_3DM_IO
Additional Inherited Members
Public Attributes inherited from ModelBase
Transform transform
Static Public Attributes inherited from Component< AnimatedModel >
static int32_t type
Protected Attributes inherited from ModelBase
bool animatedModel = false
Detailed Description
The AnimatedModel controls the lifecycle of a 3D Animated Model. This includes init, rendering, and freeing the data to render the AnimatedModel.
Definition at line 21 of file AnimatedModel.h.
Constructor & Destructor Documentation
AnimatedModel() [1/2]
_3DM::AnimatedModel::AnimatedModel (const std::string & path)
Definition at line 93 of file AnimatedModel.cpp.
References _3DM::_3DM_IO::readAnimatedModel().
~AnimatedModel()
_3DM::AnimatedModel::~AnimatedModel ()
Definition at line 71 of file AnimatedModel.cpp.
References _3DM::AnimatedMesh::boneIDsBufferObject, DBG_LOG, _3DM::Mesh::elementBufferObject, _3DM::AnimatedMesh::mesh, _3DM::Mesh::normalBufferObject, _3DM::Mesh::uvBufferObject, _3DM::Mesh::vertexArrayObject, _3DM::Mesh::vertexBufferObject, and _3DM::AnimatedMesh::weightsBufferObject.
AnimatedModel() [2/2]
_3DM::AnimatedModel::AnimatedModel () inline private
Definition at line 209 of file AnimatedModel.h.
Member Function Documentation
addPositionToKeyFrames()
void _3DM::AnimatedModel::addPositionToKeyFrames (const glm::vec3 & position, unsigned int channelIndex)
Add position to a channel.
Definition at line 36 of file AnimatedModel.cpp.
References DBG_LOG.
addRotationToKeyFrames() [1/2]
void _3DM::AnimatedModel::addRotationToKeyFrames (const glm::quat & rotation, unsigned int channelIndex)
Add rotation to a channel.
Definition at line 119 of file AnimatedModel.cpp.
References DBG_LOG.
addRotationToKeyFrames() [2/2]
void _3DM::AnimatedModel::addRotationToKeyFrames (const glm::vec3 & rotation, unsigned int channelIndex)
Add rotation to a channel.
Definition at line 129 of file AnimatedModel.cpp.
References DBG_LOG.
addScaleToKeyFrames()
void _3DM::AnimatedModel::addScaleToKeyFrames (const glm::vec3 & scale, unsigned int channelIndex)
Add scale to a channel.
Definition at line 9 of file AnimatedModel.cpp.
References DBG_LOG.
addTexture()
void _3DM::AnimatedModel::addTexture (const Texture & texture, int meshIndex, const _3DM::TextureType & type)
Used to add a texture manually to a mesh.
Definition at line 230 of file AnimatedModel.cpp.
References DBG_LOG, _3DM::Diffuse, _3DM::Mesh::diffuseIndex, Shaders::DiffuseTexture, Texture::getLocation(), Texture::getTextureData(), Shaders::getUniformName(), _3DM::ModelTexture::imageID, _3DM::ModelTexture::imagePath, _3DM::ModelTexture::imageType, _3DM::AnimatedMesh::mesh, _3DM::Normals, _3DM::Mesh::normalsIndex, Shaders::NormalTexture, _3DM::Specular, _3DM::Mesh::specularIndex, Shaders::SpecularTexture, _3DM::Mesh::textures, and _3DM::ModelTexture::uniformName.
Referenced by PlayerTestObject::initialize().
amountOfAnimations()
int _3DM::AnimatedModel::amountOfAnimations () const inline
Returns amount of animations for the animated model.
Definition at line 49 of file AnimatedModel.h.
References animationClips.
amountOfBones()
unsigned int _3DM::AnimatedModel::amountOfBones () const inline
Returns the amount of bones in the animated model.
Definition at line 61 of file AnimatedModel.h.
References _3DM::Animation::boneTransformations, and modelsAnimation.
amountOfMeshes()
unsigned int _3DM::AnimatedModel::amountOfMeshes () const inline
Returns the amount of meshes in the animated model.
Definition at line 64 of file AnimatedModel.h.
References meshes.
Referenced by CollisionMesh::createTriangleMeshCollider(), CollisionMesh::createTriangleModelCollider(), PlayerTestObject::initialize(), and EnemyTestObject::initialize().
bindBuffers()
void _3DM::AnimatedModel::bindBuffers (Shader & shader, AnimatedMesh & mesh) private
Bind's buffers before rendering.
Definition at line 611 of file AnimatedModel.cpp.
References _3DM::AnimatedMesh::boneIDs, Shaders::BoneIDS, _3DM::AnimatedMesh::boneIDsBufferObject, Shaders::BoneWeights, Shaders::getAttribLocation(), _3DM::AnimatedMesh::weights, and _3DM::AnimatedMesh::weightsBufferObject.
blendBoneTree()
void _3DM::AnimatedModel::blendBoneTree (const float & lastAnimationTime, _3DM::BoneNode * node, const glm::mat4 & parentTransform) private
This function will recursively blend the bonetree according to the time given. it will also interpolate properly between each keyframe.
Definition at line 449 of file AnimatedModel.cpp.
References _3DM::BoneNode::children, _3DM::AnimatedModel::InterpolatedFrame::firstFrame, _3DM::AnimatedModel::InterpolatedFrame::interpolation, _3DM::AnimatedModel::InterpolatedFrame::lastFrame, hh::lerp(), and _3DM::BoneNode::name.
fixedUpdateAnimation()
void _3DM::AnimatedModel::fixedUpdateAnimation ()
Updates the animation a single frame.
Definition at line 266 of file AnimatedModel.cpp.
References GameInfo::fixedDeltaTime.
getAnimationIndex()
int _3DM::AnimatedModel::getAnimationIndex (const std::string & name) const
Retrieves animation index of Model via animations name.
Definition at line 329 of file AnimatedModel.cpp.
getBoneID()
int _3DM::AnimatedModel::getBoneID (const std::string & nodeName) const
Retrieves id of bone via bones name.
Definition at line 339 of file AnimatedModel.cpp.
getBoneName()
std::string _3DM::AnimatedModel::getBoneName (uint32_t id) const
Retrieves bone name via bone's id.
Definition at line 348 of file AnimatedModel.cpp.
References DBG_LOG.
getBoneTransformation()
glm::mat4 _3DM::AnimatedModel::getBoneTransformation (unsigned int boneId) const
Returns the current transform of the bone.
Definition at line 174 of file AnimatedModel.cpp.
References DBG_LOG.
getBoneTransformationWithoutOffset() [1/2]
glm::mat4 _3DM::AnimatedModel::getBoneTransformationWithoutOffset (const std::string & name) const
Returns the current transform of the bone via bone name, without bone's offset matrix.
Definition at line 193 of file AnimatedModel.cpp.
getBoneTransformationWithoutOffset() [2/2]
glm::mat4 _3DM::AnimatedModel::getBoneTransformationWithoutOffset (unsigned int boneId) const
Returns the current transform of the bone, without bone's offset matrix.
Definition at line 183 of file AnimatedModel.cpp.
Referenced by BoneCollisionMeshSystem::fixedUpdate().
getChannelIndex()
int _3DM::AnimatedModel::getChannelIndex (const std::string & channelName) const
Retrieves animation's channel index via channel's name.
Definition at line 359 of file AnimatedModel.cpp.
getKeyframesAtTime()
template<typename T > InterpolatedFrame _3DM::AnimatedModel::getKeyframesAtTime (std::vector< T > & keys, float currentTime) inline private
Returns interpolated keyframes at a given time.
Definition at line 138 of file AnimatedModel.h.
References _3DM::AnimatedModel::InterpolatedFrame::firstFrame, _3DM::AnimatedModel::InterpolatedFrame::interpolation, and _3DM::AnimatedModel::InterpolatedFrame::lastFrame.
Referenced by getNearestFrameAtTime().
getMeshIndex()
int _3DM::AnimatedModel::getMeshIndex (const std::string & MeshName) const
Retrieves the index of a mesh via mesh name.
Definition at line 296 of file AnimatedModel.cpp.
getMeshIndices()
std::vector< uint32_t > * _3DM::AnimatedModel::getMeshIndices (unsigned int index)
Retrieves indices of mesh at index.
Definition at line 215 of file AnimatedModel.cpp.
Referenced by CollisionMesh::createTriangleMeshCollider(), and CollisionMesh::createTriangleModelCollider().
getMeshMatrix()
glm::mat4 _3DM::AnimatedModel::getMeshMatrix (unsigned int index) const
Retrieves matrix of mesh at index.
Definition at line 103 of file AnimatedModel.cpp.
References DBG_LOG.
getMeshVertices()
std::vector< glm::vec3 > * _3DM::AnimatedModel::getMeshVertices (unsigned int index)
Retrieves vertices of mesh at index.
Definition at line 208 of file AnimatedModel.cpp.
Referenced by CollisionMesh::createTriangleMeshCollider(), and CollisionMesh::createTriangleModelCollider().
getNearestFrameAtTime()
template<typename T > unsigned int _3DM::AnimatedModel::getNearestFrameAtTime (std::vector< T > & keys, float currentTime) inline private
Retrieves the nearest keyframe based on the current time.
Definition at line 154 of file AnimatedModel.h.
References _3DM::AnimatedModel::InterpolatedFrame::firstFrame, getKeyframesAtTime(), _3DM::AnimatedModel::InterpolatedFrame::interpolation, and _3DM::AnimatedModel::InterpolatedFrame::lastFrame.
initialize()
void _3DM::AnimatedModel::initialize (Shader & shader) virtual
Initializes the model. Should be called before rendering.
Implements ModelBase.
Definition at line 57 of file AnimatedModel.cpp.
initializeBoneBuffers()
void _3DM::AnimatedModel::initializeBoneBuffers (_3DM::AnimatedMesh & mesh, Shader & shader) private
Initializes the bone buffers for a mesh.
Definition at line 604 of file AnimatedModel.cpp.
References _3DM::AnimatedMesh::boneIDsBufferObject, and _3DM::AnimatedMesh::weightsBufferObject.
initializeBuffers()
void _3DM::AnimatedModel::initializeBuffers (_3DM::Mesh & mesh, Shader & shader) private
Initializes the buffers for a mesh.
Definition at line 666 of file AnimatedModel.cpp.
References _3DM::Mesh::elementBufferObject, Shaders::getAttribLocation(), _3DM::Mesh::indices, Shaders::Normal, _3DM::Mesh::normalBufferObject, _3DM::Mesh::normals, Shaders::Position, Shaders::TextureCoordinates, _3DM::Mesh::uvBufferObject, _3DM::Mesh::uvs, _3DM::Mesh::vertexArrayObject, _3DM::Mesh::vertexBufferObject, and _3DM::Mesh::vertices.
initializeTexture()
void _3DM::AnimatedModel::initializeTexture (_3DM::Mesh & mesh, Shader & shader) private
Initializes the textures for a mesh.
Definition at line 626 of file AnimatedModel.cpp.
References _3DM::Diffuse, _3DM::Mesh::diffuseIndex, Shaders::DiffuseTexture, Locator< TextureHandler, TextureHandler >::getService(), TextureHandler::getTexture(), Texture::getTextureData(), Shaders::getUniformName(), _3DM::Normals, _3DM::Mesh::normalsIndex, Shaders::NormalTexture, _3DM::Specular, _3DM::Mesh::specularIndex, Shaders::SpecularTexture, and _3DM::Mesh::textures.
overWritePositionToKeyFrames()
void _3DM::AnimatedModel::overWritePositionToKeyFrames (const glm::vec3 & position, unsigned int channelIndex)
Overwrite position of a channel.
Definition at line 47 of file AnimatedModel.cpp.
References DBG_LOG.
overwriteRotationKeyFrames() [1/2]
void _3DM::AnimatedModel::overwriteRotationKeyFrames (const glm::quat & rotation, unsigned int channelIndex)
Overwrite rotation of a channel.
Definition at line 164 of file AnimatedModel.cpp.
References DBG_LOG.
overwriteRotationKeyFrames() [2/2]
void _3DM::AnimatedModel::overwriteRotationKeyFrames (const glm::vec3 & rotation, unsigned int channelIndex)
Overwrite rotation of a channel.
Definition at line 150 of file AnimatedModel.cpp.
References DBG_LOG, and hh::toQuaternion().
overwriteScaleKeyFrames()
void _3DM::AnimatedModel::overwriteScaleKeyFrames (const glm::vec3 & scale, unsigned int channelIndex)
Overwrite scale of a channel.
Definition at line 22 of file AnimatedModel.cpp.
References DBG_LOG.
removeKeyframes()
void _3DM::AnimatedModel::removeKeyframes (unsigned int channelIndex)
Removes a channel via it's index.
Definition at line 3 of file AnimatedModel.cpp.
References _3DM::Animation::channels, and modelsAnimation.
renderAll()
void _3DM::AnimatedModel::renderAll (Shader & shader) virtual
Renders all meshes in model.
Implements ModelBase.
Definition at line 591 of file AnimatedModel.cpp.
References DBG_LOG.
renderMesh()
void _3DM::AnimatedModel::renderMesh (unsigned int index, Shader & shader) private
Renders a mesh at index.
Definition at line 549 of file AnimatedModel.cpp.
References Shaders::BoneTransformations, Shader::getProgramID(), Shaders::getUniformLocation(), and Shaders::ModelMatrix.
renderSingleMesh()
void _3DM::AnimatedModel::renderSingleMesh (unsigned int index, Shader & shader) virtual
Renders a mesh at index.
Implements ModelBase.
Definition at line 305 of file AnimatedModel.cpp.
References DBG_LOG.
setAnimationClip()
void _3DM::AnimatedModel::setAnimationClip (unsigned int clip)
Sets the current animation clip to be ran.
Definition at line 317 of file AnimatedModel.cpp.
References DBG_LOG.
Referenced by PlayerTestObject::initialize(), EnemyTestObject::initialize(), and FixedUpdatingSystem::updateCollision().
setBlendingTime()
void _3DM::AnimatedModel::setBlendingTime (const float newTime) inline
Set's amount of time it takes to interpolate one animation to another.
Definition at line 121 of file AnimatedModel.h.
References blendingTime.
setBoneMatrix()
void _3DM::AnimatedModel::setBoneMatrix (const glm::mat4 & transformation, unsigned int boneId)
Sets matrix of a bone at index.
Definition at line 222 of file AnimatedModel.cpp.
References DBG_LOG.
setMeshMatrix()
void _3DM::AnimatedModel::setMeshMatrix (unsigned int index, const glm::mat4 & newMatrix)
Sets matrix of mesh at index.
Definition at line 113 of file AnimatedModel.cpp.
Referenced by PlayerTestObject::initialize(), and EnemyTestObject::initialize().
updateBoneTree()
void _3DM::AnimatedModel::updateBoneTree (const float & timeInTicks, _3DM::BoneNode * node, const glm::mat4 & parentTransform) private
This function will recursively update the bonetree according to the time given. it will also interpolate properly between each keyframe.
Definition at line 372 of file AnimatedModel.cpp.
References _3DM::BoneNode::children, _3DM::AnimatedModel::InterpolatedFrame::firstFrame, _3DM::AnimatedModel::InterpolatedFrame::interpolation, _3DM::AnimatedModel::InterpolatedFrame::lastFrame, hh::lerp(), and _3DM::BoneNode::name.
Friends And Related Function Documentation
_3DM::_3DM_IO
friend class _3DM::_3DM_IO friend
Definition at line 210 of file AnimatedModel.h.
Member Data Documentation
animationClips
std::vector<AnimationClip> _3DM::AnimatedModel::animationClips private
Animation clips for the AnimatedModel.
Definition at line 203 of file AnimatedModel.h.
Referenced by amountOfAnimations(), _3DM::_3DM_IO::readAnimatedModel(), and _3DM::_3DM_IO::writeAnimatedModel().
blendinglastAnimationClip
uint16_t _3DM::AnimatedModel::blendinglastAnimationClip = 0 private
Definition at line 200 of file AnimatedModel.h.
blendingLastFrameTime
float _3DM::AnimatedModel::blendingLastFrameTime = 0 private
Definition at line 199 of file AnimatedModel.h.
blendingTime
float _3DM::AnimatedModel::blendingTime = .1f private
Definition at line 197 of file AnimatedModel.h.
Referenced by setBlendingTime().
boneIDMap
std::map<std::string, uint32_t> _3DM::AnimatedModel::boneIDMap private
The boneId's mapped to the bone name.
Definition at line 192 of file AnimatedModel.h.
Referenced by _3DM::_3DM_IO::readAnimatedModel(), and _3DM::_3DM_IO::writeAnimatedModel().
currentAnimationClip
uint16_t _3DM::AnimatedModel::currentAnimationClip = 0 private
Definition at line 194 of file AnimatedModel.h.
currentBlendingTime
float _3DM::AnimatedModel::currentBlendingTime = 0 private
Definition at line 198 of file AnimatedModel.h.
initialized
bool _3DM::AnimatedModel::initialized = false private
Definition at line 207 of file AnimatedModel.h.
lastAnimationClip
uint16_t _3DM::AnimatedModel::lastAnimationClip = 0 private
Definition at line 195 of file AnimatedModel.h.
meshes
std::vector<AnimatedMesh> _3DM::AnimatedModel::meshes private
The meshes of the model.
Definition at line 189 of file AnimatedModel.h.
Referenced by amountOfMeshes(), _3DM::_3DM_IO::readAnimatedModel(), and _3DM::_3DM_IO::writeAnimatedModel().
modelLoaded
bool _3DM::AnimatedModel::modelLoaded = false private
Definition at line 206 of file AnimatedModel.h.
Referenced by _3DM::_3DM_IO::readAnimatedModel(), and _3DM::_3DM_IO::writeAnimatedModel().
modelsAnimation
Animation _3DM::AnimatedModel::modelsAnimation private
The animation of the model.
Definition at line 186 of file AnimatedModel.h.
Referenced by amountOfBones(), _3DM::_3DM_IO::readAnimatedModel(), removeKeyframes(), and _3DM::_3DM_IO::writeAnimatedModel().
rootPath
std::string _3DM::AnimatedModel::rootPath private
Definition at line 205 of file AnimatedModel.h.
Referenced by _3DM::_3DM_IO::readAnimatedModel(), and _3DM::_3DM_IO::writeAnimatedModel().
timeSinceAnimationStarted
float _3DM::AnimatedModel::timeSinceAnimationStarted = 0 private
Definition at line 196 of file AnimatedModel.h.
The documentation for this class was generated from the following files:
src/AnimatedModel.h
src/AnimatedModel.cpp