LightShow_Boilerplate: PhysicsWorld Class Reference
PhysicsWorld Class Reference
#include <PhysicsWorld.h>
Public Member Functions
PhysicsWorld (const btVector3 &gravity)
btDiscreteDynamicsWorld * getWorld () const
~PhysicsWorld ()
void initialize ()
void fixedUpdate ()
void setDebugMode (btIDebugDraw::DebugDrawModes mode)
void debugDraw (const glm::mat4 &projectionMatrix, const glm::mat4 &viewMatrix)
void addRigidBody (const CollisionMesh &collisionMesh)
void removeRigidBody (const CollisionMesh &collisionMesh)
void removeAllRigidBodies ()
void setDebugDrawing (bool b)
bool isDebugDrawing ()
Engine::DebugDrawer & getDebugDrawer ()
Private Member Functions
void initializeDebugDraw ()
Private Attributes
bool shouldDebugDraw = false
std::vector< btRigidBody * > rigidBodies
std::vector< btCollisionShape * > shapes
Engine::DebugDrawer debugDrawer
btBroadphaseInterface * broadphase = nullptr
btDefaultCollisionConfiguration * collisionConfiguration = nullptr
btCollisionDispatcher * dispatcher = nullptr
btSequentialImpulseConstraintSolver * solver = nullptr
btDiscreteDynamicsWorld * thisWorld = nullptr
Detailed Description
Definition at line 10 of file PhysicsWorld.h.
Constructor & Destructor Documentation
PhysicsWorld()
PhysicsWorld::PhysicsWorld (const btVector3 & gravity)
Definition at line 3 of file PhysicsWorld.cpp.
References broadphase, collisionConfiguration, dispatcher, solver, and thisWorld.
~PhysicsWorld()
PhysicsWorld::~PhysicsWorld ()
Definition at line 17 of file PhysicsWorld.cpp.
References broadphase, collisionConfiguration, DBG_CHECK, dispatcher, removeAllRigidBodies(), solver, and thisWorld.
Member Function Documentation
addRigidBody()
void PhysicsWorld::addRigidBody (const CollisionMesh & collisionMesh)
Definition at line 89 of file PhysicsWorld.cpp.
References DBG_CHECK, CollisionMesh::getRigidBody(), CollisionMesh::isKinematic(), CollisionMesh::isTrigger(), rigidBodies, and thisWorld.
debugDraw()
void PhysicsWorld::debugDraw (const glm::mat4 & projectionMatrix, const glm::mat4 & viewMatrix)
Definition at line 76 of file PhysicsWorld.cpp.
References debugDrawer, Engine::DebugDrawer::render(), and thisWorld.
Referenced by DebuggingSystem::executeDebugRendering().
fixedUpdate()
void PhysicsWorld::fixedUpdate ()
Definition at line 35 of file PhysicsWorld.cpp.
References CollisionTag::collidingWith, DBG_LOG, GameInfo::fixedDeltaTime, GameInfo::MAX_COLLISION_TRIGGERS_AT_ONCE, GameInfo::PHYSICS_MAX_SUBSTEPS, GameInfo::PHYSICS_TIME_STEP, and thisWorld.
Referenced by FixedUpdatingSystem::fixedUpdate().
getDebugDrawer()
Engine::DebugDrawer& PhysicsWorld::getDebugDrawer () inline
Definition at line 40 of file PhysicsWorld.h.
References debugDrawer.
Referenced by PlayerControllerSystem::debugRender(), and DayNightCycleSystem::debugRender().
getWorld()
btDiscreteDynamicsWorld* PhysicsWorld::getWorld () const inline
Definition at line 15 of file PhysicsWorld.h.
References thisWorld.
Referenced by PlayerControllerSystem::executeRayTesting(), and EnemyControllerSystem::executeRayTesting().
initialize()
void PhysicsWorld::initialize ()
Definition at line 31 of file PhysicsWorld.cpp.
References initializeDebugDraw().
initializeDebugDraw()
void PhysicsWorld::initializeDebugDraw () private
Definition at line 81 of file PhysicsWorld.cpp.
References debugDrawer, Engine::DebugDrawer::initialize(), Engine::DebugDrawer::setDebugMode(), and thisWorld.
Referenced by initialize().
isDebugDrawing()
bool PhysicsWorld::isDebugDrawing () inline
Definition at line 36 of file PhysicsWorld.h.
References shouldDebugDraw.
Referenced by DebuggingSystem::controlPhysicsDebugDraw(), PlayerControllerSystem::debugRender(), DayNightCycleSystem::debugRender(), and DebuggingSystem::executeDebugRendering().
removeAllRigidBodies()
void PhysicsWorld::removeAllRigidBodies ()
Definition at line 116 of file PhysicsWorld.cpp.
References DBG_CHECK, rigidBodies, and thisWorld.
Referenced by ~PhysicsWorld().
removeRigidBody()
void PhysicsWorld::removeRigidBody (const CollisionMesh & collisionMesh)
Definition at line 105 of file PhysicsWorld.cpp.
References DBG_CHECK, CollisionMesh::getRigidBody(), rigidBodies, and thisWorld.
setDebugDrawing()
void PhysicsWorld::setDebugDrawing (bool b) inline
Definition at line 33 of file PhysicsWorld.h.
References shouldDebugDraw.
Referenced by DebuggingSystem::controlPhysicsDebugDraw().
setDebugMode()
void PhysicsWorld::setDebugMode (btIDebugDraw::DebugDrawModes mode)
Definition at line 72 of file PhysicsWorld.cpp.
References debugDrawer, and Engine::DebugDrawer::setDebugMode().
Member Data Documentation
broadphase
btBroadphaseInterface* PhysicsWorld::broadphase = nullptr private
Definition at line 53 of file PhysicsWorld.h.
Referenced by PhysicsWorld(), and ~PhysicsWorld().
collisionConfiguration
btDefaultCollisionConfiguration* PhysicsWorld::collisionConfiguration = nullptr private
Definition at line 54 of file PhysicsWorld.h.
Referenced by PhysicsWorld(), and ~PhysicsWorld().
debugDrawer
Engine::DebugDrawer PhysicsWorld::debugDrawer private
Definition at line 52 of file PhysicsWorld.h.
Referenced by debugDraw(), getDebugDrawer(), initializeDebugDraw(), and setDebugMode().
dispatcher
btCollisionDispatcher* PhysicsWorld::dispatcher = nullptr private
Definition at line 55 of file PhysicsWorld.h.
Referenced by PhysicsWorld(), and ~PhysicsWorld().
rigidBodies
std::vector<btRigidBody*> PhysicsWorld::rigidBodies private
Definition at line 49 of file PhysicsWorld.h.
Referenced by addRigidBody(), removeAllRigidBodies(), and removeRigidBody().
shapes
std::vector<btCollisionShape*> PhysicsWorld::shapes private
Definition at line 50 of file PhysicsWorld.h.
shouldDebugDraw
bool PhysicsWorld::shouldDebugDraw = false private
Definition at line 47 of file PhysicsWorld.h.
Referenced by isDebugDrawing(), and setDebugDrawing().
solver
btSequentialImpulseConstraintSolver* PhysicsWorld::solver = nullptr private
Definition at line 56 of file PhysicsWorld.h.
Referenced by PhysicsWorld(), and ~PhysicsWorld().
thisWorld
btDiscreteDynamicsWorld* PhysicsWorld::thisWorld = nullptr private
Definition at line 57 of file PhysicsWorld.h.
Referenced by addRigidBody(), debugDraw(), fixedUpdate(), getWorld(), initializeDebugDraw(), PhysicsWorld(), removeAllRigidBodies(), removeRigidBody(), and ~PhysicsWorld().
The documentation for this class was generated from the following files:
src/engine/physics/PhysicsWorld.h
src/engine/physics/PhysicsWorld.cpp