LightShow_Boilerplate: Engine::Application Class Reference
Engine::Application Class Reference
The Application class manages important tasks like creating a Game, managing the Window and Locators (single instance services) such as Input, Textures, Audio, and Shaders.
#include <Application.h>
Public Member Functions
void run ()
Private Member Functions
void fixedUpdate ()
For Fixed updating - generally physics. Capped to run at GameInfo::fixedDeltaTime.
void update ()
For updating- generally user input or ai.
void render ()
For Rendering.
void initialize ()
For Initializing everything.
void uninitialize ()
For Uninitializing everything.
void initializeGL ()
For initializing openGL.
void initializeSDL ()
For initializing SDL2.
void initializeAudio ()
For initializing audio (SDL_Mixer)
Private Attributes
SDL_Event sdlEventSystem
const unsigned int AUDIO_RATE = 44100
Audio Rate.(frequency) 22050 for LQ sound (faster) 44100 for HQ sound.
const unsigned int AUDIO_CHANNEL = 1
Audio Channel 2 for sterio, 1 for mono.
const unsigned int AUDIO_BUFFER = 256
Audio Bufffer (chunk size) Bytes used per output sample.
const unsigned short AUDIO_FORMAT = AUDIO_U8
Audio Format signed 8-bit samples, in system byte order. Same as AUDIO_S16SYS.
const glm::vec4 SCREEN_COLOR = glm::vec4(.8f, .9f, .95f, 1.f)
The default color of the screen.
Input inputService
SoundHandler soundService
MusicHandler musicService
TextureHandler textureService
ShaderHandler shaderService
Time currentTime
Manages time.
Messenger< BackEndMessages > backEndMessagingSystem
Manages BackEndMessages to send to Game.
Game thisGame
We run the game with this!
Detailed Description
The Application class manages important tasks like creating a Game, managing the Window and Locators (single instance services) such as Input, Textures, Audio, and Shaders.
Definition at line 30 of file Application.h.
Member Function Documentation
fixedUpdate()
void Application::fixedUpdate () private
For Fixed updating - generally physics. Capped to run at GameInfo::fixedDeltaTime.
Definition at line 164 of file Application.cpp.
References Engine::Game::fixedUpdate(), and thisGame.
initialize()
void Application::initialize () private
For Initializing everything.
Definition at line 143 of file Application.cpp.
References backEndMessagingSystem, currentTime, Engine::Game::initialize(), Time::initialize(), initializeAudio(), initializeGL(), initializeSDL(), inputService, musicService, Locator< MusicHandler, MusicHandler >::provide(), Locator< SoundHandler, SoundHandler >::provide(), Locator< TextureHandler, TextureHandler >::provide(), Locator< ShaderHandler, ShaderHandler >::provide(), Locator< Input, NullInput >::provide(), shaderService, soundService, textureService, and thisGame.
initializeAudio()
void Application::initializeAudio () private
For initializing audio (SDL_Mixer)
Definition at line 79 of file Application.cpp.
References AUDIO_BUFFER, AUDIO_CHANNEL, AUDIO_FORMAT, AUDIO_RATE, and DBG_LOG.
Referenced by initialize().
initializeGL()
void Application::initializeGL () private
For initializing openGL.
Definition at line 111 of file Application.cpp.
References DBG_LOG, and SCREEN_COLOR.
Referenced by initialize().
initializeSDL()
void Application::initializeSDL () private
For initializing SDL2.
Definition at line 85 of file Application.cpp.
References DBG_LOG, Engine::gameWindow, Engine::Window::getWindow(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), Engine::Window::initialize(), GameInfo::MIN_WINDOW_HEIGHT, GameInfo::MIN_WINDOW_WIDTH, and GameInfo::setMousePosition().
Referenced by initialize().
render()
void Application::render () private
For Rendering.
Definition at line 169 of file Application.cpp.
References Engine::gameWindow, Engine::Window::getWindow(), Engine::Game::render(), and thisGame.
run()
void Engine::Application::run ()
Definition at line 27 of file Application.cpp.
References PrivateGameInfo::deltaTime, GameInfo::fixedDeltaTime, and Engine::isRunning.
Referenced by main().
uninitialize()
void Application::uninitialize () private
For Uninitializing everything.
Definition at line 193 of file Application.cpp.
References thisGame, and Engine::Game::uninitialize().
update()
void Application::update () private
For updating- generally user input or ai.
Definition at line 176 of file Application.cpp.
References backEndMessagingSystem, Engine::gameWindow, GameInfo::getDeltaTime(), Engine::Window::handleEvents(), Input::handleEvents(), inputService, sdlEventSystem, thisGame, Engine::Game::update(), and Input::updateTimers().
Member Data Documentation
AUDIO_BUFFER
const unsigned int Engine::Application::AUDIO_BUFFER = 256 private
Audio Bufffer (chunk size) Bytes used per output sample.
Definition at line 69 of file Application.h.
Referenced by initializeAudio().
AUDIO_CHANNEL
const unsigned int Engine::Application::AUDIO_CHANNEL = 1 private
Audio Channel 2 for sterio, 1 for mono.
Definition at line 66 of file Application.h.
Referenced by initializeAudio().
AUDIO_FORMAT
const unsigned short Engine::Application::AUDIO_FORMAT = AUDIO_U8 private
Audio Format signed 8-bit samples, in system byte order. Same as AUDIO_S16SYS.
Definition at line 72 of file Application.h.
Referenced by initializeAudio().
AUDIO_RATE
const unsigned int Engine::Application::AUDIO_RATE = 44100 private
Audio Rate.(frequency) 22050 for LQ sound (faster) 44100 for HQ sound.
Definition at line 63 of file Application.h.
Referenced by initializeAudio().
backEndMessagingSystem
Messenger<BackEndMessages> Engine::Application::backEndMessagingSystem private
Manages BackEndMessages to send to Game.
Definition at line 96 of file Application.h.
Referenced by initialize(), and update().
currentTime
Time Engine::Application::currentTime private
Manages time.
Definition at line 93 of file Application.h.
Referenced by initialize().
inputService
Input Engine::Application::inputService private
Definition at line 78 of file Application.h.
Referenced by initialize(), and update().
musicService
MusicHandler Engine::Application::musicService private
Definition at line 84 of file Application.h.
Referenced by initialize().
SCREEN_COLOR
const glm::vec4 Engine::Application::SCREEN_COLOR = glm::vec4(.8f, .9f, .95f, 1.f) private
The default color of the screen.
Definition at line 75 of file Application.h.
Referenced by initializeGL().
sdlEventSystem
SDL_Event Engine::Application::sdlEventSystem private
Definition at line 60 of file Application.h.
Referenced by update().
shaderService
ShaderHandler Engine::Application::shaderService private
Definition at line 90 of file Application.h.
Referenced by initialize().
soundService
SoundHandler Engine::Application::soundService private
Definition at line 81 of file Application.h.
Referenced by initialize().
textureService
TextureHandler Engine::Application::textureService private
Definition at line 87 of file Application.h.
Referenced by initialize().
thisGame
Game Engine::Application::thisGame private
We run the game with this!
Definition at line 99 of file Application.h.
Referenced by fixedUpdate(), initialize(), render(), uninitialize(), and update().
The documentation for this class was generated from the following files:
src/engine/main/Application.h
src/engine/main/Application.cpp