LightShow_Boilerplate: Entities Namespace Reference
Entities Namespace Reference
Functions
template<typename T >
static EntityWrapper * registerEntity ()
Used to map a string to an EntityWrapper type's constructor.
static EntityWrapper * allocateEntity (const std::string &str)
Used to allocate a new entity via string registered with registerEntity. Does not control lifetime of allocated entity.
static void registerEntities ()
Registers all entities so they can be created with Entities::allocateEntity via string.
Variables
static std::map< std::string, EntityWrapper *(*)()> entityTypes
Map of entity constructors.
Function Documentation
allocateEntity()
static EntityWrapper* Entities::allocateEntity (const std::string & str) static
Used to allocate a new entity via string registered with registerEntity. Does not control lifetime of allocated entity.
Definition at line 170 of file EntityTests.h.
References DBG_LOG, and entityTypes.
Referenced by Engine::Game::loadScene().
registerEntities()
static void Entities::registerEntities () static
Registers all entities so they can be created with Entities::allocateEntity via string.
Definition at line 183 of file EntityTests.h.
References entityTypes.
Referenced by Engine::Game::initialize().
registerEntity()
template<typename T > static EntityWrapper* Entities::registerEntity () static
Used to map a string to an EntityWrapper type's constructor.
Definition at line 164 of file EntityTests.h.
Variable Documentation
entityTypes
std::map<std::string, EntityWrapper* (*)()> Entities::entityTypes static
Map of entity constructors.
Definition at line 167 of file EntityTests.h.
Referenced by allocateEntity(), and registerEntities().