LightShow_Boilerplate: Window Class Reference
Window Class Reference
#include <Window.h>
Public Member Functions
~Window ()
void initialize ()
void handleEvents (SDL_Event &eventSystem, SDL_WindowEventID windowEvent, Messenger< BackEndMessages > &msgr)
void setWindowTitle (const std::string &title)
unsigned int getWidth () const
unsigned int getHeight () const
std::string getCurrentTitle () const
SDL_Window *const getWindow () const
Private Member Functions
void resizeWindow (int w, int h, Messenger< BackEndMessages > &msgr)
glm::ivec2 getDeviceMaxScreenSize ()
Private Attributes
std::string windowTitle = GameInfo::WINDOW_TITLE
SDL_Window * gameWindow = nullptr
SDL_GLContext glContext = nullptr
unsigned int width = GameInfo::START_WINDOW_WIDTH
unsigned int height = GameInfo::START_WINDOW_HEIGHT
Detailed Description
Definition at line 11 of file Window.h.
Constructor & Destructor Documentation
~Window()
Window::~Window ()
Definition at line 3 of file Window.cpp.
References gameWindow, and glContext.
Member Function Documentation
getCurrentTitle()
std::string Window::getCurrentTitle () const inline
Definition at line 23 of file Window.h.
References windowTitle.
getDeviceMaxScreenSize()
glm::ivec2 Window::getDeviceMaxScreenSize () private
Definition at line 54 of file Window.cpp.
References DBG_LOG.
Referenced by handleEvents().
getHeight()
unsigned int Window::getHeight () const inline
Definition at line 22 of file Window.h.
References height.
getWidth()
unsigned int Window::getWidth () const inline
Definition at line 21 of file Window.h.
References width.
getWindow()
SDL_Window* const Window::getWindow () const inline
Definition at line 24 of file Window.h.
References gameWindow.
Referenced by Application::initializeSDL(), and Application::render().
handleEvents()
void Window::handleEvents (SDL_Event & eventSystem, SDL_WindowEventID windowEvent, Messenger< BackEndMessages > & msgr)
Definition at line 24 of file Window.cpp.
References DBG_LOG, getDeviceMaxScreenSize(), and resizeWindow().
Referenced by Application::update().
initialize()
void Window::initialize ()
Definition at line 7 of file Window.cpp.
References gameWindow, glContext, height, width, and windowTitle.
Referenced by Application::initializeSDL().
resizeWindow()
void Window::resizeWindow (int w, int h, Messenger< BackEndMessages > & msgr) private
Definition at line 46 of file Window.cpp.
References Messenger< T >::addMessage(), gameWindow, height, REFRESH_CAMERA, and width.
Referenced by handleEvents().
setWindowTitle()
void Window::setWindowTitle (const std::string & title)
Definition at line 41 of file Window.cpp.
References gameWindow, and windowTitle.
Member Data Documentation
gameWindow
SDL_Window* Window::gameWindow = nullptr private
Definition at line 33 of file Window.h.
Referenced by getWindow(), initialize(), resizeWindow(), setWindowTitle(), and ~Window().
glContext
SDL_GLContext Window::glContext = nullptr private
Definition at line 34 of file Window.h.
Referenced by initialize(), and ~Window().
height
unsigned int Window::height = GameInfo::START_WINDOW_HEIGHT private
Definition at line 37 of file Window.h.
Referenced by getHeight(), initialize(), and resizeWindow().
width
unsigned int Window::width = GameInfo::START_WINDOW_WIDTH private
Definition at line 36 of file Window.h.
Referenced by getWidth(), initialize(), and resizeWindow().
windowTitle
std::string Window::windowTitle = GameInfo::WINDOW_TITLE private
Definition at line 31 of file Window.h.
Referenced by getCurrentTitle(), initialize(), and setWindowTitle().
The documentation for this class was generated from the following files:
src/Window.h
src/Window.cpp