LightShow_Boilerplate: Serialization Namespace Reference
Serialization Namespace Reference
Typedefs
typedef uint64_t EightBytes
typedef uint32_t FourBytes
typedef uint16_t TwoBytes
typedef uint8_t Byte
Functions
template<typename T >
void swapEndian (T *objp)
template<typename T >
void writeBytes (T &variableToSerialize, const unsigned short &amountOfBytes, std::ofstream &oStream)
template<typename T >
void readBytes (T &variableToReadInto, const unsigned short &amountOfBytes, std::ifstream &iStream, const bool &swapEndianness)
bool isBigEndian ()
void writeBytes (const char *cStr, const unsigned short &amountOfBytes, std::ofstream &oStream)
void readBytes (const char *cStr, const unsigned short &amountOfBytes, std::ifstream &iStream)
Variables
const Byte SIZE_OF_FLOAT = 4
Typedef Documentation
Byte
typedef uint8_t Serialization::Byte
Definition at line 18 of file Serialization.h.
EightBytes
typedef uint64_t Serialization::EightBytes
Definition at line 15 of file Serialization.h.
FourBytes
typedef uint32_t Serialization::FourBytes
Definition at line 16 of file Serialization.h.
TwoBytes
typedef uint16_t Serialization::TwoBytes
Definition at line 17 of file Serialization.h.
Function Documentation
isBigEndian()
bool Serialization::isBigEndian ()
Definition at line 3 of file Serialization.cpp.
Referenced by TextMap::createMap(), and _3DM::_3DM_IO::readAnimatedModel().
readBytes() [1/2]
void Serialization::readBytes (const char * cStr, const unsigned short & amountOfBytes, std::ifstream & iStream)
Definition at line 13 of file Serialization.cpp.
readBytes() [2/2]
template<typename T > void Serialization::readBytes (T & variableToReadInto, const unsigned short & amountOfBytes, std::ifstream & iStream, const bool & swapEndianness)
Definition at line 35 of file Serialization.h.
References swapEndian().
Referenced by TextMap::createMap(), _3DM::_3DM_IO::readAnimatedMesh(), _3DM::_3DM_IO::readAnimatedModel(), _3DM::_3DM_IO::readAnimation(), _3DM::_3DM_IO::readAnimationClip(), _3DM::_3DM_IO::readBoneHierarchyFromFile(), _3DM::_3DM_IO::readChannel(), _3DM::_3DM_IO::readMesh(), _3DM::_3DM_IO::readModel(), and _3DM::_3DM_IO::readVector().
swapEndian()
template<typename T > void Serialization::swapEndian (T * objp)
Definition at line 24 of file Serialization.h.
Referenced by readBytes().
writeBytes() [1/2]
void Serialization::writeBytes (const char * cStr, const unsigned short & amountOfBytes, std::ofstream & oStream)
Definition at line 9 of file Serialization.cpp.
writeBytes() [2/2]
template<typename T > void Serialization::writeBytes (T & variableToSerialize, const unsigned short & amountOfBytes, std::ofstream & oStream)
Definition at line 30 of file Serialization.h.
Referenced by _3DM::_3DM_IO::writeAnimatedMesh(), _3DM::_3DM_IO::writeAnimatedModel(), _3DM::_3DM_IO::writeAnimation(), _3DM::_3DM_IO::writeBoneHierarchyToFile(), _3DM::_3DM_IO::writeMesh(), _3DM::_3DM_IO::writeModel(), and _3DM::_3DM_IO::writeVector().
Variable Documentation
SIZE_OF_FLOAT
const Byte Serialization::SIZE_OF_FLOAT = 4
Definition at line 20 of file Serialization.h.
Referenced by _3DM::_3DM_IO::readAnimatedMesh(), _3DM::_3DM_IO::readAnimation(), _3DM::_3DM_IO::readAnimationClip(), _3DM::_3DM_IO::readChannel(), _3DM::_3DM_IO::readMesh(), _3DM::_3DM_IO::writeAnimatedMesh(), _3DM::_3DM_IO::writeAnimation(), _3DM::_3DM_IO::writeAnimationClip(), _3DM::_3DM_IO::writeChannel(), and _3DM::_3DM_IO::writeMesh().