LightShow_Boilerplate: PlayerCameraHandler Class Reference
PlayerCameraHandler Class Reference
#include <PlayerCameraHandler.h>
Public Member Functions
void setCameraTargetOffset (const glm::vec3 &offset)
void setYInterpolationSpeed (float speed)
const glm::vec3 * getCameraTargetOffset ()
float getYinterpolationSpeed () const
Public Member Functions inherited from Component< PlayerCameraHandler >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
glm::vec3 cameraTargetOffset = glm::vec3(0, 2.5f, 0)
float cameraYInterpolationSpeed = 5
Additional Inherited Members
Static Public Attributes inherited from Component< PlayerCameraHandler >
static int32_t type
Detailed Description
Definition at line 7 of file PlayerCameraHandler.h.
Member Function Documentation
getCameraTargetOffset()
const glm::vec3* PlayerCameraHandler::getCameraTargetOffset () inline
Definition at line 13 of file PlayerCameraHandler.h.
References cameraTargetOffset.
Referenced by PlayerCameraHandlingSystem::setThirdPersonCameraTargetPosition().
getYinterpolationSpeed()
float PlayerCameraHandler::getYinterpolationSpeed () const inline
Definition at line 14 of file PlayerCameraHandler.h.
References cameraYInterpolationSpeed.
setCameraTargetOffset()
void PlayerCameraHandler::setCameraTargetOffset (const glm::vec3 & offset) inline
Definition at line 10 of file PlayerCameraHandler.h.
References cameraTargetOffset.
setYInterpolationSpeed()
void PlayerCameraHandler::setYInterpolationSpeed (float speed) inline
Definition at line 11 of file PlayerCameraHandler.h.
References cameraYInterpolationSpeed.
Member Data Documentation
cameraTargetOffset
glm::vec3 PlayerCameraHandler::cameraTargetOffset = glm::vec3(0, 2.5f, 0) private
Definition at line 17 of file PlayerCameraHandler.h.
Referenced by getCameraTargetOffset(), and setCameraTargetOffset().
cameraYInterpolationSpeed
float PlayerCameraHandler::cameraYInterpolationSpeed = 5 private
Definition at line 18 of file PlayerCameraHandler.h.
Referenced by getYinterpolationSpeed(), and setYInterpolationSpeed().
The documentation for this class was generated from the following file:
src/PlayerCameraHandler.h