LightShow_Boilerplate: DebuggingController Class Reference
DebuggingController Class Reference
#include <DebuggingController.h>
Public Member Functions
void controlPhysicsDebugDraw (Input &inputHandler, PhysicsWorld &world)
void executeDebugRendering (PhysicsWorld &world, const glm::mat4 &viewMatrix, const glm::mat4 &projectionMatrix)
void controlWireframeDebugDraw (Input &inputHandler)
Public Member Functions inherited from Component< DebuggingController >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Static Public Attributes
static const SDL_Keycode PHYSICS_DRAW_TOGGLE = SDLK_F1
static const SDL_Keycode WIREFRAME_DRAW_TOGGLE = SDLK_F2
Static Public Attributes inherited from Component< DebuggingController >
static int32_t type
Private Attributes
bool isDebugDrawOn = false
bool isWireframeOn = false
Detailed Description
Definition at line 8 of file DebuggingController.h.
Member Function Documentation
controlPhysicsDebugDraw()
void DebuggingController::controlPhysicsDebugDraw (Input & inputHandler, PhysicsWorld & world)
Definition at line 3 of file DebuggingController.cpp.
References DBG_LOG, PhysicsWorld::initializeDebugDraw(), isDebugDrawOn, Input::keyPressedOnce(), and PHYSICS_DRAW_TOGGLE.
controlWireframeDebugDraw()
void DebuggingController::controlWireframeDebugDraw (Input & inputHandler)
Definition at line 22 of file DebuggingController.cpp.
References DBG_LOG, isWireframeOn, Input::keyPressedOnce(), and WIREFRAME_DRAW_TOGGLE.
executeDebugRendering()
void DebuggingController::executeDebugRendering (PhysicsWorld & world, const glm::mat4 & viewMatrix, const glm::mat4 & projectionMatrix)
Definition at line 16 of file DebuggingController.cpp.
References PhysicsWorld::debugDraw(), and isDebugDrawOn.
Referenced by RenderingSystem::renderDebugging().
Member Data Documentation
isDebugDrawOn
bool DebuggingController::isDebugDrawOn = false private
Definition at line 20 of file DebuggingController.h.
Referenced by controlPhysicsDebugDraw(), and executeDebugRendering().
isWireframeOn
bool DebuggingController::isWireframeOn = false private
Definition at line 21 of file DebuggingController.h.
Referenced by controlWireframeDebugDraw().
PHYSICS_DRAW_TOGGLE
const SDL_Keycode DebuggingController::PHYSICS_DRAW_TOGGLE = SDLK_F1 static
Definition at line 10 of file DebuggingController.h.
Referenced by controlPhysicsDebugDraw().
WIREFRAME_DRAW_TOGGLE
const SDL_Keycode DebuggingController::WIREFRAME_DRAW_TOGGLE = SDLK_F2 static
Definition at line 11 of file DebuggingController.h.
Referenced by controlWireframeDebugDraw().
The documentation for this class was generated from the following files:
src/DebuggingController.h
src/DebuggingController.cpp