LightShow_Boilerplate: Shader Class Reference
Shader Class Reference
#include <Shader.h>
Public Member Functions
Shader ()
~Shader ()
SHADER_TYPE getShaderType ()
void setShaderType (SHADER_TYPE &type)
Shader (const std::string &id, const std::string &vertexPath, const std::string &fragmentPath, const SHADER_TYPE &type, const std::string &geometryPath="")
GLint getProgramID () const
void useProgram ()
void supplyVec3fUniform (const std::string &location, const glm::vec3 &value)
void supply1fUniform (const std::string &location, const float &value)
void recompileShader ()
Shader (const std::string &id, const Settings &currentSettings, const std::string &vertexPath, const std::string &fragmentPath, const SHADER_TYPE &type, const std::string &geometryPath="")
void recompileShader (const Settings &currentSettings)
void setPointLight (const Settings &currentSettings, const PointLight &light, unsigned int index)
void setDirectionalLight (const DirectionalLight &directionalLight)
void setMaterial (const Material &material)
void setSimpleMaterial (const SimpleMaterial &material)
void setShininess (const float &shininess)
std::string getIdentifier () const
Public Member Functions inherited from Component< Shader >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Static Public Member Functions
static SHADER_TASK getShaderTask ()
static void setShaderTaskShader (SHADER_TASK task, const GLint &id)
static void setShaderTask (SHADER_TASK task)
Private Member Functions
void updateTagValues (const Settings &currentSettings, std::string &fragmentCode)
void updateTagValue (const std::string &tag, const std::string &toAdd, std::string &stringToModify)
GLint createAndCompileShader (int GLShaderType, const GLchar *const *code)
int getCode (const std::string &vertexPath, const std::string &fragmentPath, const std::string &geometryPath, std::string &vertexCode, std::string &fragmentCode, std::string &geometryCode)
void createProgram (const std::string &vShaderCode, const std::string &fShaderCode, const std::string &gShaderCode)
Private Attributes
GLint programID = -1
std::string vertexFilePath
std::string fragmentFilePath
std::string geometryFilePath
SHADER_TYPE shaderType = SHADER_TYPE::Default
std::string identifier = ""
Static Private Attributes
static GLint shadersForTasks [static_cast< unsigned int >(SHADER_TASK::SHADER_TASK_MAX)]
static SHADER_TASK currentTask = SHADER_TASK::Normal_Render_Task
Additional Inherited Members
Static Public Attributes inherited from Component< Shader >
static int32_t type
Detailed Description
Definition at line 19 of file Shader.h.
Constructor & Destructor Documentation
Shader() [1/3]
Shader::Shader () inline
Definition at line 22 of file Shader.h.
~Shader()
Shader::~Shader () inline
Definition at line 24 of file Shader.h.
Shader() [2/3]
Shader::Shader (const std::string & id, const std::string & vertexPath, const std::string & fragmentPath, const SHADER_TYPE & type, const std::string & geometryPath = "")
Definition at line 119 of file Shader.cpp.
References createProgram(), DBG_LOG, fragmentFilePath, geometryFilePath, getCode(), identifier, shaderType, Component< Shader >::type, and vertexFilePath.
Shader() [3/3]
Shader::Shader (const std::string & id, const Settings & currentSettings, const std::string & vertexPath, const std::string & fragmentPath, const SHADER_TYPE & type, const std::string & geometryPath = "")
Definition at line 23 of file Shader.cpp.
References createProgram(), DBG_LOG, fragmentFilePath, geometryFilePath, getCode(), Settings::getLightsPerEntity(), identifier, programID, shaderType, Component< Shader >::type, updateTagValues(), and vertexFilePath.
Member Function Documentation
createAndCompileShader()
GLint Shader::createAndCompileShader (int GLShaderType, const GLchar *const * code) private
Definition at line 142 of file Shader.cpp.
References DBG_LOG.
Referenced by createProgram().
createProgram()
void Shader::createProgram (const std::string & vShaderCode, const std::string & fShaderCode, const std::string & gShaderCode) private
Definition at line 244 of file Shader.cpp.
References createAndCompileShader(), DBG_LOG, and programID.
Referenced by recompileShader(), and Shader().
getCode()
int Shader::getCode (const std::string & vertexPath, const std::string & fragmentPath, const std::string & geometryPath, std::string & vertexCode, std::string & fragmentCode, std::string & geometryCode) private
Definition at line 164 of file Shader.cpp.
References DBG_LOG.
Referenced by recompileShader(), and Shader().
getIdentifier()
std::string Shader::getIdentifier () const inline
Definition at line 80 of file Shader.h.
References identifier.
getProgramID()
GLint Shader::getProgramID () const inline
Definition at line 43 of file Shader.h.
References currentTask, programID, and shadersForTasks.
Referenced by SphereShape::drawSphere(), DirectionalLightShadowMap::getDepthMapShader(), PointLightShadowMap::getDepthMapShader(), RenderingSystem::render(), CubeShape::render(), Quad::render2D(), Quad::render3D(), _3DM::Model::renderMesh(), _3DM::AnimatedModel::renderMesh(), DefaultParticleSystem::renderParticles(), RenderingSystem::supplyDefaultShaderUniforms(), RenderingSystem::supplyLitShaderUniforms(), RenderingSystem::supplyParticleShaderUniforms(), DirectionalLightShadowMap::updateDepthMap(), PointLightShadowMap::updateDepthMap(), and useProgram().
getShaderTask()
SHADER_TASK Shader::getShaderTask () static
Definition at line 138 of file Shader.cpp.
References currentTask.
Referenced by RenderingSystem::renderDebugging(), and RenderingSystem::renderOthers().
getShaderType()
SHADER_TYPE Shader::getShaderType () inline
Definition at line 32 of file Shader.h.
References shaderType.
Referenced by RenderingSystem::prepareShader(), and RenderingSystem::renderOthers().
recompileShader() [1/2]
void Shader::recompileShader ()
Definition at line 231 of file Shader.cpp.
References createProgram(), DBG_LOG, fragmentFilePath, geometryFilePath, getCode(), and vertexFilePath.
recompileShader() [2/2]
void Shader::recompileShader (const Settings & currentSettings)
Definition at line 2 of file Shader.cpp.
References createProgram(), DBG_LOG, fragmentFilePath, geometryFilePath, getCode(), Settings::getLightsPerEntity(), programID, updateTagValues(), and vertexFilePath.
setDirectionalLight()
void Shader::setDirectionalLight (const DirectionalLight & directionalLight)
Definition at line 66 of file Shader.cpp.
References DirectionalLight::ambient, DirectionalLight::diffuse, DirectionalLight::direction, Shaders::DirectionalLightAmbient, Shaders::DirectionalLightDiffuse, Shaders::DirectionalLightDirection, Shaders::DirectionalLightSpecular, Shaders::getUniformName(), DirectionalLight::specular, and supplyVec3fUniform().
Referenced by RenderingSystem::initializeLights().
setMaterial()
void Shader::setMaterial (const Material & material)
Definition at line 73 of file Shader.cpp.
References Material::ambient, Material::diffuse, Shaders::getUniformName(), Shaders::MaterialAmbient, Shaders::MaterialDiffuse, Shaders::MaterialShininess, Shaders::MaterialSpecular, Material::shininess, Material::specular, supply1fUniform(), and supplyVec3fUniform().
setPointLight()
void Shader::setPointLight (const Settings & currentSettings, const PointLight & light, unsigned int index)
Definition at line 53 of file Shader.cpp.
References PointLight::ambient, PointLight::constant, PointLight::diffuse, Settings::getLightsPerEntity(), PointLight::linear, PointLight::position, PointLight::quadratic, PointLight::specular, supply1fUniform(), and supplyVec3fUniform().
Referenced by RenderingSystem::initializeLights().
setShaderTask()
static void Shader::setShaderTask (SHADER_TASK task) inline static
Definition at line 30 of file Shader.h.
References currentTask.
Referenced by Engine::Game::initializeShaders(), and RenderingSystem::render().
setShaderTaskShader()
static void Shader::setShaderTaskShader (SHADER_TASK task, const GLint & id) inline static
Definition at line 29 of file Shader.h.
References shadersForTasks.
Referenced by Engine::Game::initializeShaders().
setShaderType()
void Shader::setShaderType (SHADER_TYPE & type) inline
Definition at line 33 of file Shader.h.
References shaderType, and Component< Shader >::type.
setShininess()
void Shader::setShininess (const float & shininess)
Definition at line 84 of file Shader.cpp.
References Shaders::getUniformName(), Shaders::MaterialShininess, and supply1fUniform().
Referenced by setSimpleMaterial().
setSimpleMaterial()
void Shader::setSimpleMaterial (const SimpleMaterial & material)
Definition at line 80 of file Shader.cpp.
References setShininess(), and SimpleMaterial::shininess.
supply1fUniform()
void Shader::supply1fUniform (const std::string & location, const float & value)
Definition at line 309 of file Shader.cpp.
References programID.
Referenced by setMaterial(), setPointLight(), and setShininess().
supplyVec3fUniform()
void Shader::supplyVec3fUniform (const std::string & location, const glm::vec3 & value)
Definition at line 299 of file Shader.cpp.
References programID.
Referenced by setDirectionalLight(), setMaterial(), and setPointLight().
updateTagValue()
void Shader::updateTagValue (const std::string & tag, const std::string & toAdd, std::string & stringToModify) inline private
Definition at line 85 of file Shader.h.
References Shaders::TAG_END.
Referenced by updateTagValues().
updateTagValues()
void Shader::updateTagValues (const Settings & currentSettings, std::string & fragmentCode) private
Definition at line 88 of file Shader.cpp.
References DBG_LOG, Settings::getLightsPerEntity(), Settings::getShadowFilterAmount(), Settings::getShadowIntensity(), Shaders::MAX_LIGHT_TAG, shaderType, Shaders::SHADOW_FILTERING_TAG, Shaders::SHADOW_INTENSITY_TAG, and updateTagValue().
Referenced by recompileShader(), and Shader().
useProgram()
void Shader::useProgram ()
Definition at line 290 of file Shader.cpp.
References getProgramID().
Referenced by RenderingSystem::initializeLights(), RenderingSystem::prepareShader(), RenderingSystem::render(), RenderingSystem::renderOthers(), RenderingSystem::supplyParticleShaderUniforms(), and DirectionalLightShadowMap::updateDepthMap().
Member Data Documentation
currentTask
SHADER_TASK Shader::currentTask = SHADER_TASK::Normal_Render_Task static private
Definition at line 92 of file Shader.h.
Referenced by getProgramID(), getShaderTask(), and setShaderTask().
fragmentFilePath
std::string Shader::fragmentFilePath private
Definition at line 102 of file Shader.h.
Referenced by recompileShader(), and Shader().
geometryFilePath
std::string Shader::geometryFilePath private
Definition at line 103 of file Shader.h.
Referenced by recompileShader(), and Shader().
identifier
std::string Shader::identifier = "" private
Definition at line 107 of file Shader.h.
Referenced by getIdentifier(), and Shader().
programID
GLint Shader::programID = -1 private
Definition at line 99 of file Shader.h.
Referenced by createProgram(), getProgramID(), recompileShader(), Shader(), supply1fUniform(), and supplyVec3fUniform().
shadersForTasks
GLint Shader::shadersForTasks static private
Definition at line 91 of file Shader.h.
Referenced by getProgramID(), and setShaderTaskShader().
shaderType
SHADER_TYPE Shader::shaderType = SHADER_TYPE::Default private
Definition at line 105 of file Shader.h.
Referenced by getShaderType(), setShaderType(), Shader(), and updateTagValues().
vertexFilePath
std::string Shader::vertexFilePath private
Definition at line 101 of file Shader.h.
Referenced by recompileShader(), and Shader().
The documentation for this class was generated from the following files:
src/Shader.h
src/Shader.cpp