LightShow_Boilerplate: DisplayStatisticsSystem Class Reference
DisplayStatisticsSystem Class Reference
#include <DisplayStatisticsSystem.h>
Public Member Functions
void fixedUpdate (DisplayStatistics &ds, const Time &time, GUIResizingInformation &guiInfo)
void render (Shader &shader, DisplayStatistics &ds)
Detailed Description
Definition at line 7 of file DisplayStatisticsSystem.h.
Member Function Documentation
fixedUpdate()
void DisplayStatisticsSystem::fixedUpdate (DisplayStatistics & ds, const Time & time, GUIResizingInformation & guiInfo) inline
Definition at line 10 of file DisplayStatisticsSystem.h.
References DisplayStatistics::currentFPS, DisplayStatistics::currentMSPF, Time::getFPS(), GUIResizingInformation::getLeftScreenPosition(), Time::getMSPF(), GUIResizingInformation::getTopScreenPosition(), GUIResizingInformation::getWidthUnit(), DisplayStatistics::guiString, DisplayStatistics::lastFPS, DisplayStatistics::lastUnit, GuiString::setPosition(), GuiString::setScale(), and GuiString::setString().
render()
void DisplayStatisticsSystem::render (Shader & shader, DisplayStatistics & ds) inline
Definition at line 36 of file DisplayStatisticsSystem.h.
References DisplayStatistics::guiString, and GuiString::render().
Referenced by RenderingSystem::renderOthers().
The documentation for this class was generated from the following file:
src/DisplayStatisticsSystem.h