LightShow_Boilerplate: Shaders Namespace Reference
Shaders Namespace Reference
Enumerations
enum SHADER_TYPE {
SHADER_TYPE::Default = 0, SHADER_TYPE::Lit = 1, SHADER_TYPE::Particle = 2, SHADER_TYPE::GUI = 3,
SHADER_TYPE::SHADER_TYPE_MAX = 4
}
enum SHADER_TASK { SHADER_TASK::Normal_Render_Task = 0, SHADER_TASK::Directional_Depth_Task = 1, SHADER_TASK::Omnidirectional_Depth_Task = 2, SHADER_TASK::SHADER_TASK_MAX = 3 }
enum UniformName {
UniformName::DiffuseTexture = 0, UniformName::SpecularTexture = 1, UniformName::NormalTexture = 2, UniformName::BoneWeights = 3,
UniformName::BoneIDS = 4, UniformName::BoneTransformations = 5, UniformName::TextureCoordinates = 6, UniformName::Position = 7,
UniformName::ModelMatrix = 8, UniformName::ViewMatrix = 9, UniformName::ProjectionMatrix = 10, UniformName::ViewPosition = 11,
UniformName::LightSpaceMatrix = 12, UniformName::LightPosition = 13, UniformName::FarPlane = 14, UniformName::ShadowMatrices = 15,
UniformName::DirectionalShadowMap = 16, UniformName::PointShadowMap = 17, UniformName::IsModelAnimated = 18, UniformName::Color = 19,
UniformName::ProjectionViewMatrix = 20, UniformName::DepthMap = 21, UniformName::NearPlane = 22, UniformName::DirectionalLightDirection = 23,
UniformName::DirectionalLightAmbient = 24, UniformName::DirectionalLightDiffuse = 25, UniformName::DirectionalLightSpecular = 26, UniformName::MaterialDiffuse = 27,
UniformName::MaterialAmbient = 28, UniformName::MaterialSpecular = 29, UniformName::MaterialShininess = 30, UniformName::TimeMS = 31,
UniformName::UNIFORM_NAME_COUNT = 32
}
enum AttribName {
AttribName::Position = 0, AttribName::Normal = 1, AttribName::TextureCoordinates = 2, AttribName::BoneWeights = 3,
AttribName::BoneIDS = 4, AttribName::ParticlePosition = 5, AttribName::ParticleScale = 6, AttribName::ParticleColor = 7,
AttribName::AttribName_MAX = 8
}
Functions
static const char * getUniformName (const UniformName &name)
static GLint getAttribLocation (const AttribName &name)
static GLint getUniformLocation (GLint program, const UniformName &name)
Variables
const std::string MAX_LIGHT_TAG = "/*MAL*/"
const std::string SHADOW_INTENSITY_TAG = "/*SI*/"
const std::string SHADOW_FILTERING_TAG = "/*SF*/"
const std::string TAG_END = "//"
const unsigned short DEPTH_MAP_LOCATION_OMNIDIRECTIONAL = 6
const unsigned short DEPTH_MAP_LOCATION_DIRECTIONAL = 7
static const char * UniformNames [32]
Enumeration Type Documentation
AttribName
enum Shaders::AttribName strong
Enumerator
Position
Normal
TextureCoordinates
BoneWeights
BoneIDS
ParticlePosition
ParticleScale
ParticleColor
AttribName_MAX
Definition at line 117 of file Shaders.h.
SHADER_TASK
enum Shaders::SHADER_TASK strong
Enumerator
Normal_Render_Task
Directional_Depth_Task
Omnidirectional_Depth_Task
SHADER_TASK_MAX
Definition at line 19 of file Shaders.h.
SHADER_TYPE
enum Shaders::SHADER_TYPE strong
Enumerator
Default
Lit
Particle
GUI
SHADER_TYPE_MAX
Definition at line 11 of file Shaders.h.
UniformName
enum Shaders::UniformName strong
Enumerator
DiffuseTexture
SpecularTexture
NormalTexture
BoneWeights
BoneIDS
BoneTransformations
TextureCoordinates
Position
ModelMatrix
ViewMatrix
ProjectionMatrix
ViewPosition
LightSpaceMatrix
LightPosition
FarPlane
ShadowMatrices
DirectionalShadowMap
PointShadowMap
IsModelAnimated
Color
ProjectionViewMatrix
DepthMap
NearPlane
DirectionalLightDirection
DirectionalLightAmbient
DirectionalLightDiffuse
DirectionalLightSpecular
MaterialDiffuse
MaterialAmbient
MaterialSpecular
MaterialShininess
TimeMS
UNIFORM_NAME_COUNT
Definition at line 37 of file Shaders.h.
Function Documentation
getAttribLocation()
static GLint Shaders::getAttribLocation (const AttribName & name) static
Definition at line 138 of file Shaders.h.
Referenced by _3DM::AnimatedModel::bindBuffers(), CubeShape::create(), SphereShape::createSphere(), SphereShape::drawSphere(), Quad::init(), Particles::initialize(), _3DM::Model::initializeBuffers(), _3DM::AnimatedModel::initializeBuffers(), Quad::render2D(), and Quad::render3D().
getUniformLocation()
static GLint Shaders::getUniformLocation (GLint program, const UniformName & name) static
Definition at line 142 of file Shaders.h.
References getUniformName().
Referenced by SphereShape::drawSphere(), RenderingSystem::render(), CubeShape::render(), Quad::render2D(), Quad::render3D(), _3DM::Model::renderMesh(), _3DM::AnimatedModel::renderMesh(), DefaultParticleSystem::renderParticles(), RenderingSystem::supplyDefaultShaderUniforms(), RenderingSystem::supplyLitShaderUniforms(), RenderingSystem::supplyParticleShaderUniforms(), DirectionalLightShadowMap::updateDepthMap(), and PointLightShadowMap::updateDepthMap().
getUniformName()
static const char* Shaders::getUniformName (const UniformName & name) static
Definition at line 131 of file Shaders.h.
References UNIFORM_NAME_COUNT, and UniformNames.
Referenced by getUniformLocation(), _3DM::Model::initializeTexture(), _3DM::AnimatedModel::initializeTexture(), Shader::setDirectionalLight(), Shader::setMaterial(), Shader::setShininess(), and PointLightShadowMap::updateDepthMap().
Variable Documentation
DEPTH_MAP_LOCATION_DIRECTIONAL
const unsigned short Shaders::DEPTH_MAP_LOCATION_DIRECTIONAL = 7
Definition at line 35 of file Shaders.h.
Referenced by RenderingSystem::supplyLitShaderUniforms().
DEPTH_MAP_LOCATION_OMNIDIRECTIONAL
const unsigned short Shaders::DEPTH_MAP_LOCATION_OMNIDIRECTIONAL = 6
Definition at line 31 of file Shaders.h.
Referenced by RenderingSystem::supplyLitShaderUniforms().
MAX_LIGHT_TAG
const std::string Shaders::MAX_LIGHT_TAG = "/*MAL*/"
Definition at line 7 of file Shaders.h.
Referenced by Shader::updateTagValues().
SHADOW_FILTERING_TAG
const std::string Shaders::SHADOW_FILTERING_TAG = "/*SF*/"
Definition at line 9 of file Shaders.h.
Referenced by Shader::updateTagValues().
SHADOW_INTENSITY_TAG
const std::string Shaders::SHADOW_INTENSITY_TAG = "/*SI*/"
Definition at line 8 of file Shaders.h.
Referenced by Shader::updateTagValues().
TAG_END
const std::string Shaders::TAG_END = "//"
Definition at line 27 of file Shaders.h.
Referenced by Shader::updateTagValue().
UniformNames
const char* Shaders::UniformNames[32] static
Definition at line 82 of file Shaders.h.
Referenced by getUniformName().