LightShow_Boilerplate: BoneCollisionMeshSystem Class Reference
BoneCollisionMeshSystem Class Reference
#include <BoneCollisionMeshSystem.h>
Public Member Functions
void fixedUpdate (BoneCollisionMesh &mesh, const _3DM::AnimatedModel &animatedModel)
Detailed Description
Definition at line 6 of file BoneCollisionMeshSystem.h.
Member Function Documentation
fixedUpdate()
void BoneCollisionMeshSystem::fixedUpdate (BoneCollisionMesh & mesh, const _3DM::AnimatedModel & animatedModel)
Definition at line 3 of file BoneCollisionMeshSystem.cpp.
References _3DM::AnimatedModel::getBoneTransformationWithoutOffset(), BoneCollisionMesh::getColliderOffset(), CollisionMesh::getMotionState(), BoneCollisionMesh::iterateThroughColliders(), Transform::position, Transform::rotation, Transform::scale, and ModelBase::transform.
Referenced by FixedUpdatingSystem::fixedUpdate().
The documentation for this class was generated from the following files:
src/BoneCollisionMeshSystem.h
src/BoneCollisionMeshSystem.cpp