LightShow_Boilerplate: Engine::DebugDrawer Class Reference
Engine::DebugDrawer Class Reference
The DebugDrawer class is used to render Bullet3's collision boxes/points/etc.
#include <DebugDrawer.h>
Public Member Functions
DebugDrawer ()
~DebugDrawer ()
virtual DefaultColors getDefaultColors () const
Sets the colors for debug rendering.
void initialize ()
Initializes everything.
void render (const glm::mat4 &projectionMatrix, const glm::mat4 &viewMatrix)
Renders the lines added via drawLine.
virtual void drawLine (const btVector3 &from, const btVector3 &to, const btVector3 &color)
Adds a line to the list of lines to draw next frame.
void drawLine (const btVector3 &from, const btVector3 &to, const btVector3 &colorStart, const btVector3 &colorEnd)
Adds a line to the list of lines to draw next frame.
virtual void drawContactPoint (const btVector3 &PointOnB, const btVector3 &normalOnB, btScalar distance, int lifeTime, const btVector3 &color)
Unimplemented.
virtual void reportErrorWarning (const char *warningString)
virtual void draw3dText (const btVector3 &, const char *)
Unimplemented.
virtual void setDebugMode (int debugMode)
Sets the debug draw mode.
virtual int getDebugMode () const
Gets the debug draw mode.
Private Attributes
Shader thisShader
glm::mat4 identitym = glm::mat4(1.0f)
glm::vec3 lineVertices [Engine::DBG_DRAWER::MAX_AMOUNT_DEBUG_LINES]
glm::vec3 lineColors [Engine::DBG_DRAWER::MAX_AMOUNT_DEBUG_LINES]
int currentDebugMode = 0
unsigned int currentMaxAmountOfVertices = 0
unsigned int currentAmountOfLines = 0
GLuint VAO = 0
GLuint vertID = 0
GLuint colorID = 0
GLint positionAttribute = 0
GLint colorAttribute = 0
GLint projectionLocation = 0
GLint viewLocation = 0
bool initialized = false
Detailed Description
The DebugDrawer class is used to render Bullet3's collision boxes/points/etc.
The DebugDrawer should never be created outside of the PhysicsWorld object.
Definition at line 21 of file DebugDrawer.h.
Constructor & Destructor Documentation
DebugDrawer()
Engine::DebugDrawer::DebugDrawer () inline
Definition at line 23 of file DebugDrawer.h.
~DebugDrawer()
Engine::DebugDrawer::~DebugDrawer ()
Definition at line 58 of file DebugDrawer.cpp.
References DBG_LOG.
Member Function Documentation
draw3dText()
virtual void Engine::DebugDrawer::draw3dText (const btVector3 & , const char *) inline virtual
Unimplemented.
Definition at line 59 of file DebugDrawer.h.
drawContactPoint()
virtual void Engine::DebugDrawer::drawContactPoint (const btVector3 & PointOnB, const btVector3 & normalOnB, btScalar distance, int lifeTime, const btVector3 & color) inline virtual
Unimplemented.
Definition at line 54 of file DebugDrawer.h.
drawLine() [1/2]
void Engine::DebugDrawer::drawLine (const btVector3 & from, const btVector3 & to, const btVector3 & color) virtual
Adds a line to the list of lines to draw next frame.
Definition at line 71 of file DebugDrawer.cpp.
Referenced by PlayerControllerSystem::debugRender(), and DayNightCycleSystem::debugRender().
drawLine() [2/2]
void Engine::DebugDrawer::drawLine (const btVector3 & from, const btVector3 & to, const btVector3 & colorStart, const btVector3 & colorEnd)
Adds a line to the list of lines to draw next frame.
Definition at line 75 of file DebugDrawer.cpp.
References Engine::DBG_DRAWER::MAX_AMOUNT_DEBUG_LINES, and hh::toGlmVec3().
getDebugMode()
virtual int Engine::DebugDrawer::getDebugMode () const inline virtual
Gets the debug draw mode.
Definition at line 65 of file DebugDrawer.h.
References currentDebugMode.
getDefaultColors()
virtual DefaultColors Engine::DebugDrawer::getDefaultColors () const inline virtual
Sets the colors for debug rendering.
Definition at line 27 of file DebugDrawer.h.
initialize()
void Engine::DebugDrawer::initialize ()
Initializes everything.
Definition at line 37 of file DebugDrawer.cpp.
References Shaders::Color, Shaders::getAttribLocation(), Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), Shaders::getUniformLocation(), Engine::DBG_DRAWER::MAX_AMOUNT_DEBUG_LINES, Shaders::ModelMatrix, Shaders::Position, Shaders::ProjectionMatrix, Shader::useProgram(), and Shaders::ViewMatrix.
Referenced by PhysicsWorld::initializeDebugDraw().
render()
void Engine::DebugDrawer::render (const glm::mat4 & projectionMatrix, const glm::mat4 & viewMatrix)
Renders the lines added via drawLine.
Definition at line 3 of file DebugDrawer.cpp.
References colorAttribute, colorID, currentAmountOfLines, currentMaxAmountOfVertices, DBG_LOG, Engine::DBG_DRAWER::DEBUG_LINE_WIDTH, initialized, lineColors, lineVertices, positionAttribute, projectionLocation, thisShader, Shader::useProgram(), VAO, vertID, and viewLocation.
Referenced by PhysicsWorld::debugDraw().
reportErrorWarning()
void Engine::DebugDrawer::reportErrorWarning (const char * warningString) virtual
Definition at line 89 of file DebugDrawer.cpp.
setDebugMode()
void Engine::DebugDrawer::setDebugMode (int debugMode) virtual
Sets the debug draw mode.
Definition at line 85 of file DebugDrawer.cpp.
Referenced by PhysicsWorld::initializeDebugDraw(), and PhysicsWorld::setDebugMode().
Member Data Documentation
colorAttribute
GLint Engine::DebugDrawer::colorAttribute = 0 private
Definition at line 84 of file DebugDrawer.h.
Referenced by render().
colorID
GLuint Engine::DebugDrawer::colorID = 0 private
Definition at line 81 of file DebugDrawer.h.
Referenced by render().
currentAmountOfLines
unsigned int Engine::DebugDrawer::currentAmountOfLines = 0 private
Definition at line 77 of file DebugDrawer.h.
Referenced by render().
currentDebugMode
int Engine::DebugDrawer::currentDebugMode = 0 private
Definition at line 75 of file DebugDrawer.h.
Referenced by getDebugMode().
currentMaxAmountOfVertices
unsigned int Engine::DebugDrawer::currentMaxAmountOfVertices = 0 private
Definition at line 76 of file DebugDrawer.h.
Referenced by render().
identitym
glm::mat4 Engine::DebugDrawer::identitym = glm::mat4(1.0f) private
Definition at line 70 of file DebugDrawer.h.
initialized
bool Engine::DebugDrawer::initialized = false private
Definition at line 87 of file DebugDrawer.h.
Referenced by render().
lineColors
glm::vec3 Engine::DebugDrawer::lineColors[Engine::DBG_DRAWER::MAX_AMOUNT_DEBUG_LINES] private
Definition at line 73 of file DebugDrawer.h.
Referenced by render().
lineVertices
glm::vec3 Engine::DebugDrawer::lineVertices[Engine::DBG_DRAWER::MAX_AMOUNT_DEBUG_LINES] private
Definition at line 72 of file DebugDrawer.h.
Referenced by render().
positionAttribute
GLint Engine::DebugDrawer::positionAttribute = 0 private
Definition at line 83 of file DebugDrawer.h.
Referenced by render().
projectionLocation
GLint Engine::DebugDrawer::projectionLocation = 0 private
Definition at line 85 of file DebugDrawer.h.
Referenced by render().
thisShader
Shader Engine::DebugDrawer::thisShader private
Definition at line 68 of file DebugDrawer.h.
Referenced by render().
VAO
GLuint Engine::DebugDrawer::VAO = 0 private
Definition at line 79 of file DebugDrawer.h.
Referenced by render().
vertID
GLuint Engine::DebugDrawer::vertID = 0 private
Definition at line 80 of file DebugDrawer.h.
Referenced by render().
viewLocation
GLint Engine::DebugDrawer::viewLocation = 0 private
Definition at line 86 of file DebugDrawer.h.
Referenced by render().
The documentation for this class was generated from the following files:
src/engine/physics/DebugDrawer.h
src/engine/physics/DebugDrawer.cpp