LightShow_Boilerplate: EnemyControllerSystem Class Reference
EnemyControllerSystem Class Reference
#include <EnemyControllerSystem.h>
Public Member Functions
EnemyControllerSystem ()
void update (Input &input, EntityTransform &modelsTransform, CollisionMesh &mesh, PhysicsWorld &world, const GlobalInformation &globalInformation, EnemyController &enemyController)
Private Member Functions
void calculateMovment (Input &input, const glm::quat &rotation, const glm::vec3 &playersPosition, CollisionMesh &collisionMesh, EnemyController &enemyController)
void handleRayHit (EnemyController &enemyController, CollisionMesh &collisionMesh, float closest)
int getLowestRayHitIndex (const RayCaster &rayResults, EnemyController &enemyController)
ControllerRayCollision getLowestRayHitForAllRays (EnemyController &enemyController)
void executeRayTesting (EnemyController &enemyController, CollisionMesh &collisionMesh, const Transform &meshTransform, PhysicsWorld &world)
void performCommands (CollisionMesh &collisionMesh, EnemyController &enemyController)
void applyForces (CollisionMesh &collisionMesh, EnemyController &enemyController)
void applyNewTransform (CollisionMesh &mesh, const glm::vec3 &playersPosition, EnemyController &enemyController, Transform &oldTransform)
Private Attributes
RayCaster rayCast [ENEMY_CTRLR_NS::AMOUNT_OF_RAYS]
Detailed Description
Definition at line 21 of file EnemyControllerSystem.h.
Constructor & Destructor Documentation
EnemyControllerSystem()
EnemyControllerSystem::EnemyControllerSystem () inline
Definition at line 24 of file EnemyControllerSystem.h.
References ENEMY_CTRLR_NS::AMOUNT_OF_RAYS.
Member Function Documentation
applyForces()
void EnemyControllerSystem::applyForces (CollisionMesh & collisionMesh, EnemyController & enemyController) private
Definition at line 94 of file EnemyControllerSystem.cpp.
References CollisionMesh::applyCentralImpulse(), and EnemyController::playerGravityImpulse.
Referenced by update().
applyNewTransform()
void EnemyControllerSystem::applyNewTransform (CollisionMesh & mesh, const glm::vec3 & playersPosition, EnemyController & enemyController, Transform & oldTransform) private
Definition at line 123 of file EnemyControllerSystem.cpp.
References CollisionMesh::getPosition(), EnemyController::offsetFromCollider, Transform::position, Transform::rotation, and hh::signedRadiansBetweenVectors().
Referenced by update().
calculateMovment()
void EnemyControllerSystem::calculateMovment (Input & input, const glm::quat & rotation, const glm::vec3 & playersPosition, CollisionMesh & collisionMesh, EnemyController & enemyController) private
Definition at line 3 of file EnemyControllerSystem.cpp.
References EnemyController::currentRotation, EnemyController::currentState, EnemyController::enemyMovmentType, Idle, Idle_Facing_Player, EnemyController::lastKnownTargetPosition, Towards_Target, and Unknown.
Referenced by update().
executeRayTesting()
void EnemyControllerSystem::executeRayTesting (EnemyController & enemyController, CollisionMesh & collisionMesh, const Transform & meshTransform, PhysicsWorld & world) private
Definition at line 98 of file EnemyControllerSystem.cpp.
References EnemyController::colliderWidthAndDepth, RayCaster::getHitNormal(), getLowestRayHitForAllRays(), CollisionMesh::getVelocitybt(), PhysicsWorld::getWorld(), EnemyController::halfLengthOfRay, handleRayHit(), ControllerRayCollision::INVALID_COLLISION, EnemyController::isTouchingGround, ControllerRayCollision::lowestPointIndex, ControllerRayCollision::lowestPointValue, Transform::position, ENEMY_CTRLR_NS::RAY_DISTANCE_CORRECTOR, ENEMY_CTRLR_NS::rayCast, rayCast, ControllerRayCollision::rayIndex, EnemyController::rayNormal, RayCaster::rayTest(), CollisionMesh::setVelocity(), RayCaster::size(), and hh::toGlmVec3().
Referenced by update().
getLowestRayHitForAllRays()
ControllerRayCollision EnemyControllerSystem::getLowestRayHitForAllRays (EnemyController & enemyController) private
Definition at line 69 of file EnemyControllerSystem.cpp.
References ENEMY_CTRLR_NS::AMOUNT_OF_RAYS, RayCaster::getHitFractionRaySpace(), RayCaster::getLength(), getLowestRayHitIndex(), ControllerRayCollision::lowestPointIndex, ControllerRayCollision::lowestPointValue, ENEMY_CTRLR_NS::rayCast, and ControllerRayCollision::rayIndex.
Referenced by executeRayTesting().
getLowestRayHitIndex()
int EnemyControllerSystem::getLowestRayHitIndex (const RayCaster & rayResults, EnemyController & enemyController) private
Definition at line 40 of file EnemyControllerSystem.cpp.
References RayCaster::getCollisionObject(), RayCaster::getHitFraction(), RayCaster::size(), TAG_EMPTY, and CollisionTag::tagName.
Referenced by getLowestRayHitForAllRays().
handleRayHit()
void EnemyControllerSystem::handleRayHit (EnemyController & enemyController, CollisionMesh & collisionMesh, float closest) private
Definition at line 30 of file EnemyControllerSystem.cpp.
References ENEMY_CTRLR_NS::CLAMPING_VELOCITY, CollisionMesh::getVelocitybt(), EnemyController::isTouchingGround, EnemyController::jumping, CollisionMesh::setVelocity(), and CollisionMesh::translate().
Referenced by executeRayTesting().
performCommands()
void EnemyControllerSystem::performCommands (CollisionMesh & collisionMesh, EnemyController & enemyController) private
Definition at line 91 of file EnemyControllerSystem.cpp.
Referenced by update().
update()
void EnemyControllerSystem::update (Input & input, EntityTransform & modelsTransform, CollisionMesh & mesh, PhysicsWorld & world, const GlobalInformation & globalInformation, EnemyController & enemyController)
Definition at line 137 of file EnemyControllerSystem.cpp.
References CollisionMesh::activateRigidBody(), applyForces(), applyNewTransform(), calculateMovment(), executeRayTesting(), GlobalInformation::getPlayersPosition(), CollisionMesh::getTransformation(), performCommands(), Transform::rotation, and EntityTransform::transform.
Referenced by FixedUpdatingSystem::updateCollision().
Member Data Documentation
rayCast
RayCaster EnemyControllerSystem::rayCast[ENEMY_CTRLR_NS::AMOUNT_OF_RAYS] private
Definition at line 31 of file EnemyControllerSystem.h.
Referenced by executeRayTesting().
The documentation for this class was generated from the following files:
src/EnemyControllerSystem.h
src/EnemyControllerSystem.cpp