LightShow_Boilerplate: Application Class Reference
Application Class Reference
#include <Application.h>
Public Member Functions
void run ()
Static Public Member Functions
static unsigned const int getGameWindowWidth ()
static unsigned const int getGameWindowHeight ()
static void setMousePosition (int xPos, int yPos)
Static Public Attributes
static bool isRunning = true
Private Member Functions
void fixedUpdate ()
void update ()
void render ()
void initialize ()
void uninitialize ()
void initializeGL ()
void initializeSDL ()
void initializeAudio ()
Private Attributes
SDL_Event sdlEventSystem
const unsigned int AUDIO_RATE = 22050
const unsigned int AUDIO_CHANNEL = 1
const unsigned int AUDIO_BUFFER = 256
const unsigned short AUDIO_FORMAT = AUDIO_U8
const glm::vec4 SCREEN_COLOR = glm::vec4(.8f, .9f, .95f, 1.f)
Input inputService
SoundHandler soundService
MusicHandler musicService
TextureHandler textureService
ShaderHandler shaderService
Time currentTime
Messenger< BackEndMessages > backEndMessagingSystem
Game thisGame
Static Private Attributes
static Window gameWindow = Window()
Detailed Description
Definition at line 14 of file Application.h.
Member Function Documentation
fixedUpdate()
void Application::fixedUpdate () private
Definition at line 161 of file Application.cpp.
References Game::fixedUpdate(), and thisGame.
Referenced by run().
getGameWindowHeight()
static unsigned const int Application::getGameWindowHeight () inline static
Definition at line 33 of file Application.h.
Referenced by GameInfo::getWindowHeight().
getGameWindowWidth()
static unsigned const int Application::getGameWindowWidth () inline static
Definition at line 30 of file Application.h.
Referenced by GameInfo::getWindowWidth().
initialize()
void Application::initialize () private
Definition at line 140 of file Application.cpp.
References backEndMessagingSystem, currentTime, Game::initialize(), Time::initialize(), initializeAudio(), initializeGL(), initializeSDL(), inputService, musicService, Locator< MusicHandler, MusicHandler >::provide(), Locator< SoundHandler, SoundHandler >::provide(), Locator< TextureHandler, TextureHandler >::provide(), Locator< ShaderHandler, ShaderHandler >::provide(), Locator< Input, NullInput >::provide(), shaderService, soundService, textureService, and thisGame.
Referenced by run().
initializeAudio()
void Application::initializeAudio () private
Definition at line 75 of file Application.cpp.
References AUDIO_BUFFER, AUDIO_CHANNEL, AUDIO_FORMAT, AUDIO_RATE, and DBG_LOG.
Referenced by initialize().
initializeGL()
void Application::initializeGL () private
Definition at line 107 of file Application.cpp.
References DBG_LOG, and SCREEN_COLOR.
Referenced by initialize().
initializeSDL()
void Application::initializeSDL () private
Definition at line 81 of file Application.cpp.
References DBG_LOG, gameWindow, Window::getWindow(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), Window::initialize(), GameInfo::MIN_WINDOW_HEIGHT, GameInfo::MIN_WINDOW_WIDTH, and GameInfo::setMousePosition().
Referenced by initialize().
render()
void Application::render () private
Definition at line 166 of file Application.cpp.
References gameWindow, Window::getWindow(), Game::render(), and thisGame.
Referenced by run().
run()
void Application::run ()
Definition at line 23 of file Application.cpp.
References currentTime, PrivateGameInfo::deltaTime, GameInfo::fixedDeltaTime, fixedUpdate(), Time::getMSPF(), initialize(), isRunning, render(), Time::timeSinceStart, uninitialize(), update(), Time::updateFPS(), and Time::updateMSPF().
Referenced by main().
setMousePosition()
static void Application::setMousePosition (int xPos, int yPos) inline static
Definition at line 36 of file Application.h.
Referenced by GameInfo::setMousePosition().
uninitialize()
void Application::uninitialize () private
Definition at line 190 of file Application.cpp.
References thisGame, and Game::uninitialize().
Referenced by run().
update()
void Application::update () private
Definition at line 173 of file Application.cpp.
References backEndMessagingSystem, gameWindow, Window::handleEvents(), Input::handleEvents(), inputService, sdlEventSystem, thisGame, and Game::update().
Referenced by run().
Member Data Documentation
AUDIO_BUFFER
const unsigned int Application::AUDIO_BUFFER = 256 private
Definition at line 81 of file Application.h.
Referenced by initializeAudio().
AUDIO_CHANNEL
const unsigned int Application::AUDIO_CHANNEL = 1 private
Definition at line 79 of file Application.h.
Referenced by initializeAudio().
AUDIO_FORMAT
const unsigned short Application::AUDIO_FORMAT = AUDIO_U8 private
Definition at line 83 of file Application.h.
Referenced by initializeAudio().
AUDIO_RATE
const unsigned int Application::AUDIO_RATE = 22050 private
Definition at line 77 of file Application.h.
Referenced by initializeAudio().
backEndMessagingSystem
Messenger<BackEndMessages> Application::backEndMessagingSystem private
Definition at line 103 of file Application.h.
Referenced by initialize(), and update().
currentTime
Time Application::currentTime private
Definition at line 101 of file Application.h.
Referenced by initialize(), and run().
gameWindow
Window Application::gameWindow = Window() static private
Definition at line 50 of file Application.h.
Referenced by initializeSDL(), render(), and update().
inputService
Input Application::inputService private
Definition at line 91 of file Application.h.
Referenced by initialize(), and update().
isRunning
bool Application::isRunning = true static
Definition at line 43 of file Application.h.
Referenced by run(), and GameInfo::terminateGame().
musicService
MusicHandler Application::musicService private
Definition at line 95 of file Application.h.
Referenced by initialize().
SCREEN_COLOR
const glm::vec4 Application::SCREEN_COLOR = glm::vec4(.8f, .9f, .95f, 1.f) private
Definition at line 85 of file Application.h.
Referenced by initializeGL().
sdlEventSystem
SDL_Event Application::sdlEventSystem private
Definition at line 75 of file Application.h.
Referenced by update().
shaderService
ShaderHandler Application::shaderService private
Definition at line 99 of file Application.h.
Referenced by initialize().
soundService
SoundHandler Application::soundService private
Definition at line 93 of file Application.h.
Referenced by initialize().
textureService
TextureHandler Application::textureService private
Definition at line 97 of file Application.h.
Referenced by initialize().
thisGame
Game Application::thisGame private
Definition at line 105 of file Application.h.
Referenced by fixedUpdate(), initialize(), render(), uninitialize(), and update().
The documentation for this class was generated from the following files:
src/Application.h
src/Application.cpp