LightShow_Boilerplate: LightTest Class Reference
LightTest Class Reference
#include <EntityTests.h>
Public Member Functions
void initialize (EntityWrapper::EntityVitals &vitals)
~LightTest ()
Public Member Functions inherited from EntityWrapper
virtual ~EntityWrapper ()
Private Attributes
std::vector< PointLight > lights = std::vector<PointLight>(4)
DirectionalLight directionalLight
SkyBox skyBox
Shader skyBoxShader
Detailed Description
Definition at line 42 of file EntityTests.h.
Constructor & Destructor Documentation
~LightTest()
LightTest::~LightTest () inline
Definition at line 46 of file EntityTests.h.
Member Function Documentation
initialize()
void LightTest::initialize (EntityWrapper::EntityVitals & vitals) virtual
Implements EntityWrapper.
Definition at line 216 of file EntityTests.cpp.
References Scene::addComponent(), DirectionalLight::ambient, EntityWrapper::EntityVitals::checkForNulls(), EntityWrapper::EntityVitals::currentSettings, DBG_LOG, DirectionalLight::diffuse, DirectionalLight::direction, directionalLight, Scene::generateEntity(), TextureHandler::getCubeMap(), Settings::getLightsPerEntity(), hh::getRandomRange(), Locator< TextureHandler, TextureHandler >::getService(), Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), lights, EntityWrapper::EntityVitals::scene, ComponentInterface::setActive(), skyBox, skyBoxShader, DirectionalLight::specular, and SkyBox::supplyMap().
Member Data Documentation
directionalLight
DirectionalLight LightTest::directionalLight private
Definition at line 50 of file EntityTests.h.
Referenced by initialize().
lights
std::vector<PointLight> LightTest::lights = std::vector<PointLight>(4) private
Definition at line 49 of file EntityTests.h.
Referenced by initialize().
skyBox
SkyBox LightTest::skyBox private
Definition at line 51 of file EntityTests.h.
Referenced by initialize().
skyBoxShader
Shader LightTest::skyBoxShader private
Definition at line 52 of file EntityTests.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/EntityTests.h
src/EntityTests.cpp