LightShow_Boilerplate: SoundHandler Class Reference
SoundHandler Class Reference
#include <Sound.h>
Public Member Functions
void addSound (const std::string &location)
void playSound (const std::string &location)
~SoundHandler ()
Private Member Functions
Sound * binarySearchSounds (const std::string &key)
void addSoundWithoutChecking (const std::string &location)
void addThenSort (Sound &sound)
Private Attributes
std::vector< Sound * > soundLibrary
Detailed Description
Definition at line 78 of file Sound.h.
Constructor & Destructor Documentation
~SoundHandler()
SoundHandler::~SoundHandler ()
Definition at line 229 of file Sound.cpp.
References DBG_LOG, and soundLibrary.
Member Function Documentation
addSound()
void SoundHandler::addSound (const std::string & location)
Definition at line 203 of file Sound.cpp.
References addSoundWithoutChecking(), binarySearchSounds(), and DBG_LOG.
addSoundWithoutChecking()
void SoundHandler::addSoundWithoutChecking (const std::string & location) private
Definition at line 176 of file Sound.cpp.
References addThenSort(), DBG_LOG, Sound::initialize(), and Sound::isNullSound().
Referenced by addSound(), and playSound().
addThenSort()
void SoundHandler::addThenSort (Sound & sound) private
Definition at line 159 of file Sound.cpp.
References soundLibrary.
Referenced by addSoundWithoutChecking().
binarySearchSounds()
Sound * SoundHandler::binarySearchSounds (const std::string & key) private
Definition at line 136 of file Sound.cpp.
References soundLibrary.
Referenced by addSound(), and playSound().
playSound()
void SoundHandler::playSound (const std::string & location)
Definition at line 215 of file Sound.cpp.
References addSoundWithoutChecking(), and binarySearchSounds().
Member Data Documentation
soundLibrary
std::vector<Sound*> SoundHandler::soundLibrary private
Definition at line 94 of file Sound.h.
Referenced by addThenSort(), binarySearchSounds(), and ~SoundHandler().
The documentation for this class was generated from the following files:
src/Sound.h
src/Sound.cpp