LightShow_Boilerplate: UniqueVec3< T > Class Template Reference
UniqueVec3< T > Class Template Reference
#include <UniqueVectors.h>
Public Member Functions
UniqueVec3 operator+ (UniqueVec3 &v)
UniqueVec3 operator- (UniqueVec3 &v)
UniqueVec3 operator* (UniqueVec3 &v)
UniqueVec3 operator* (T &v)
UniqueVec3 (T X, T Y, T Z)
UniqueVec3 (T XYZ)
UniqueVec3 ()
Public Attributes
union {
T vec3 [3]
struct {
T x
T y
T z
}
};
Detailed Description
template<typename T>
class UniqueVec3< T >
Definition at line 51 of file UniqueVectors.h.
Constructor & Destructor Documentation
UniqueVec3() [1/3]
template<typename T > UniqueVec3< T >::UniqueVec3 (T X, T Y, T Z) inline
Definition at line 81 of file UniqueVectors.h.
References UniqueVec3< T >::x, UniqueVec3< T >::y, and UniqueVec3< T >::z.
UniqueVec3() [2/3]
template<typename T > UniqueVec3< T >::UniqueVec3 (T XYZ) inline
Definition at line 87 of file UniqueVectors.h.
References UniqueVec3< T >::x, UniqueVec3< T >::y, and UniqueVec3< T >::z.
UniqueVec3() [3/3]
template<typename T > UniqueVec3< T >::UniqueVec3 () inline
Definition at line 92 of file UniqueVectors.h.
References UniqueVec3< T >::x, UniqueVec3< T >::y, and UniqueVec3< T >::z.
Referenced by UniqueVec3< T >::operator*(), UniqueVec3< T >::operator+(), and UniqueVec3< T >::operator-().
Member Function Documentation
operator*() [1/2]
template<typename T > UniqueVec3 UniqueVec3< T >::operator* (T & v) inline
Definition at line 77 of file UniqueVectors.h.
References UniqueVec3< T >::UniqueVec3(), UniqueVec3< T >::x, UniqueVec3< T >::y, and UniqueVec3< T >::z.
operator*() [2/2]
template<typename T > UniqueVec3 UniqueVec3< T >::operator* (UniqueVec3< T > & v) inline
Definition at line 73 of file UniqueVectors.h.
References UniqueVec3< T >::UniqueVec3(), UniqueVec3< T >::x, UniqueVec3< T >::y, and UniqueVec3< T >::z.
operator+()
template<typename T > UniqueVec3 UniqueVec3< T >::operator+ (UniqueVec3< T > & v) inline
Definition at line 65 of file UniqueVectors.h.
References UniqueVec3< T >::UniqueVec3(), UniqueVec3< T >::x, UniqueVec3< T >::y, and UniqueVec3< T >::z.
operator-()
template<typename T > UniqueVec3 UniqueVec3< T >::operator- (UniqueVec3< T > & v) inline
Definition at line 69 of file UniqueVectors.h.
References UniqueVec3< T >::UniqueVec3(), UniqueVec3< T >::x, UniqueVec3< T >::y, and UniqueVec3< T >::z.
Member Data Documentation
@5
union { ... }
vec3
template<typename T > T UniqueVec3< T >::vec3[3]
Definition at line 56 of file UniqueVectors.h.
x
template<typename T > T UniqueVec3< T >::x
Definition at line 59 of file UniqueVectors.h.
Referenced by UniqueVec3< T >::operator*(), UniqueVec3< T >::operator+(), UniqueVec3< T >::operator-(), and UniqueVec3< T >::UniqueVec3().
y
template<typename T > T UniqueVec3< T >::y
Definition at line 60 of file UniqueVectors.h.
Referenced by UniqueVec3< T >::operator*(), UniqueVec3< T >::operator+(), UniqueVec3< T >::operator-(), and UniqueVec3< T >::UniqueVec3().
z
template<typename T > T UniqueVec3< T >::z
Definition at line 61 of file UniqueVectors.h.
Referenced by UniqueVec3< T >::operator*(), UniqueVec3< T >::operator+(), UniqueVec3< T >::operator-(), and UniqueVec3< T >::UniqueVec3().
The documentation for this class was generated from the following file:
src/UniqueVectors.h