LightShow_Boilerplate: SkyBoxSystem Class Reference
SkyBoxSystem Class Reference
#include <SkyBoxSystem.h>
Public Member Functions
void init (SkyBox &skybox)
void render (SkyBox &skybox, Camera &camera, Shader &shader)
Detailed Description
Definition at line 6 of file SkyBoxSystem.h.
Member Function Documentation
init()
void SkyBoxSystem::init (SkyBox & skybox) inline
Definition at line 8 of file SkyBoxSystem.h.
References CubeShape::create(), and SkyBox::getCube().
render()
void SkyBoxSystem::render (SkyBox & skybox, Camera & camera, Shader & shader) inline
Definition at line 9 of file SkyBoxSystem.h.
References SkyBox::getCube(), SkyBox::getCubeMap(), CubeMap::getCubeMapData(), and CubeShape::render().
Referenced by RenderingSystem::renderOthers().
The documentation for this class was generated from the following file:
src/game/systems/subsystems/SkyBoxSystem.h