LightShow_Boilerplate: Particle Struct Reference
Particle Struct Reference
#include <Particles.h>
Public Attributes
float lifeTime = 0
float weight = 0
float size = 1
glm::vec3 position = glm::vec3(0.0f, 0.0f, 0.0f)
glm::vec3 speed = glm::vec3(0.0f, 0.0f, 0.0f)
glm::vec4 color = glm::vec4(1, 1, 1, 1)
Detailed Description
Definition at line 24 of file Particles.h.
Member Data Documentation
color
glm::vec4 Particle::color = glm::vec4(1, 1, 1, 1)
Definition at line 30 of file Particles.h.
Referenced by Particles::initialize(), FountainParticleSystem::performParticleCalculations(), DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
lifeTime
float Particle::lifeTime = 0
Definition at line 25 of file Particles.h.
Referenced by DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
position
glm::vec3 Particle::position = glm::vec3(0.0f, 0.0f, 0.0f)
Definition at line 28 of file Particles.h.
Referenced by Particles::initialize(), DefaultParticleSystem::performParticleCalculations(), FountainParticleSystem::performParticleCalculations(), DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
size
float Particle::size = 1
Definition at line 27 of file Particles.h.
Referenced by Particles::initialize(), FountainParticleSystem::performParticleCalculations(), DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
speed
glm::vec3 Particle::speed = glm::vec3(0.0f, 0.0f, 0.0f)
Definition at line 29 of file Particles.h.
Referenced by DefaultParticleSystem::performParticleCalculations(), FountainParticleSystem::performParticleCalculations(), DefaultParticleSystem::setParticleToDefault(), and FountainParticleSystem::setParticleToDefault().
weight
float Particle::weight = 0
Definition at line 26 of file Particles.h.
Referenced by FountainParticleSystem::performParticleCalculations().
The documentation for this struct was generated from the following file:
src/Particles.h