LightShow_Boilerplate: DebuggingSystem Class Reference
DebuggingSystem Class Reference
Controls the PhysicsWorld DebugDrawer.
#include <DebuggingSystem.h>
Public Member Functions
void controlPhysicsDebugDraw (Input &inputHandler, PhysicsWorld &world)
Updates the DebugDrawer- such as toggling if it should be rendering or not. Should be called in FixedUpdatingSystem.
void executeDebugRendering (PhysicsWorld &world, const glm::mat4 &viewMatrix, const glm::mat4 &projectionMatrix)
Renders the DebugDrawer if it is set to render. Should be called in RenderingSystem.
Detailed Description
Controls the PhysicsWorld DebugDrawer.
Definition at line 8 of file DebuggingSystem.h.
Member Function Documentation
controlPhysicsDebugDraw()
void DebuggingSystem::controlPhysicsDebugDraw (Input & inputHandler, PhysicsWorld & world)
Updates the DebugDrawer- such as toggling if it should be rendering or not. Should be called in FixedUpdatingSystem.
Definition at line 3 of file DebuggingSystem.cpp.
References DBG_LOG, PhysicsWorld::isDebugDrawing(), Input::isKeyPressedOnce(), and PhysicsWorld::setDebugDrawing().
Referenced by FixedUpdatingSystem::fixedUpdate().
executeDebugRendering()
void DebuggingSystem::executeDebugRendering (PhysicsWorld & world, const glm::mat4 & viewMatrix, const glm::mat4 & projectionMatrix)
Renders the DebugDrawer if it is set to render. Should be called in RenderingSystem.
Definition at line 15 of file DebuggingSystem.cpp.
References PhysicsWorld::debugDraw(), and PhysicsWorld::isDebugDrawing().
Referenced by RenderingSystem::renderDebugging().
The documentation for this class was generated from the following files:
src/game/systems/subsystems/DebuggingSystem.h
src/game/systems/subsystems/DebuggingSystem.cpp