LightShow_Boilerplate: PlayerControllerSystem Class Reference
PlayerControllerSystem Class Reference
#include <PlayerControllerSystem.h>
Public Member Functions
PlayerControllerSystem ()
void update (Transform &modelsTransform, PlayerController &playerController, Camera &camera, CollisionMesh &mesh)
void fixedUpdate (Input &input, Transform &modelsTransform, CollisionMesh &mesh, PhysicsWorld &world, PlayerController &playerController, Camera &camera, const UserControls &userControls)
Private Member Functions
void performJump (CollisionMesh &collisionMesh, float jumpVelocity)
void getPlayerInput (Input &input, CollisionMesh &collisionMesh, PlayerController &playerController, Camera &camera, const UserControls &userControls)
void handleRayHit (PlayerController &playerController, CollisionMesh &collisionMesh, float closest)
int getLowestRayHitIndex (const RayCaster &rayResults, PlayerController &playerController)
ControllerRayCollision getLowestRayHitForAllRays (PlayerController &playerController)
void executeRayTesting (PlayerController &playerController, CollisionMesh &collisionMesh, const Transform &meshTransform, PhysicsWorld &world)
glm::vec3 getSlopeSpeed (float sensitivity, const glm::vec3 &rayNormal)
int getCurrentSlopeSpeedIndex (const glm::vec3 &rayNormal, const PlayerController &playerController)
void performCommands (CollisionMesh &collisionMesh, PlayerController &playerController)
void applyForces (CollisionMesh &collisionMesh, PlayerController &playerController)
void applyNewTransform (CollisionMesh &mesh, const glm::vec3 &cameraForward, const PlayerController &playerController, Transform &oldTransform)
void applyNewRotation (const glm::vec3 &cameraForward, const PlayerController &playerController, Transform &oldTransform)
Detailed Description
Definition at line 20 of file PlayerControllerSystem.h.
Constructor & Destructor Documentation
PlayerControllerSystem()
PlayerControllerSystem::PlayerControllerSystem () inline
Definition at line 23 of file PlayerControllerSystem.h.
References PLR_CTRLR_NS::AMOUNT_OF_RAYS.
Member Function Documentation
applyForces()
void PlayerControllerSystem::applyForces (CollisionMesh & collisionMesh, PlayerController & playerController) private
Definition at line 158 of file PlayerControllerSystem.cpp.
References CollisionMesh::addVelocity(), CollisionMesh::applyCentralImpulse(), PlayerController::getResistance(), CollisionMesh::getVelocitybt(), and PlayerController::playerGravityImpulse.
Referenced by fixedUpdate().
applyNewRotation()
void PlayerControllerSystem::applyNewRotation (const glm::vec3 & cameraForward, const PlayerController & playerController, Transform & oldTransform) private
Definition at line 208 of file PlayerControllerSystem.cpp.
References PlayerController::rotateAwayFromCamera, Transform::rotation, and hh::signedRadiansBetweenVectors().
Referenced by update().
applyNewTransform()
void PlayerControllerSystem::applyNewTransform (CollisionMesh & mesh, const glm::vec3 & cameraForward, const PlayerController & playerController, Transform & oldTransform) private
Definition at line 203 of file PlayerControllerSystem.cpp.
References CollisionMesh::getPosition(), PlayerController::offsetFromCollider, and Transform::position.
Referenced by fixedUpdate().
executeRayTesting()
void PlayerControllerSystem::executeRayTesting (PlayerController & playerController, CollisionMesh & collisionMesh, const Transform & meshTransform, PhysicsWorld & world) private
Definition at line 168 of file PlayerControllerSystem.cpp.
References PlayerController::colliderWidthAndDepth, PlayerController::currentSlopeIntensity, getCurrentSlopeSpeedIndex(), RayCaster::getHitNormal(), getLowestRayHitForAllRays(), getSlopeSpeed(), CollisionMesh::getVelocitybt(), PhysicsWorld::getWorld(), PlayerController::halfLengthOfRay, handleRayHit(), ControllerRayCollision::INVALID_COLLISION, PlayerController::isTouchingGround, ControllerRayCollision::lowestPointIndex, ControllerRayCollision::lowestPointValue, Transform::position, PLR_CTRLR_NS::RAY_DISTANCE_CORRECTOR, PLR_CTRLR_NS::rayCast, ControllerRayCollision::rayIndex, PlayerController::rayNormal, RayCaster::rayTest(), CollisionMesh::setVelocity(), RayCaster::size(), PLR_CTRLR_NS::SlopeIntensity::slopeGravity, PlayerController::slopes, and hh::toGlmVec3().
Referenced by fixedUpdate().
fixedUpdate()
void PlayerControllerSystem::fixedUpdate (Input & input, Transform & modelsTransform, CollisionMesh & mesh, PhysicsWorld & world, PlayerController & playerController, Camera & camera, const UserControls & userControls)
Definition at line 220 of file PlayerControllerSystem.cpp.
References CollisionMesh::activateRigidBody(), applyForces(), applyNewTransform(), executeRayTesting(), Camera::getForward(), getPlayerInput(), CollisionMesh::getTransformation(), and performCommands().
Referenced by FixedUpdatingSystem::updateCollision().
getCurrentSlopeSpeedIndex()
int PlayerControllerSystem::getCurrentSlopeSpeedIndex (const glm::vec3 & rayNormal, const PlayerController & playerController) private
Definition at line 134 of file PlayerControllerSystem.cpp.
References PlayerController::MAX_AMOUNT_SLOPE_CALCULATIONS, PLR_CTRLR_NS::SlopeIntensity::slopeAmount, and PlayerController::slopes.
Referenced by executeRayTesting().
getLowestRayHitForAllRays()
ControllerRayCollision PlayerControllerSystem::getLowestRayHitForAllRays (PlayerController & playerController) private
Definition at line 112 of file PlayerControllerSystem.cpp.
References PLR_CTRLR_NS::AMOUNT_OF_RAYS, RayCaster::getHitFractionRaySpace(), RayCaster::getLength(), getLowestRayHitIndex(), ControllerRayCollision::lowestPointIndex, ControllerRayCollision::lowestPointValue, PLR_CTRLR_NS::rayCast, and ControllerRayCollision::rayIndex.
Referenced by executeRayTesting().
getLowestRayHitIndex()
int PlayerControllerSystem::getLowestRayHitIndex (const RayCaster & rayResults, PlayerController & playerController) private
Definition at line 76 of file PlayerControllerSystem.cpp.
References RayCaster::getCollisionObject(), RayCaster::getHitFraction(), RayCaster::size(), TAG_EMPTY, and CollisionTag::tagName.
Referenced by getLowestRayHitForAllRays().
getPlayerInput()
void PlayerControllerSystem::getPlayerInput (Input & input, CollisionMesh & collisionMesh, PlayerController & playerController, Camera & camera, const UserControls & userControls) private
Definition at line 3 of file PlayerControllerSystem.cpp.
References CollisionMesh::addVelocity(), PlayerController::canJump(), PlayerController::currentSlopeIntensity, PlayerController::currentState, Camera::getForward(), UserControls::getPlayerBackwardsKey(), UserControls::getPlayerForwardKey(), UserControls::getPlayerJumpKey(), UserControls::getPlayerLeftKey(), UserControls::getPlayerRightKey(), UserControls::getPlayerViewKey(), CollisionMesh::getPosition(), Camera::getRight(), Idle, Input::isKeyDown(), PlayerController::jumping, Input::keyPressedOnce(), PlayerController::performJump, PlayerController::rotateAwayFromCamera, PlayerController::speed, and Walking.
Referenced by fixedUpdate().
getSlopeSpeed()
glm::vec3 PlayerControllerSystem::getSlopeSpeed (float sensitivity, const glm::vec3 & rayNormal) inline private
Definition at line 43 of file PlayerControllerSystem.h.
References GameInfo::fixedDeltaTime.
Referenced by executeRayTesting().
handleRayHit()
void PlayerControllerSystem::handleRayHit (PlayerController & playerController, CollisionMesh & collisionMesh, float closest) private
Definition at line 61 of file PlayerControllerSystem.cpp.
References PLR_CTRLR_NS::CLAMPING_VELOCITY, CollisionMesh::getPosition(), CollisionMesh::getVelocitybt(), PlayerController::isTouchingGround, PlayerController::jumping, PlayerController::lastTouchedPosition, CollisionMesh::setVelocity(), and CollisionMesh::translate().
Referenced by executeRayTesting().
performCommands()
void PlayerControllerSystem::performCommands (CollisionMesh & collisionMesh, PlayerController & playerController) private
Definition at line 150 of file PlayerControllerSystem.cpp.
References PlayerController::jumping, PlayerController::jumpVelocity, performJump(), and PlayerController::performJump.
Referenced by fixedUpdate().
performJump()
void PlayerControllerSystem::performJump (CollisionMesh & collisionMesh, float jumpVelocity) private
Definition at line 105 of file PlayerControllerSystem.cpp.
References CollisionMesh::applyCentralImpulse().
Referenced by performCommands().
update()
void PlayerControllerSystem::update (Transform & modelsTransform, PlayerController & playerController, Camera & camera, CollisionMesh & mesh)
Definition at line 243 of file PlayerControllerSystem.cpp.
References applyNewRotation(), and Camera::getForward().
Referenced by UpdatingSystem::update().
The documentation for this class was generated from the following files:
src/PlayerControllerSystem.h
src/PlayerControllerSystem.cpp