LightShow_Boilerplate: GuiTextCharacter Class Reference
GuiTextCharacter Class Reference
#include <GuiTextCharacter.h>
Public Member Functions
void render (Shader &shader, Texture &texture, const Glyph &glyph, const glm::vec2 &scale)
Public Attributes
float xPosition = 0
float yPosition = 0
Private Attributes
Quad quad
Detailed Description
Definition at line 5 of file GuiTextCharacter.h.
Member Function Documentation
render()
void GuiTextCharacter::render (Shader & shader, Texture & texture, const Glyph & glyph, const glm::vec2 & scale)
Definition at line 3 of file GuiTextCharacter.cpp.
References Glyph::getHeight(), Glyph::getWidth(), quad, Quad::render3D(), Glyph::x, xPosition, Glyph::y, and yPosition.
Member Data Documentation
quad
Quad GuiTextCharacter::quad private
Definition at line 13 of file GuiTextCharacter.h.
Referenced by render().
xPosition
float GuiTextCharacter::xPosition = 0
Definition at line 9 of file GuiTextCharacter.h.
Referenced by render().
yPosition
float GuiTextCharacter::yPosition = 0
Definition at line 10 of file GuiTextCharacter.h.
Referenced by render().
The documentation for this class was generated from the following files:
src/GuiTextCharacter.h
src/GuiTextCharacter.cpp