LightShow_Boilerplate: GuiButton Class Reference
GuiButton Class Reference
#include <GuiButton.h>
Public Member Functions
void update (Input &input)
template<typename Func >
void onButtonHover (Func function)
template<typename Func >
void onButtonClickedOnce (Func function)
template<typename Func >
void onButtonPressed (Func function)
template<typename Func >
void onButtonReleased (Func function)
BUTTON_STATE getButtonState () const
GuiSprite ()
GuiSprite (Texture &txtre)
Public Member Functions inherited from GuiSprite
GuiSprite ()
GuiSprite (Texture &txtre)
void initialize (Texture &txtre)
void setSprite (float spriteXlocPXL, float spriteYlocPXL, float spriteWPXL, float spriteHPXL)
void setScale (float widthInPixels, float heightInPixels)
void setScale (const glm::vec2 &scaleInPixels)
void setPosition (float x, float y)
void setPosition (const glm::vec2 &pos)
void render (Shader &shader)
Private Member Functions
glm::ivec2 mouseCoordsToScreenCoords (const glm::ivec2 &mousePosition)
bool mouseIsInsideButton (glm::ivec2 mousePosition)
Private Attributes
bool setFirstClick = false
MOUSE_BUTTON mouseButton
BUTTON_STATE currentState = BUTTON_STATE::No_Feedback
Additional Inherited Members
Protected Attributes inherited from GuiSprite
glm::vec2 position = glm::vec2(0.0f, 0.0f)
glm::vec2 scale = glm::vec2(0.0f, 0.0f)
float spriteXStart = 0
float spriteYStart = 0
float spriteWidth = 0
float spriteHeight = 0
Texture * texture = nullptr
Quad quad
Detailed Description
Definition at line 15 of file GuiButton.h.
Member Function Documentation
getButtonState()
BUTTON_STATE GuiButton::getButtonState () const inline
Definition at line 83 of file GuiButton.h.
References currentState.
GuiSprite() [1/2]
GuiSprite::GuiSprite inline
Definition at line 10 of file GuiSprite.h.
GuiSprite() [2/2]
GuiSprite::GuiSprite inline
Definition at line 12 of file GuiSprite.h.
mouseCoordsToScreenCoords()
glm::ivec2 GuiButton::mouseCoordsToScreenCoords (const glm::ivec2 & mousePosition) inline private
Definition at line 89 of file GuiButton.h.
References GameInfo::getWindowHeight(), and GameInfo::getWindowWidth().
Referenced by update().
mouseIsInsideButton()
bool GuiButton::mouseIsInsideButton (glm::ivec2 mousePosition) inline private
Definition at line 95 of file GuiButton.h.
References GuiSprite::position, and GuiSprite::scale.
Referenced by update().
onButtonClickedOnce()
template<typename Func > void GuiButton::onButtonClickedOnce (Func function) inline
Definition at line 63 of file GuiButton.h.
References currentState, FirstClick, and mouseButton.
Referenced by PauseMenuSystem::update().
onButtonHover()
template<typename Func > void GuiButton::onButtonHover (Func function) inline
Definition at line 56 of file GuiButton.h.
References currentState, Hovering, and mouseButton.
onButtonPressed()
template<typename Func > void GuiButton::onButtonPressed (Func function) inline
Definition at line 70 of file GuiButton.h.
References currentState, mouseButton, and Pressed.
onButtonReleased()
template<typename Func > void GuiButton::onButtonReleased (Func function) inline
Definition at line 77 of file GuiButton.h.
References currentState, mouseButton, and Released.
update()
void GuiButton::update (Input & input) inline
Definition at line 20 of file GuiButton.h.
References currentState, FirstClick, Input::getMouseButton(), Input::getMousePosition(), Hovering, LeftButton, mouseButton, mouseCoordsToScreenCoords(), mouseIsInsideButton(), No_Feedback, Pressed, Released, RightButton, and setFirstClick.
Referenced by PauseMenuSystem::update().
Member Data Documentation
currentState
BUTTON_STATE GuiButton::currentState = BUTTON_STATE::No_Feedback private
Definition at line 106 of file GuiButton.h.
Referenced by getButtonState(), onButtonClickedOnce(), onButtonHover(), onButtonPressed(), onButtonReleased(), and update().
mouseButton
MOUSE_BUTTON GuiButton::mouseButton private
Definition at line 105 of file GuiButton.h.
Referenced by onButtonClickedOnce(), onButtonHover(), onButtonPressed(), onButtonReleased(), and update().
setFirstClick
bool GuiButton::setFirstClick = false private
Definition at line 103 of file GuiButton.h.
Referenced by update().
The documentation for this class was generated from the following file:
src/GuiButton.h