LightShow_Boilerplate: GameState Class Reference
GameState Class Reference
#include <GameState.h>
Public Member Functions
GameState (Engine::Game &game)
void loadScene (int sceneIndex)
Loads a scene via index of the scene to be loaded.
int getCurrentSceneIndex ()
Gets the index of the current scene.
int getSceneCount ()
Gets amount of scenes loaded into game.
Private Attributes
Engine::Game * currentGame
Detailed Description
The GameState class is used as a layer to provide Game functions such as Game::loadScene to classes such as FixedUpdatingSystem without exposing sensitive functions like Game::uninitialize or Game::resetVitals.
Essentially: FixedUpdatingSystem, RenderingSystem, and UpdatingSystem should not know the Game class exists.
Definition at line 14 of file GameState.h.
Constructor & Destructor Documentation
GameState()
GameState::GameState (Engine::Game & game)
Definition at line 3 of file GameState.cpp.
References currentGame.
Member Function Documentation
getCurrentSceneIndex()
int GameState::getCurrentSceneIndex ()
Gets the index of the current scene.
Definition at line 14 of file GameState.cpp.
References currentGame, and Engine::Game::getCurrentSceneIndex().
Referenced by FixedUpdatingSystem::fixedUpdate().
getSceneCount()
int GameState::getSceneCount ()
Gets amount of scenes loaded into game.
Definition at line 18 of file GameState.cpp.
References currentGame, and Engine::Game::getSceneCount().
Referenced by FixedUpdatingSystem::fixedUpdate().
loadScene()
void GameState::loadScene (int sceneIndex)
Loads a scene via index of the scene to be loaded.
Definition at line 7 of file GameState.cpp.
References currentGame, and Engine::Game::loadScene().
Referenced by FixedUpdatingSystem::fixedUpdate().
Member Data Documentation
currentGame
Engine::Game* GameState::currentGame private
Definition at line 28 of file GameState.h.
Referenced by GameState(), getCurrentSceneIndex(), getSceneCount(), and loadScene().
The documentation for this class was generated from the following files:
src/engine/GameState.h
src/engine/GameState.cpp