LightShow_Boilerplate: Quad Class Reference
Quad Class Reference
#include <Quad.h>
Public Member Functions
void render3D (const Shader &shader, const Texture &texture, const glm::vec4 &spriteOrientationInPixels, const glm::vec2 &positionInPixels, const glm::vec2 &scaleInPixels)
void render3D (const Shader &shader, GLint textureID, glm::mat4 &modelMatrix)
void render2D (const Shader &shader, GLint textureID)
~Quad ()
Private Member Functions
void init ()
Private Attributes
bool hasInit = false
GLuint quadVAO = 0
GLuint quadVBO = 0
std::vector< GLfloat > quadVertices
Detailed Description
Definition at line 11 of file Quad.h.
Constructor & Destructor Documentation
~Quad()
Quad::~Quad ()
Definition at line 161 of file Quad.cpp.
References DBG_LOG, hasInit, quadVAO, and quadVBO.
Member Function Documentation
init()
void Quad::init () private
Definition at line 3 of file Quad.cpp.
References Shaders::getAttribLocation(), hasInit, Shaders::Position, quadVAO, quadVBO, and Shaders::TextureCoordinates.
Referenced by render2D(), and render3D().
render2D()
void Quad::render2D (const Shader & shader, GLint textureID)
Definition at line 140 of file Quad.cpp.
References Shaders::DiffuseTexture, Shaders::getAttribLocation(), Shader::getProgramID(), Shaders::getUniformLocation(), hasInit, init(), Shaders::Position, quadVAO, quadVBO, quadVertices, and Shaders::TextureCoordinates.
Referenced by RenderingSystem::render().
render3D() [1/2]
void Quad::render3D (const Shader & shader, const Texture & texture, const glm::vec4 & spriteOrientationInPixels, const glm::vec2 & positionInPixels, const glm::vec2 & scaleInPixels)
Definition at line 17 of file Quad.cpp.
References Shaders::DiffuseTexture, Shaders::getAttribLocation(), Texture::getHeight(), Shader::getProgramID(), Texture::getTextureData(), Shaders::getUniformLocation(), Texture::getWidth(), GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), hasInit, init(), Shaders::ModelMatrix, Shaders::Position, quadVAO, quadVBO, quadVertices, and Shaders::TextureCoordinates.
Referenced by GuiTextCharacter::render(), RenderingSystem::render(), and GuiSprite::render().
render3D() [2/2]
void Quad::render3D (const Shader & shader, GLint textureID, glm::mat4 & modelMatrix)
Definition at line 90 of file Quad.cpp.
References Shaders::DiffuseTexture, Shaders::getAttribLocation(), Shader::getProgramID(), Shaders::getUniformLocation(), hasInit, init(), Shaders::ModelMatrix, Shaders::Position, quadVAO, quadVBO, quadVertices, and Shaders::TextureCoordinates.
Member Data Documentation
hasInit
bool Quad::hasInit = false private
Definition at line 29 of file Quad.h.
Referenced by init(), render2D(), render3D(), and ~Quad().
quadVAO
GLuint Quad::quadVAO = 0 private
Definition at line 31 of file Quad.h.
Referenced by init(), render2D(), render3D(), and ~Quad().
quadVBO
GLuint Quad::quadVBO = 0 private
Definition at line 32 of file Quad.h.
Referenced by init(), render2D(), render3D(), and ~Quad().
quadVertices
std::vector<GLfloat> Quad::quadVertices private
Initial value:
= {
        -1.0f, 1.0f,
        0, 1,
        -1.0f, -1.0f,
        0, 0,
        1.0f, 1.0f,
        1, 1,
        1.0f, -1.0f,
        1, 0
    }
Definition at line 33 of file Quad.h.
Referenced by render2D(), and render3D().
The documentation for this class was generated from the following files:
src/Quad.h
src/Quad.cpp