LightShow_Boilerplate: DefaultParticleSystem Class Reference
DefaultParticleSystem Class Reference
#include <ParticleSystem.h>
Public Member Functions
virtual void renderParticles (Shader &shader, Particles &particles)
virtual void fixedUpdateParticles (Particles &particlesWrapper)
virtual void updateParticles (Particles &particlesWrapper)
Protected Member Functions
virtual void setParticleToDefault (Particle &particle, Particles &particles)
virtual void performParticleCalculations (Particle &particle, Particles &particles)
Detailed Description
Definition at line 7 of file ParticleSystem.h.
Member Function Documentation
fixedUpdateParticles()
void DefaultParticleSystem::fixedUpdateParticles (Particles & particlesWrapper) virtual
Definition at line 40 of file ParticleSystem.cpp.
References GameInfo::fixedDeltaTime, Particles::newparticles, Particles::particles, Particles::particlesPerSecond, Particles::renderingSize, setParticleToDefault(), and hh::swapVal().
Referenced by FixedUpdatingSystem::fixedUpdate().
performParticleCalculations()
void DefaultParticleSystem::performParticleCalculations (Particle & particle, Particles & particles) protected virtual
Reimplemented in FountainParticleSystem.
Definition at line 108 of file ParticleSystem.cpp.
References GameInfo::getDeltaTime(), Particle::position, and Particle::speed.
Referenced by updateParticles().
renderParticles()
void DefaultParticleSystem::renderParticles (Shader & shader, Particles & particles) virtual
Definition at line 4 of file ParticleSystem.cpp.
References Particles::areVitalsNull(), DBG_LOG, Shaders::DiffuseTexture, Shader::getProgramID(), Particles::getTexture(), Texture::getTextureData(), Shaders::getUniformLocation(), Particles::instanceBufferObject, Particles::particles, Particles::renderingSize, and Particles::vertexArrayObject.
Referenced by RenderingSystem::renderParticles().
setParticleToDefault()
void DefaultParticleSystem::setParticleToDefault (Particle & particle, Particles & particles) protected virtual
Reimplemented in FountainParticleSystem.
Definition at line 95 of file ParticleSystem.cpp.
References Particle::color, Particles::defaultColor, Particles::defaultLifeTime, Particles::defaultScale, Particles::emmisionPosition, GameInfo::getDeltaTime(), Particle::lifeTime, Particle::position, Particle::size, and Particle::speed.
Referenced by fixedUpdateParticles().
updateParticles()
void DefaultParticleSystem::updateParticles (Particles & particlesWrapper) virtual
Definition at line 86 of file ParticleSystem.cpp.
References Particles::particles, performParticleCalculations(), and Particles::renderingSize.
Referenced by UpdatingSystem::update().
The documentation for this class was generated from the following files:
src/ParticleSystem.h
src/ParticleSystem.cpp