LightShow_Boilerplate: Music Class Reference
Music Class Reference
#include <Sound.h>
Public Member Functions
~Music ()
Music ()
void play () override
std::string getLocation () const override
bool isNullSound () const override
void fadeIn ()
void togglePlay ()
void togglePlay (bool pause)
void initialize (const std::string &location) override
Private Attributes
const unsigned int FADE_SPEED = 2000
Mix_Music * soundClip = nullptr
Additional Inherited Members
Protected Attributes inherited from Audio
std::string location
Detailed Description
Definition at line 47 of file Sound.h.
Constructor & Destructor Documentation
~Music()
Music::~Music ()
Definition at line 124 of file Sound.cpp.
References soundClip.
Music()
Music::Music ()
Definition at line 119 of file Sound.cpp.
Member Function Documentation
fadeIn()
void Music::fadeIn () inline
Definition at line 78 of file Sound.cpp.
References DBG_LOG, FADE_SPEED, and soundClip.
Referenced by MusicHandler::playMusic().
getLocation()
std::string Music::getLocation () const inline override virtual
Implements Audio.
Definition at line 67 of file Sound.cpp.
References Audio::location.
initialize()
void Music::initialize (const std::string & location) override virtual
Implements Audio.
Definition at line 89 of file Sound.cpp.
References Audio::location, and soundClip.
Referenced by MusicHandler::addMusicWithoutChecking().
isNullSound()
bool Music::isNullSound () const inline override virtual
Implements Audio.
Definition at line 74 of file Sound.cpp.
References soundClip.
Referenced by MusicHandler::addMusicWithoutChecking().
play()
void Music::play () inline override virtual
Implements Audio.
Definition at line 56 of file Sound.cpp.
References DBG_LOG, and soundClip.
Referenced by MusicHandler::playMusic().
togglePlay() [1/2]
void Music::togglePlay ()
Definition at line 97 of file Sound.cpp.
Referenced by MusicHandler::toggleMusic().
togglePlay() [2/2]
void Music::togglePlay (bool pause)
Definition at line 108 of file Sound.cpp.
Member Data Documentation
FADE_SPEED
const unsigned int Music::FADE_SPEED = 2000 private
Definition at line 68 of file Sound.h.
Referenced by fadeIn().
soundClip
Mix_Music* Music::soundClip = nullptr private
Definition at line 70 of file Sound.h.
Referenced by fadeIn(), initialize(), isNullSound(), play(), and ~Music().
The documentation for this class was generated from the following files:
src/Sound.h
src/Sound.cpp