LightShow_Boilerplate: Time Class Reference
Time Class Reference
#include <LTime.h>
Classes
struct TimeData
Public Member Functions
double getMSPF () const
int getFPS () const
uint64_t sinceStartMS32 () const
uint64_t sinceStartMS () const
double sinceStartSD () const
float sinceStartSF () const
Private Member Functions
void initialize ()
void updateMSPF ()
void updateFPS ()
Private Attributes
uint64_t timeSinceStart = 0
int fps = 0
int currentFramesInSecond = 0
float timeElapsedForFPSCounter = 0
double currentMSPF = 0
TimeData timeData
Friends
class Engine::Application
Detailed Description
Definition at line 10 of file LTime.h.
Member Function Documentation
getFPS()
int Time::getFPS () const inline
Definition at line 16 of file LTime.h.
References fps.
Referenced by DisplayStatisticsSystem::fixedUpdate().
getMSPF()
double Time::getMSPF () const inline
Definition at line 13 of file LTime.h.
References currentMSPF.
Referenced by DisplayStatisticsSystem::fixedUpdate().
initialize()
void Time::initialize () inline private
Definition at line 47 of file LTime.h.
References timeSinceStart, and updateMSPF().
Referenced by Engine::Application::initialize().
sinceStartMS()
uint64_t Time::sinceStartMS () const inline
Definition at line 22 of file LTime.h.
References timeSinceStart.
sinceStartMS32()
uint64_t Time::sinceStartMS32 () const inline
Definition at line 19 of file LTime.h.
Referenced by sinceStartSF().
sinceStartSD()
double Time::sinceStartSD () const inline
Definition at line 25 of file LTime.h.
References timeSinceStart.
sinceStartSF()
float Time::sinceStartSF () const inline
Definition at line 28 of file LTime.h.
References sinceStartMS32().
updateFPS()
void Time::updateFPS () private
Definition at line 12 of file LTime.cpp.
References currentFramesInSecond, fps, GameInfo::getDeltaTime(), and timeElapsedForFPSCounter.
updateMSPF()
void Time::updateMSPF () private
Definition at line 3 of file LTime.cpp.
References currentMSPF, Time::TimeData::now, Time::TimeData::then, and timeData.
Referenced by initialize().
Friends And Related Function Documentation
Engine::Application
friend class Engine::Application friend
Definition at line 56 of file LTime.h.
Member Data Documentation
currentFramesInSecond
int Time::currentFramesInSecond = 0 private
Definition at line 35 of file LTime.h.
Referenced by updateFPS().
currentMSPF
double Time::currentMSPF = 0 private
Definition at line 38 of file LTime.h.
Referenced by getMSPF(), and updateMSPF().
fps
int Time::fps = 0 private
Definition at line 34 of file LTime.h.
Referenced by getFPS(), and updateFPS().
timeData
TimeData Time::timeData private
Definition at line 45 of file LTime.h.
Referenced by updateMSPF().
timeElapsedForFPSCounter
float Time::timeElapsedForFPSCounter = 0 private
Definition at line 36 of file LTime.h.
Referenced by updateFPS().
timeSinceStart
uint64_t Time::timeSinceStart = 0 private
Definition at line 33 of file LTime.h.
Referenced by initialize(), sinceStartMS(), and sinceStartSD().
The documentation for this class was generated from the following files:
src/engine/main/LTime.h
src/engine/main/LTime.cpp