LightShow_Boilerplate: Scene Class Reference
Scene Class Reference
#include <Scene.h>
Classes
struct Entity
Public Member Functions
bool isEntityActive (const int32_t &id)
void setEntityActive (const int32_t &id, bool t)
int32_t generateEntity ()
void addComponent (const int32_t &objectID, ComponentInterface &component)
template<class T >
T * getComponent (const int32_t &objectID)
template<typename T >
T * getFirstComponentOfType ()
template<typename T >
T * getFirstActiveComponentOfType ()
template<typename T , typename func >
void performOperationsOnAllOfType (func function)
template<typename func >
void loopEntities (func function)
template<typename T >
std::vector< T * > getAllComponentsOfType ()
const std::vector< Entity > *const getAllEntities () const
Private Member Functions
int binarySearchForComponent (int32_t type, int32_t entityID)
int binarySearchForComponent (int32_t type)
bool binarySearchForEntity (int32_t id)
Private Attributes
std::vector< ComponentInterface * > components
std::vector< Entity > entities
Detailed Description
Definition at line 8 of file Scene.h.
Member Function Documentation
addComponent()
void Scene::addComponent (const int32_t & objectID, ComponentInterface & component)
Definition at line 35 of file Scene.cpp.
References binarySearchForEntity(), components, ComponentInterface::entityID, and ComponentInterface::ID.
Referenced by LightTest::initialize(), ParticleTest::initialize(), Player::initialize(), PlayerTestObject::initialize(), EnemyTestObject::initialize(), CubeTrigger::initialize(), and FloorObject::initialize().
binarySearchForComponent() [1/2]
int Scene::binarySearchForComponent (int32_t type) private
Definition at line 99 of file Scene.cpp.
References components.
binarySearchForComponent() [2/2]
int Scene::binarySearchForComponent (int32_t type, int32_t entityID) private
Definition at line 53 of file Scene.cpp.
References components.
Referenced by getAllComponentsOfType(), getComponent(), getFirstActiveComponentOfType(), and getFirstComponentOfType().
binarySearchForEntity()
bool Scene::binarySearchForEntity (int32_t id) private
Definition at line 124 of file Scene.cpp.
References entities.
Referenced by addComponent(), getComponent(), isEntityActive(), and setEntityActive().
generateEntity()
int32_t Scene::generateEntity ()
Definition at line 22 of file Scene.cpp.
References entities, Scene::Entity::id, and Scene::Entity::isActive.
Referenced by LightTest::initialize(), ParticleTest::initialize(), Player::initialize(), PlayerTestObject::initialize(), EnemyTestObject::initialize(), CubeTrigger::initialize(), and FloorObject::initialize().
getAllComponentsOfType()
template<typename T > std::vector<T*> Scene::getAllComponentsOfType () inline
Definition at line 88 of file Scene.h.
References binarySearchForComponent(), and components.
Referenced by RenderingSystem::initializeLights(), RenderingSystem::render(), RenderingSystem::renderDebugging(), RenderingSystem::renderOthers(), and FixedUpdatingSystem::updateCollision().
getAllEntities()
const std::vector< Scene::Entity > *const Scene::getAllEntities () const
Definition at line 49 of file Scene.cpp.
References entities.
Referenced by UpdatingSystem::update().
getComponent()
template<class T > T* Scene::getComponent (const int32_t & objectID) inline
Definition at line 23 of file Scene.h.
References binarySearchForComponent(), binarySearchForEntity(), and components.
Referenced by FixedUpdatingSystem::fixedUpdate(), RenderingSystem::initialize(), RenderingSystem::initializeModels(), RenderingSystem::prepareShader(), RenderingSystem::renderModels(), RenderingSystem::renderOthers(), RenderingSystem::renderParticles(), UpdatingSystem::update(), FixedUpdatingSystem::updateCollision(), and FixedUpdatingSystem::updateGUI().
getFirstActiveComponentOfType()
template<typename T > T* Scene::getFirstActiveComponentOfType () inline
Definition at line 50 of file Scene.h.
References binarySearchForComponent(), and components.
Referenced by FixedUpdatingSystem::handleBackEndMessage(), FixedUpdatingSystem::initialize(), RenderingSystem::initializeLights(), RenderingSystem::render(), RenderingSystem::renderOthers(), UpdatingSystem::update(), FixedUpdatingSystem::updateCollision(), and FixedUpdatingSystem::updateGUI().
getFirstComponentOfType()
template<typename T > T* Scene::getFirstComponentOfType () inline
Definition at line 39 of file Scene.h.
References binarySearchForComponent().
isEntityActive()
bool Scene::isEntityActive (const int32_t & id)
Definition at line 3 of file Scene.cpp.
References binarySearchForEntity(), DBG_LOG, and entities.
Referenced by FixedUpdatingSystem::handleCollisionTrigger(), and RenderingSystem::prepareShader().
loopEntities()
template<typename func > void Scene::loopEntities (func function) inline
Definition at line 78 of file Scene.h.
References entities.
Referenced by FixedUpdatingSystem::fixedUpdate(), RenderingSystem::initialize(), RenderingSystem::renderModels(), RenderingSystem::renderOthers(), and FixedUpdatingSystem::updateGUI().
performOperationsOnAllOfType()
template<typename T , typename func > void Scene::performOperationsOnAllOfType (func function) inline
Definition at line 65 of file Scene.h.
Referenced by Game::fixedUpdate(), FixedUpdatingSystem::fixedUpdate(), Game::initialize(), and FixedUpdatingSystem::updateShadowMaps().
setEntityActive()
void Scene::setEntityActive (const int32_t & id, bool t)
Definition at line 12 of file Scene.cpp.
References binarySearchForEntity(), DBG_LOG, and entities.
Referenced by FixedUpdatingSystem::handleCollisionTrigger().
Member Data Documentation
components
std::vector<ComponentInterface*> Scene::components private
Definition at line 117 of file Scene.h.
Referenced by addComponent(), binarySearchForComponent(), getAllComponentsOfType(), getComponent(), and getFirstActiveComponentOfType().
entities
std::vector<Entity> Scene::entities private
Definition at line 118 of file Scene.h.
Referenced by binarySearchForEntity(), generateEntity(), getAllEntities(), isEntityActive(), loopEntities(), and setEntityActive().
The documentation for this class was generated from the following files:
src/Scene.h
src/Scene.cpp