LightShow_Boilerplate: MusicHandler Class Reference
MusicHandler Class Reference
#include <Sound.h>
Public Member Functions
void stop (bool fadeOut)
void addMusic (const std::string &location)
void playMusic (const std::string &location, bool fadeIn=false)
void toggleMusic ()
void toggleMusic (bool paused)
bool isPlayingMusic ()
~MusicHandler ()
Private Member Functions
Music * binarySearchMusic (const std::string &key)
void addMusicWithoutChecking (const std::string &location)
void addThenSort (Music &sound)
Private Attributes
std::vector< Music * > musicLibrary
const unsigned int FADE_SPEED = 2000
Music * currentlyPlaying = nullptr
Detailed Description
Definition at line 96 of file Sound.h.
Constructor & Destructor Documentation
~MusicHandler()
MusicHandler::~MusicHandler ()
Definition at line 384 of file Sound.cpp.
References DBG_LOG, and musicLibrary.
Member Function Documentation
addMusic()
void MusicHandler::addMusic (const std::string & location)
Definition at line 323 of file Sound.cpp.
References addMusicWithoutChecking(), binarySearchMusic(), and DBG_LOG.
addMusicWithoutChecking()
void MusicHandler::addMusicWithoutChecking (const std::string & location) private
Definition at line 287 of file Sound.cpp.
References addThenSort(), Music::initialize(), and Music::isNullSound().
Referenced by addMusic(), and playMusic().
addThenSort()
void MusicHandler::addThenSort (Music & sound) private
Definition at line 270 of file Sound.cpp.
References musicLibrary.
Referenced by addMusicWithoutChecking().
binarySearchMusic()
Music * MusicHandler::binarySearchMusic (const std::string & key) private
Definition at line 247 of file Sound.cpp.
References musicLibrary.
Referenced by addMusic(), and playMusic().
isPlayingMusic()
bool MusicHandler::isPlayingMusic ()
Definition at line 377 of file Sound.cpp.
playMusic()
void MusicHandler::playMusic (const std::string & location, bool fadeIn = false)
Definition at line 335 of file Sound.cpp.
References addMusicWithoutChecking(), binarySearchMusic(), currentlyPlaying, Music::fadeIn(), and Music::play().
stop()
void MusicHandler::stop (bool fadeOut)
Definition at line 312 of file Sound.cpp.
References FADE_SPEED.
toggleMusic() [1/2]
void MusicHandler::toggleMusic ()
Definition at line 356 of file Sound.cpp.
References currentlyPlaying, DBG_LOG, and Music::togglePlay().
toggleMusic() [2/2]
void MusicHandler::toggleMusic (bool paused)
Definition at line 367 of file Sound.cpp.
References currentlyPlaying, and Music::togglePlay().
Member Data Documentation
currentlyPlaying
Music* MusicHandler::currentlyPlaying = nullptr private
Definition at line 117 of file Sound.h.
Referenced by playMusic(), and toggleMusic().
FADE_SPEED
const unsigned int MusicHandler::FADE_SPEED = 2000 private
Definition at line 116 of file Sound.h.
Referenced by stop().
musicLibrary
std::vector<Music*> MusicHandler::musicLibrary private
Definition at line 114 of file Sound.h.
Referenced by addThenSort(), binarySearchMusic(), and ~MusicHandler().
The documentation for this class was generated from the following files:
src/Sound.h
src/Sound.cpp