LightShow_Boilerplate: PointLightShadowMap Class Reference
PointLightShadowMap Class Reference
#include <PointLightShadowMap.h>
Public Member Functions
PointLightShadowMap ()
~PointLightShadowMap ()
GLuint getCubeMap ()
GLint getDepthMapShader ()
GLfloat getFarPlane ()
glm::vec3 getCurrentLightPosition ()
void setCurrentLightPosition (const glm::vec3 &lightPos)
unsigned int getDepthMapWidth () const
unsigned int getDepthMapHeight () const
void setDepthMapResolution (const unsigned int &width, const unsigned int &height)
GLuint getFBO ()
void setShadowActive (bool t)
bool isActive ()
void initialize ()
void updateDepthMap ()
Public Attributes
const float FOV = glm::radians(90.0f)
Private Member Functions
void updateDepthMapResolution ()
glm::mat4 getShadowTransformation (const glm::vec3 &eye, const glm::vec3 &up)
Private Attributes
glm::mat4 shadowTransforms [6]
unsigned int DEPTH_MAP_WIDTH = 512
unsigned int DEPTH_MAP_HEIGHT = 512
bool lightSupplied = false
GLfloat nearPlane = .10f
GLfloat farPlane = 100.0f
GLfloat aspect = 1.0f
GLuint depthMapFBO = 0
GLuint depthCubeMap = 0
Shader depthMapShader
glm::vec3 lightPosition = glm::vec3(0, 6, 0)
glm::mat4 shadowProjection = glm::perspective(FOV, aspect, nearPlane, farPlane)
bool initialized = false
Detailed Description
Definition at line 11 of file PointLightShadowMap.h.
Constructor & Destructor Documentation
PointLightShadowMap()
PointLightShadowMap::PointLightShadowMap () inline
Definition at line 13 of file PointLightShadowMap.h.
~PointLightShadowMap()
PointLightShadowMap::~PointLightShadowMap ()
Definition at line 41 of file PointLightShadowMap.cpp.
References DBG_LOG, depthCubeMap, depthMapFBO, and initialized.
Member Function Documentation
getCubeMap()
GLuint PointLightShadowMap::getCubeMap () inline
Definition at line 18 of file PointLightShadowMap.h.
References depthCubeMap.
Referenced by RenderingSystem::supplyLitShaderUniforms().
getCurrentLightPosition()
glm::vec3 PointLightShadowMap::getCurrentLightPosition () inline
Definition at line 21 of file PointLightShadowMap.h.
References lightPosition.
Referenced by RenderingSystem::supplyLitShaderUniforms().
getDepthMapHeight()
unsigned int PointLightShadowMap::getDepthMapHeight () const inline
Definition at line 25 of file PointLightShadowMap.h.
References DEPTH_MAP_HEIGHT.
Referenced by RenderingSystem::render().
getDepthMapShader()
GLint PointLightShadowMap::getDepthMapShader () inline
Definition at line 19 of file PointLightShadowMap.h.
References depthMapShader, and Shader::getProgramID().
Referenced by Game::initializeShaders().
getDepthMapWidth()
unsigned int PointLightShadowMap::getDepthMapWidth () const inline
Definition at line 24 of file PointLightShadowMap.h.
References DEPTH_MAP_WIDTH.
Referenced by RenderingSystem::render().
getFarPlane()
GLfloat PointLightShadowMap::getFarPlane () inline
Definition at line 20 of file PointLightShadowMap.h.
References farPlane.
Referenced by RenderingSystem::supplyLitShaderUniforms().
getFBO()
GLuint PointLightShadowMap::getFBO () inline
Definition at line 32 of file PointLightShadowMap.h.
References depthMapFBO.
Referenced by RenderingSystem::render().
getShadowTransformation()
glm::mat4 PointLightShadowMap::getShadowTransformation (const glm::vec3 & eye, const glm::vec3 & up) private
Definition at line 53 of file PointLightShadowMap.cpp.
References lightPosition, and shadowProjection.
Referenced by updateDepthMap().
initialize()
void PointLightShadowMap::initialize ()
Definition at line 3 of file PointLightShadowMap.cpp.
References DBG_LOG, depthCubeMap, depthMapFBO, depthMapShader, Locator< ShaderHandler, ShaderHandler >::getService(), ShaderHandler::getShader(), initialized, and updateDepthMapResolution().
Referenced by Game::initializeShaders().
isActive()
bool PointLightShadowMap::isActive () inline
Definition at line 34 of file PointLightShadowMap.h.
References lightSupplied.
Referenced by RenderingSystem::render(), and RenderingSystem::supplyLitShaderUniforms().
setCurrentLightPosition()
void PointLightShadowMap::setCurrentLightPosition (const glm::vec3 & lightPos) inline
Definition at line 22 of file PointLightShadowMap.h.
References lightPosition.
Referenced by FixedUpdatingSystem::updateShadowMaps().
setDepthMapResolution()
void PointLightShadowMap::setDepthMapResolution (const unsigned int & width, const unsigned int & height) inline
Definition at line 26 of file PointLightShadowMap.h.
References DEPTH_MAP_HEIGHT, DEPTH_MAP_WIDTH, and updateDepthMapResolution().
setShadowActive()
void PointLightShadowMap::setShadowActive (bool t) inline
Definition at line 33 of file PointLightShadowMap.h.
References lightSupplied.
Referenced by FixedUpdatingSystem::updateShadowMaps().
updateDepthMap()
void PointLightShadowMap::updateDepthMap ()
Definition at line 57 of file PointLightShadowMap.cpp.
References aspect, DEPTH_MAP_HEIGHT, DEPTH_MAP_WIDTH, depthMapFBO, depthMapShader, Shaders::FarPlane, farPlane, FOV, Shader::getProgramID(), getShadowTransformation(), Shaders::getUniformLocation(), Shaders::getUniformName(), Shaders::LightPosition, lightPosition, nearPlane, Shaders::ShadowMatrices, shadowProjection, and shadowTransforms.
Referenced by FixedUpdatingSystem::updateShadowMaps().
updateDepthMapResolution()
void PointLightShadowMap::updateDepthMapResolution () inline private
Definition at line 40 of file PointLightShadowMap.h.
References aspect, DBG_LOG, DEPTH_MAP_HEIGHT, DEPTH_MAP_WIDTH, and depthCubeMap.
Referenced by initialize(), and setDepthMapResolution().
Member Data Documentation
aspect
GLfloat PointLightShadowMap::aspect = 1.0f private
Definition at line 83 of file PointLightShadowMap.h.
Referenced by updateDepthMap(), and updateDepthMapResolution().
DEPTH_MAP_HEIGHT
unsigned int PointLightShadowMap::DEPTH_MAP_HEIGHT = 512 private
Definition at line 78 of file PointLightShadowMap.h.
Referenced by getDepthMapHeight(), setDepthMapResolution(), updateDepthMap(), and updateDepthMapResolution().
DEPTH_MAP_WIDTH
unsigned int PointLightShadowMap::DEPTH_MAP_WIDTH = 512 private
Definition at line 77 of file PointLightShadowMap.h.
Referenced by getDepthMapWidth(), setDepthMapResolution(), updateDepthMap(), and updateDepthMapResolution().
depthCubeMap
GLuint PointLightShadowMap::depthCubeMap = 0 private
Definition at line 85 of file PointLightShadowMap.h.
Referenced by getCubeMap(), initialize(), updateDepthMapResolution(), and ~PointLightShadowMap().
depthMapFBO
GLuint PointLightShadowMap::depthMapFBO = 0 private
Definition at line 84 of file PointLightShadowMap.h.
Referenced by getFBO(), initialize(), updateDepthMap(), and ~PointLightShadowMap().
depthMapShader
Shader PointLightShadowMap::depthMapShader private
Definition at line 87 of file PointLightShadowMap.h.
Referenced by getDepthMapShader(), initialize(), and updateDepthMap().
farPlane
GLfloat PointLightShadowMap::farPlane = 100.0f private
Definition at line 82 of file PointLightShadowMap.h.
Referenced by getFarPlane(), and updateDepthMap().
FOV
const float PointLightShadowMap::FOV = glm::radians(90.0f)
Definition at line 16 of file PointLightShadowMap.h.
Referenced by updateDepthMap().
initialized
bool PointLightShadowMap::initialized = false private
Definition at line 90 of file PointLightShadowMap.h.
Referenced by initialize(), and ~PointLightShadowMap().
lightPosition
glm::vec3 PointLightShadowMap::lightPosition = glm::vec3(0, 6, 0) private
Definition at line 88 of file PointLightShadowMap.h.
Referenced by getCurrentLightPosition(), getShadowTransformation(), setCurrentLightPosition(), and updateDepthMap().
lightSupplied
bool PointLightShadowMap::lightSupplied = false private
Definition at line 80 of file PointLightShadowMap.h.
Referenced by isActive(), and setShadowActive().
nearPlane
GLfloat PointLightShadowMap::nearPlane = .10f private
Definition at line 81 of file PointLightShadowMap.h.
Referenced by updateDepthMap().
shadowProjection
glm::mat4 PointLightShadowMap::shadowProjection = glm::perspective(FOV, aspect, nearPlane, farPlane) private
Definition at line 89 of file PointLightShadowMap.h.
Referenced by getShadowTransformation(), and updateDepthMap().
shadowTransforms
glm::mat4 PointLightShadowMap::shadowTransforms[6] private
Initial value:
= {
        glm::mat4(1.0f),
        glm::mat4(1.0f),
        glm::mat4(1.0f),
        glm::mat4(1.0f),
        glm::mat4(1.0f),
        glm::mat4(1.0f)
    }
Definition at line 67 of file PointLightShadowMap.h.
Referenced by updateDepthMap().
The documentation for this class was generated from the following files:
src/PointLightShadowMap.h
src/PointLightShadowMap.cpp