LightShow_Boilerplate: PlayerCameraHandlingSystem Class Reference
PlayerCameraHandlingSystem Class Reference
#include <PlayerCameraHandlingSystem.h>
Public Member Functions
void setThirdPersonCameraTargetPosition (PlayerCameraHandler &playerController, const Transform &modelsTransform, Camera &camera)
Detailed Description
Definition at line 8 of file PlayerCameraHandlingSystem.h.
Member Function Documentation
setThirdPersonCameraTargetPosition()
void PlayerCameraHandlingSystem::setThirdPersonCameraTargetPosition (PlayerCameraHandler & playerController, const Transform & modelsTransform, Camera & camera) inline
Definition at line 11 of file PlayerCameraHandlingSystem.h.
References PlayerCameraHandler::getCameraTargetOffset(), Transform::position, and Camera::setTargetPosition().
Referenced by UpdatingSystem::update().
The documentation for this class was generated from the following file:
src/game/systems/subsystems/PlayerCameraHandlingSystem.h