LightShow_Boilerplate: Messenger< T > Class Template Reference
Messenger< T > Class Template Reference
#include <Messenger.h>
Public Member Functions
void AddMessage (const T &message)
bool getMessagesThenRemove (T &msg)
bool findThenRemoveMessage (T msg)
void clearAll ()
Private Attributes
int numberOfCurrentMessages = 0
std::vector< T > messageList = std::vector<T>(GameInfo::DEFAULT_MESSAGE_CAPACITY)
Detailed Description
template<class T>
class Messenger< T >
Definition at line 9 of file Messenger.h.
Member Function Documentation
AddMessage()
template<class T > void Messenger< T >::AddMessage (const T & message) inline
Definition at line 12 of file Messenger.h.
Referenced by Window::resizeWindow().
clearAll()
template<class T > void Messenger< T >::clearAll () inline
Definition at line 45 of file Messenger.h.
findThenRemoveMessage()
template<class T > bool Messenger< T >::findThenRemoveMessage (T msg) inline
Definition at line 33 of file Messenger.h.
getMessagesThenRemove()
template<class T > bool Messenger< T >::getMessagesThenRemove (T & msg) inline
Definition at line 22 of file Messenger.h.
Referenced by Game::readBackendEventQueue().
Member Data Documentation
messageList
template<class T > std::vector<T> Messenger< T >::messageList = std::vector<T>(GameInfo::DEFAULT_MESSAGE_CAPACITY) private
Definition at line 51 of file Messenger.h.
Referenced by Messenger< BackEndMessages >::AddMessage(), Messenger< BackEndMessages >::findThenRemoveMessage(), and Messenger< BackEndMessages >::getMessagesThenRemove().
numberOfCurrentMessages
template<class T > int Messenger< T >::numberOfCurrentMessages = 0 private
Definition at line 50 of file Messenger.h.
Referenced by Messenger< BackEndMessages >::AddMessage(), Messenger< BackEndMessages >::clearAll(), Messenger< BackEndMessages >::findThenRemoveMessage(), and Messenger< BackEndMessages >::getMessagesThenRemove().
The documentation for this class was generated from the following file:
src/Messenger.h