LightShow_Boilerplate: UserControls Class Reference
UserControls Class Reference
#include <UserControls.h>
Classes
struct GuiControls
struct PlayerControls
Public Member Functions
SDL_Keycode getPlayerForwardKey () const
SDL_Keycode getPlayerBackwardsKey () const
SDL_Keycode getPlayerLeftKey () const
SDL_Keycode getPlayerRightKey () const
SDL_Keycode getPlayerJumpKey () const
SDL_Keycode getPlayerViewKey () const
SDL_Keycode getGuiControlPauseMenuKey () const
Public Member Functions inherited from Component< UserControls >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
GuiControls guiControls
PlayerControls playerControls
Additional Inherited Members
Static Public Attributes inherited from Component< UserControls >
static int32_t type
Detailed Description
Definition at line 6 of file UserControls.h.
Member Function Documentation
getGuiControlPauseMenuKey()
SDL_Keycode UserControls::getGuiControlPauseMenuKey () const inline
Definition at line 15 of file UserControls.h.
References guiControls, and UserControls::GuiControls::openPauseMenu.
Referenced by PauseMenuSystem::update().
getPlayerBackwardsKey()
SDL_Keycode UserControls::getPlayerBackwardsKey () const inline
Definition at line 10 of file UserControls.h.
References UserControls::PlayerControls::backwardsKey, and playerControls.
Referenced by PlayerControllerSystem::getPlayerInput().
getPlayerForwardKey()
SDL_Keycode UserControls::getPlayerForwardKey () const inline
Definition at line 9 of file UserControls.h.
References UserControls::PlayerControls::forwardKey, and playerControls.
Referenced by PlayerControllerSystem::getPlayerInput().
getPlayerJumpKey()
SDL_Keycode UserControls::getPlayerJumpKey () const inline
Definition at line 13 of file UserControls.h.
References UserControls::PlayerControls::jumpKey, and playerControls.
Referenced by PlayerControllerSystem::getPlayerInput().
getPlayerLeftKey()
SDL_Keycode UserControls::getPlayerLeftKey () const inline
Definition at line 11 of file UserControls.h.
References UserControls::PlayerControls::leftKey, and playerControls.
Referenced by PlayerControllerSystem::getPlayerInput().
getPlayerRightKey()
SDL_Keycode UserControls::getPlayerRightKey () const inline
Definition at line 12 of file UserControls.h.
References playerControls, and UserControls::PlayerControls::rightKey.
Referenced by PlayerControllerSystem::getPlayerInput().
getPlayerViewKey()
SDL_Keycode UserControls::getPlayerViewKey () const inline
Definition at line 14 of file UserControls.h.
References playerControls, and UserControls::PlayerControls::viewKey.
Referenced by PlayerControllerSystem::getPlayerInput().
Member Data Documentation
guiControls
GuiControls UserControls::guiControls private
Definition at line 33 of file UserControls.h.
Referenced by getGuiControlPauseMenuKey().
playerControls
PlayerControls UserControls::playerControls private
Definition at line 35 of file UserControls.h.
Referenced by getPlayerBackwardsKey(), getPlayerForwardKey(), getPlayerJumpKey(), getPlayerLeftKey(), getPlayerRightKey(), and getPlayerViewKey().
The documentation for this class was generated from the following file:
src/UserControls.h