LightShow_Boilerplate: DisplayStatistics Class Reference
DisplayStatistics Class Reference
#include <DisplayStatistics.h>
Public Member Functions
void initialize (TextMap &textMap, Texture &texture)
Public Member Functions inherited from Component< DisplayStatistics >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Private Attributes
GuiString guiString = GuiString(20)
float lastUnit = 0
float currentInterval = 0.f
std::string currentFPS = "0"
std::string currentMSPF = "0"
int lastFPS = 0
Friends
class DisplayStatisticsSystem
Additional Inherited Members
Static Public Attributes inherited from Component< DisplayStatistics >
static int32_t type
Detailed Description
Definition at line 9 of file DisplayStatistics.h.
Member Function Documentation
initialize()
void DisplayStatistics::initialize (TextMap & textMap, Texture & texture) inline
Definition at line 12 of file DisplayStatistics.h.
References guiString, and GuiString::initialize().
Referenced by Player::initialize().
Friends And Related Function Documentation
DisplayStatisticsSystem
friend class DisplayStatisticsSystem friend
Definition at line 26 of file DisplayStatistics.h.
Member Data Documentation
currentFPS
std::string DisplayStatistics::currentFPS = "0" private
Definition at line 22 of file DisplayStatistics.h.
Referenced by DisplayStatisticsSystem::fixedUpdate().
currentInterval
float DisplayStatistics::currentInterval = 0.f private
Definition at line 21 of file DisplayStatistics.h.
currentMSPF
std::string DisplayStatistics::currentMSPF = "0" private
Definition at line 23 of file DisplayStatistics.h.
Referenced by DisplayStatisticsSystem::fixedUpdate().
guiString
GuiString DisplayStatistics::guiString = GuiString(20) private
Definition at line 17 of file DisplayStatistics.h.
Referenced by DisplayStatisticsSystem::fixedUpdate(), initialize(), and DisplayStatisticsSystem::render().
lastFPS
int DisplayStatistics::lastFPS = 0 private
Definition at line 24 of file DisplayStatistics.h.
Referenced by DisplayStatisticsSystem::fixedUpdate().
lastUnit
float DisplayStatistics::lastUnit = 0 private
Definition at line 19 of file DisplayStatistics.h.
Referenced by DisplayStatisticsSystem::fixedUpdate().
The documentation for this class was generated from the following file:
src/DisplayStatistics.h