LightShow_Boilerplate: CameraSystem Class Reference
CameraSystem Class Reference
#include <CameraSystem.h>
Public Member Functions
void initializeCamera (Camera &camera)
void update (Camera &camera)
void refreshCamera (Camera &camera)
Detailed Description
Definition at line 11 of file CameraSystem.h.
Member Function Documentation
initializeCamera()
void CameraSystem::initializeCamera (Camera & camera)
Definition at line 3 of file CameraSystem.cpp.
References refreshCamera().
Referenced by FixedUpdatingSystem::initialize().
refreshCamera()
void CameraSystem::refreshCamera (Camera & camera)
Definition at line 37 of file CameraSystem.cpp.
References Camera::currentFOV, Camera::farPlane, GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), Camera::nearPlane, and Camera::projectionMatrix.
Referenced by FixedUpdatingSystem::handleBackEndMessage(), and initializeCamera().
update()
void CameraSystem::update (Camera & camera)
Definition at line 7 of file CameraSystem.cpp.
References Camera::cameraDistance, Camera::cameraFront, Camera::getCameraDistance(), GameInfo::getDeltaTime(), Input::getMouseDelta(), Locator< Input, NullInput >::getService(), Camera::position, Camera::rotation, Camera::setCameraDistance(), Camera::speed, hh::sphericalToCartisean(), Camera::targetPosition, and Camera::viewMatrix.
Referenced by UpdatingSystem::update().
The documentation for this class was generated from the following files:
src/CameraSystem.h
src/CameraSystem.cpp