LightShow_Boilerplate: Engine::Game Class Reference
Engine::Game Class Reference
Handles the Game's physics, scene loading, rendering, and updating. Managed by Application.
#include <Game.h>
Public Member Functions
void initialize (Time *time, Messenger< BackEndMessages > *backEndMessagingSystem)
void fixedUpdate ()
void render ()
void update ()
void uninitialize ()
void loadScene (int scene)
Loads a scene by index- should be called in fixedUpdate.
int getCurrentSceneIndex () const
int getSceneCount () const
Private Member Functions
bool areVitalsNull ()
Checks for null vitals.
void initializeShaders ()
void readBackendEventQueue ()
void freeEntities ()
Private Attributes
Messenger< BackEndMessages > * backEndMessages = nullptr
Messenger to recieve messages from Application.
Time * currentTime = nullptr
GameState gameState = GameState(*this)
Used to provide Game info to UpdatingSystem, FixedUpdatingSystem, and RenderingSystem without exposing the Game.
Settings settings = Settings(GameInfo::DEFAULT_GRAVITY, glm::vec3(-20, 0, 10))
PointLightShadowMap pointLightDepthMap
DirectionalLightShadowMap directionalLightDepthMap
RenderTexture renderTexture
UpdatingSystem updatingSystem
The main system used for updating the game based on the Scene's components.
FixedUpdatingSystem fixedUpdatingSystem
The main system used for fixed updating the game based on the Scene's components.
RenderingSystem renderingSystem
The main system used for rendering game the game based on the Scene's components.
SubSystems subSystems
Small systems that are used inside of the UpdatingSystem, FixedUpdatingSystem, and RenderingSystem.
Scene * scene = new Scene()
Current scene.
PhysicsWorld * physicsWorld = new PhysicsWorld(hh::toBtVec3(GameInfo::DEFAULT_GRAVITY))
Current PhysicsWorld used along with the Scene.
std::vector< EntityWrapper * > sceneEntities
int currentScene = 0
The current scene index.
TextMap map
Font atlas to be used in the game.
Detailed Description
Handles the Game's physics, scene loading, rendering, and updating. Managed by Application.
Definition at line 14 of file Game.h.
Member Function Documentation
areVitalsNull()
bool Engine::Game::areVitalsNull () private
Checks for null vitals.
Definition at line 3 of file Game.cpp.
References backEndMessages, currentTime, and DBG_LOG.
fixedUpdate()
void Engine::Game::fixedUpdate ()
Definition at line 105 of file Game.cpp.
Referenced by Engine::Application::fixedUpdate().
freeEntities()
void Engine::Game::freeEntities () private
Definition at line 127 of file Game.cpp.
getCurrentSceneIndex()
int Engine::Game::getCurrentSceneIndex () const inline
Definition at line 28 of file Game.h.
References currentScene.
Referenced by GameState::getCurrentSceneIndex().
getSceneCount()
int Engine::Game::getSceneCount () const inline
Definition at line 31 of file Game.h.
References scenes.
Referenced by GameState::getSceneCount().
initialize()
void Engine::Game::initialize (Time * time, Messenger< BackEndMessages > * backEndMessagingSystem)
Definition at line 12 of file Game.cpp.
References Entities::registerEntities().
Referenced by Engine::Application::initialize().
initializeShaders()
void Engine::Game::initializeShaders () private
Definition at line 30 of file Game.cpp.
References GameInfo::getWindowHeight(), GameInfo::getWindowWidth(), Shader::setShaderTask(), and Shader::setShaderTaskShader().
loadScene()
void Engine::Game::loadScene (int scene)
Loads a scene by index- should be called in fixedUpdate.
Definition at line 41 of file Game.cpp.
References Entities::allocateEntity(), DBG_LOG, GameInfo::DEFAULT_GRAVITY, scenes, and hh::toBtVec3().
Referenced by GameState::loadScene().
readBackendEventQueue()
void Engine::Game::readBackendEventQueue () private
Definition at line 98 of file Game.cpp.
render()
void Engine::Game::render ()
Definition at line 119 of file Game.cpp.
Referenced by Engine::Application::render().
uninitialize()
void Engine::Game::uninitialize ()
Definition at line 138 of file Game.cpp.
Referenced by Engine::Application::uninitialize().
update()
void Engine::Game::update ()
Definition at line 115 of file Game.cpp.
Referenced by Engine::Application::update().
Member Data Documentation
backEndMessages
Messenger<BackEndMessages>* Engine::Game::backEndMessages = nullptr private
Messenger to recieve messages from Application.
Definition at line 37 of file Game.h.
Referenced by areVitalsNull().
currentScene
int Engine::Game::currentScene = 0 private
The current scene index.
Definition at line 79 of file Game.h.
Referenced by getCurrentSceneIndex().
currentTime
Time* Engine::Game::currentTime = nullptr private
Definition at line 38 of file Game.h.
Referenced by areVitalsNull().
directionalLightDepthMap
DirectionalLightShadowMap Engine::Game::directionalLightDepthMap private
Definition at line 55 of file Game.h.
fixedUpdatingSystem
FixedUpdatingSystem Engine::Game::fixedUpdatingSystem private
The main system used for fixed updating the game based on the Scene's components.
Definition at line 62 of file Game.h.
gameState
GameState Engine::Game::gameState = GameState(*this) private
Used to provide Game info to UpdatingSystem, FixedUpdatingSystem, and RenderingSystem without exposing the Game.
Definition at line 41 of file Game.h.
map
TextMap Engine::Game::map private
Font atlas to be used in the game.
Definition at line 83 of file Game.h.
physicsWorld
PhysicsWorld* Engine::Game::physicsWorld = new PhysicsWorld(hh::toBtVec3(GameInfo::DEFAULT_GRAVITY)) private
Current PhysicsWorld used along with the Scene.
Definition at line 74 of file Game.h.
pointLightDepthMap
PointLightShadowMap Engine::Game::pointLightDepthMap private
Definition at line 54 of file Game.h.
renderingSystem
RenderingSystem Engine::Game::renderingSystem private
The main system used for rendering game the game based on the Scene's components.
Definition at line 65 of file Game.h.
renderTexture
RenderTexture Engine::Game::renderTexture private
Definition at line 56 of file Game.h.
scene
Scene* Engine::Game::scene = new Scene() private
Current scene.
Definition at line 71 of file Game.h.
sceneEntities
std::vector<EntityWrapper*> Engine::Game::sceneEntities private
Definition at line 76 of file Game.h.
settings
Settings Engine::Game::settings = Settings(GameInfo::DEFAULT_GRAVITY, glm::vec3(-20, 0, 10)) private
Definition at line 51 of file Game.h.
subSystems
SubSystems Engine::Game::subSystems private
Small systems that are used inside of the UpdatingSystem, FixedUpdatingSystem, and RenderingSystem.
Definition at line 68 of file Game.h.
updatingSystem
UpdatingSystem Engine::Game::updatingSystem private
The main system used for updating the game based on the Scene's components.
Definition at line 59 of file Game.h.
The documentation for this class was generated from the following files:
src/Game.h
src/Game.cpp