LightShow_Boilerplate: Material Struct Reference
Material Struct Reference
#include <Material.h>
Public Attributes
glm::vec3 ambient = glm::vec3(.6f, .6f, .65f)
glm::vec3 diffuse = glm::vec3(.6f, .6f, .65f)
glm::vec3 specular = glm::vec3(.9f, .9f, .9f)
float shininess = 8.0f
Additional Inherited Members
Public Member Functions inherited from Component< Material >
virtual ~Component ()
int32_t getType () const
Public Member Functions inherited from ComponentInterface
virtual ~ComponentInterface ()
virtual int32_t getType () const =0
int32_t getEntityID () const
void setEntityID (int32_t id)
bool isActive () const
void setActive (bool isActive)
Static Public Attributes inherited from Component< Material >
static int32_t type
Detailed Description
Definition at line 5 of file Material.h.
Member Data Documentation
ambient
glm::vec3 Material::ambient = glm::vec3(.6f, .6f, .65f)
Definition at line 6 of file Material.h.
Referenced by Shader::setMaterial().
diffuse
glm::vec3 Material::diffuse = glm::vec3(.6f, .6f, .65f)
Definition at line 7 of file Material.h.
Referenced by Shader::setMaterial().
shininess
float Material::shininess = 8.0f
Definition at line 9 of file Material.h.
Referenced by FloorObject::initialize(), and Shader::setMaterial().
specular
glm::vec3 Material::specular = glm::vec3(.9f, .9f, .9f)
Definition at line 8 of file Material.h.
Referenced by Shader::setMaterial().
The documentation for this struct was generated from the following file:
src/Material.h