LightShow_Boilerplate: Settings Class Reference
Settings Class Reference
#include <Settings.h>
Public Member Functions
Settings (glm::vec3 gravity, glm::vec3 wind)
glm::vec3 getGravity () const
glm::vec3 getWind () const
unsigned short getLightsPerEntity () const
unsigned short getShadowFilterAmount () const
float getShadowIntensity () const
void setWorldWind (glm::vec3 wind)
void setWorldGravity (glm::vec3 gravity)
void setAmountOfLightsPerEntity (unsigned short amount)
void setShadowIntensity (float intensity)
void setShadowFilteringAmount (unsigned short filterAmount)
Public Attributes
const unsigned short MIN_AMOUNT_LIGHTS_PER_ENTITY = 0
const unsigned short MAX_AMOUNT_LIGHTS_PER_ENTITY = 50
const unsigned short MIN_FILTER_AMOUNT = 0
const unsigned short MAX_FILTER_AMOUNT = 20
const float MIN_SHADOW_INTENSITY = 0.5f
const float MAX_SHADOW_INTENSITY = 7
Private Attributes
unsigned short amountOfLightsPerEntity = 10
unsigned short shadowFilteringAmount = 4
float shadowIntesity = 1.f
glm::vec3 worldWind
glm::vec3 worldGravity
Detailed Description
Definition at line 3 of file Settings.h.
Constructor & Destructor Documentation
Settings()
Settings::Settings (glm::vec3 gravity, glm::vec3 wind) inline
Definition at line 6 of file Settings.h.
References worldGravity, and worldWind.
Member Function Documentation
getGravity()
glm::vec3 Settings::getGravity () const inline
Definition at line 20 of file Settings.h.
References worldGravity.
Referenced by FountainParticleSystem::performParticleCalculations().
getLightsPerEntity()
unsigned short Settings::getLightsPerEntity () const inline
Definition at line 23 of file Settings.h.
References amountOfLightsPerEntity.
Referenced by LightTest::initialize(), Shader::recompileShader(), Shader::setPointLight(), Shader::Shader(), and Shader::updateTagValues().
getShadowFilterAmount()
unsigned short Settings::getShadowFilterAmount () const inline
Definition at line 24 of file Settings.h.
References shadowFilteringAmount.
Referenced by Shader::updateTagValues().
getShadowIntensity()
float Settings::getShadowIntensity () const inline
Definition at line 25 of file Settings.h.
References shadowIntesity.
Referenced by Shader::updateTagValues().
getWind()
glm::vec3 Settings::getWind () const inline
Definition at line 21 of file Settings.h.
References worldWind.
Referenced by FountainParticleSystem::performParticleCalculations().
setAmountOfLightsPerEntity()
void Settings::setAmountOfLightsPerEntity (unsigned short amount) inline
Definition at line 30 of file Settings.h.
References amountOfLightsPerEntity, MAX_AMOUNT_LIGHTS_PER_ENTITY, and MIN_AMOUNT_LIGHTS_PER_ENTITY.
setShadowFilteringAmount()
void Settings::setShadowFilteringAmount (unsigned short filterAmount) inline
Definition at line 42 of file Settings.h.
References MAX_FILTER_AMOUNT, MIN_FILTER_AMOUNT, and shadowFilteringAmount.
setShadowIntensity()
void Settings::setShadowIntensity (float intensity) inline
Definition at line 36 of file Settings.h.
References MAX_SHADOW_INTENSITY, MIN_SHADOW_INTENSITY, and shadowIntesity.
setWorldGravity()
void Settings::setWorldGravity (glm::vec3 gravity) inline
Definition at line 28 of file Settings.h.
References worldGravity.
setWorldWind()
void Settings::setWorldWind (glm::vec3 wind) inline
Definition at line 27 of file Settings.h.
References worldWind.
Member Data Documentation
amountOfLightsPerEntity
unsigned short Settings::amountOfLightsPerEntity = 10 private
Definition at line 49 of file Settings.h.
Referenced by getLightsPerEntity(), and setAmountOfLightsPerEntity().
MAX_AMOUNT_LIGHTS_PER_ENTITY
const unsigned short Settings::MAX_AMOUNT_LIGHTS_PER_ENTITY = 50
Definition at line 13 of file Settings.h.
Referenced by setAmountOfLightsPerEntity().
MAX_FILTER_AMOUNT
const unsigned short Settings::MAX_FILTER_AMOUNT = 20
Definition at line 15 of file Settings.h.
Referenced by setShadowFilteringAmount().
MAX_SHADOW_INTENSITY
const float Settings::MAX_SHADOW_INTENSITY = 7
Definition at line 18 of file Settings.h.
Referenced by setShadowIntensity().
MIN_AMOUNT_LIGHTS_PER_ENTITY
const unsigned short Settings::MIN_AMOUNT_LIGHTS_PER_ENTITY = 0
Definition at line 12 of file Settings.h.
Referenced by setAmountOfLightsPerEntity().
MIN_FILTER_AMOUNT
const unsigned short Settings::MIN_FILTER_AMOUNT = 0
Definition at line 14 of file Settings.h.
Referenced by setShadowFilteringAmount().
MIN_SHADOW_INTENSITY
const float Settings::MIN_SHADOW_INTENSITY = 0.5f
Definition at line 17 of file Settings.h.
Referenced by setShadowIntensity().
shadowFilteringAmount
unsigned short Settings::shadowFilteringAmount = 4 private
Definition at line 50 of file Settings.h.
Referenced by getShadowFilterAmount(), and setShadowFilteringAmount().
shadowIntesity
float Settings::shadowIntesity = 1.f private
Definition at line 51 of file Settings.h.
Referenced by getShadowIntensity(), and setShadowIntensity().
worldGravity
glm::vec3 Settings::worldGravity private
Definition at line 53 of file Settings.h.
Referenced by getGravity(), Settings(), and setWorldGravity().
worldWind
glm::vec3 Settings::worldWind private
Definition at line 52 of file Settings.h.
Referenced by getWind(), Settings(), and setWorldWind().
The documentation for this class was generated from the following file:
src/Settings.h