LightShow_Boilerplate: GameInfo Namespace Reference
GameInfo Namespace Reference
Functions
float getDeltaTime ()
void terminateGame ()
int getWindowWidth ()
int getWindowHeight ()
void setMousePosition (int xPos, int yPos)
Variables
const glm::vec3 GLM_VEC3_ZERO = glm::vec3(0, 0, 0)
const btVector3 BT_VEC3_ZERO = btVector3(0, 0, 0)
const unsigned int MAX_COLLISION_TRIGGERS_AT_ONCE = 5
const unsigned short DEFAULT_MESSAGE_CAPACITY = 10
const float fixedDeltaTime = 1.f / 30.f
const short PHYSICS_MAX_SUBSTEPS = 1
const float PHYSICS_TIME_STEP = fixedDeltaTime
const std::string WINDOW_TITLE = "Prototype #1 (Hopefully the last)"
const glm::vec4 DEBUG_COLOR = glm::vec4(0.0f, 0.7f, 0.3f, 1.0f)
const glm::vec3 DEFAULT_GRAVITY = glm::vec3(0.0f, -9.81f, 0.0f)
const unsigned short START_WINDOW_WIDTH = 800
const unsigned short START_WINDOW_HEIGHT = 600
const unsigned short MIN_WINDOW_HEIGHT = 300
const unsigned short MIN_WINDOW_WIDTH = 400
Function Documentation
getDeltaTime()
float GameInfo::getDeltaTime ()
Definition at line 4 of file GameInfo.cpp.
References PrivateGameInfo::deltaTime.
Referenced by DefaultParticleSystem::performParticleCalculations(), FountainParticleSystem::performParticleCalculations(), DefaultParticleSystem::setParticleToDefault(), CameraSystem::update(), and Time::updateFPS().
getWindowHeight()
int GameInfo::getWindowHeight ()
Definition at line 14 of file Application.cpp.
References Application::getGameWindowHeight().
Referenced by FixedUpdatingSystem::fixedUpdate(), GUIResizingInformation::getBottomScreenPosition(), Input::getMouseDelta(), GUIResizingInformation::getTopScreenPosition(), FixedUpdatingSystem::handleBackEndMessage(), Application::initializeSDL(), Game::initializeShaders(), GuiButton::mouseCoordsToScreenCoords(), CameraSystem::refreshCamera(), RenderingSystem::render(), PauseMenuSystem::render(), Quad::render3D(), and GUIResizingInformation::updateInformation().
getWindowWidth()
int GameInfo::getWindowWidth ()
Definition at line 10 of file Application.cpp.
References Application::getGameWindowWidth().
Referenced by FixedUpdatingSystem::fixedUpdate(), GUIResizingInformation::getLeftScreenPosition(), Input::getMouseDelta(), GUIResizingInformation::getRightScreenPosition(), FixedUpdatingSystem::handleBackEndMessage(), Application::initializeSDL(), Game::initializeShaders(), GuiButton::mouseCoordsToScreenCoords(), CameraSystem::refreshCamera(), RenderingSystem::render(), PauseMenuSystem::render(), Quad::render3D(), and GUIResizingInformation::updateInformation().
setMousePosition()
void GameInfo::setMousePosition (int xPos, int yPos)
Definition at line 18 of file Application.cpp.
References Application::setMousePosition().
Referenced by FixedUpdatingSystem::fixedUpdate(), and Application::initializeSDL().
terminateGame()
void GameInfo::terminateGame ()
Definition at line 6 of file Application.cpp.
References Application::isRunning.
Referenced by Input::handleEvents(), and NullInput::handleEvents().
Variable Documentation
BT_VEC3_ZERO
const btVector3 GameInfo::BT_VEC3_ZERO = btVector3(0, 0, 0)
Definition at line 49 of file GameInfo.h.
DEBUG_COLOR
const glm::vec4 GameInfo::DEBUG_COLOR = glm::vec4(0.0f, 0.7f, 0.3f, 1.0f)
Definition at line 71 of file GameInfo.h.
DEFAULT_GRAVITY
const glm::vec3 GameInfo::DEFAULT_GRAVITY = glm::vec3(0.0f, -9.81f, 0.0f)
Definition at line 74 of file GameInfo.h.
Referenced by Game::fixedUpdate().
DEFAULT_MESSAGE_CAPACITY
const unsigned short GameInfo::DEFAULT_MESSAGE_CAPACITY = 10
Definition at line 54 of file GameInfo.h.
Referenced by Messenger< BackEndMessages >::AddMessage().
fixedDeltaTime
const float GameInfo::fixedDeltaTime = 1.f / 30.f
Definition at line 57 of file GameInfo.h.
Referenced by PhysicsWorld::fixedUpdate(), DayNightCycleSystem::fixedUpdate(), _3DM::AnimatedModel::fixedUpdateAnimation(), DefaultParticleSystem::fixedUpdateParticles(), PlayerController::getResistance(), PlayerControllerSystem::getSlopeSpeed(), and Application::run().
GLM_VEC3_ZERO
const glm::vec3 GameInfo::GLM_VEC3_ZERO = glm::vec3(0, 0, 0)
Definition at line 48 of file GameInfo.h.
Referenced by BoneCollisionMesh::getColliderOffset().
MAX_COLLISION_TRIGGERS_AT_ONCE
const unsigned int GameInfo::MAX_COLLISION_TRIGGERS_AT_ONCE = 5
Definition at line 51 of file GameInfo.h.
Referenced by PhysicsWorld::fixedUpdate().
MIN_WINDOW_HEIGHT
const unsigned short GameInfo::MIN_WINDOW_HEIGHT = 300
Definition at line 83 of file GameInfo.h.
Referenced by Application::initializeSDL().
MIN_WINDOW_WIDTH
const unsigned short GameInfo::MIN_WINDOW_WIDTH = 400
Definition at line 86 of file GameInfo.h.
Referenced by Application::initializeSDL().
PHYSICS_MAX_SUBSTEPS
const short GameInfo::PHYSICS_MAX_SUBSTEPS = 1
Definition at line 62 of file GameInfo.h.
Referenced by PhysicsWorld::fixedUpdate().
PHYSICS_TIME_STEP
const float GameInfo::PHYSICS_TIME_STEP = fixedDeltaTime
Definition at line 65 of file GameInfo.h.
Referenced by PhysicsWorld::fixedUpdate().
START_WINDOW_HEIGHT
const unsigned short GameInfo::START_WINDOW_HEIGHT = 600
Definition at line 80 of file GameInfo.h.
Referenced by GUIResizingInformation::updateInformation().
START_WINDOW_WIDTH
const unsigned short GameInfo::START_WINDOW_WIDTH = 800
Definition at line 77 of file GameInfo.h.
Referenced by GUIResizingInformation::updateInformation().
WINDOW_TITLE
const std::string GameInfo::WINDOW_TITLE = "Prototype #1 (Hopefully the last)"
Definition at line 68 of file GameInfo.h.