LightShow_Boilerplate: Engine::Window Class Reference
Engine::Window Class Reference
Handles all of the window logic for the application.
#include <Window.h>
Public Member Functions
Window (unsigned int w, unsigned int h, const std::string &title)
Window ()
~Window ()
void initialize ()
Creates window.
void handleEvents (SDL_Event &eventSystem, SDL_WindowEventID windowEvent, Messenger< BackEndMessages > &msgr)
Handles sdl events such as resizing.
void setWindowTitle (const std::string &title)
unsigned int getWidth () const
unsigned int getHeight () const
std::string getCurrentTitle () const
SDL_Window *const getWindow () const
Private Member Functions
void resizeWindow (int w, int h, Messenger< BackEndMessages > &msgr)
glm::ivec2 getDeviceMaxScreenSize ()
Returns max screen size.
Private Attributes
std::string windowTitle = ""
SDL_Window * gameWindow = nullptr
SDL_GLContext glContext = nullptr
unsigned int width = 640
unsigned int height = 400
Detailed Description
Handles all of the window logic for the application.
Definition at line 13 of file Window.h.
Constructor & Destructor Documentation
Window() [1/2]
Engine::Window::Window (unsigned int w, unsigned int h, const std::string & title)
Definition at line 2 of file Window.cpp.
References height, width, and windowTitle.
Window() [2/2]
Engine::Window::Window () inline
Definition at line 16 of file Window.h.
~Window()
Engine::Window::~Window ()
Definition at line 7 of file Window.cpp.
References Engine::gameWindow.
Member Function Documentation
getCurrentTitle()
std::string Engine::Window::getCurrentTitle () const inline
Definition at line 29 of file Window.h.
References windowTitle.
getDeviceMaxScreenSize()
glm::ivec2 Engine::Window::getDeviceMaxScreenSize () private
Returns max screen size.
Definition at line 56 of file Window.cpp.
References DBG_LOG.
getHeight()
unsigned int Engine::Window::getHeight () const inline
Definition at line 28 of file Window.h.
References height.
Referenced by Engine::getGameWindowHeight().
getWidth()
unsigned int Engine::Window::getWidth () const inline
Definition at line 27 of file Window.h.
References width.
Referenced by Engine::getGameWindowWidth().
getWindow()
SDL_Window* const Engine::Window::getWindow () const inline
Definition at line 30 of file Window.h.
References gameWindow.
Referenced by Engine::Application::initializeSDL(), Engine::Application::render(), and Engine::setMousePosition().
handleEvents()
void Engine::Window::handleEvents (SDL_Event & eventSystem, SDL_WindowEventID windowEvent, Messenger< BackEndMessages > & msgr)
Handles sdl events such as resizing.
Definition at line 26 of file Window.cpp.
References DBG_LOG.
Referenced by Engine::Application::update().
initialize()
void Engine::Window::initialize ()
Creates window.
Definition at line 11 of file Window.cpp.
References Engine::gameWindow.
Referenced by Engine::Application::initializeSDL().
resizeWindow()
void Engine::Window::resizeWindow (int w, int h, Messenger< BackEndMessages > & msgr) private
Definition at line 48 of file Window.cpp.
References Messenger< T >::addMessage(), Engine::gameWindow, and REFRESH_CAMERA.
setWindowTitle()
void Engine::Window::setWindowTitle (const std::string & title)
Definition at line 43 of file Window.cpp.
References Engine::gameWindow.
Member Data Documentation
gameWindow
SDL_Window* Engine::Window::gameWindow = nullptr private
Definition at line 39 of file Window.h.
Referenced by getWindow().
glContext
SDL_GLContext Engine::Window::glContext = nullptr private
Definition at line 40 of file Window.h.
height
unsigned int Engine::Window::height = 400 private
Definition at line 43 of file Window.h.
Referenced by getHeight(), and Window().
width
unsigned int Engine::Window::width = 640 private
Definition at line 42 of file Window.h.
Referenced by getWidth(), and Window().
windowTitle
std::string Engine::Window::windowTitle = "" private
Definition at line 37 of file Window.h.
Referenced by getCurrentTitle(), and Window().
The documentation for this class was generated from the following files:
src/engine/main/Window.h
src/engine/main/Window.cpp